### ISSUE TITLE
add files to local gitignore ( .git/info/exclude ) 

### ISSUE THREAD

**Issue by divinity76** [git-cola/git-cola#1000]
would be nice if we could add files to local .git/info/exclude the same way we can add files to .gitignore from the menu here:

![image](https://user-images.githubusercontent.com/1874996/67151380-d35bd200-f2c5-11e9-92a2-730c99098f8c.png)

for example, here is SmartGit's hide file menu (a similar git GUI program):

![image](https://user-images.githubusercontent.com/1874996/67151397-0dc56f00-f2c6-11e9-825b-3a61987eaeda.png)

![image](https://user-images.githubusercontent.com/1874996/67151369-97287180-f2c5-11e9-83a5-2ac8674d9878.png)

would be nice if git-cola could get something similar :)

**Comment by davvid** [comment]
Great idea.  This should be relatively easy to implement too by reusing the existing approach and adapting it for the local `.git/info/exclude`.  I would totally use this often.
