### ISSUE TITLE
Crash on repo open

### ISSUE THREAD

**Issue by akontsevich** [git-cola/git-cola#1015]
Began to crash on repo open again: https://github.com/git-cola/git-cola/issues/991#issuecomment-549161703

```
> git-cola
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/fsmonitor.py", line 198, in run
    self._inotify_fd = inotify.init()
  File "/usr/share/git-cola/lib/cola/inotify.py", line 44, in _errcheck
    raise OSError(err, os.strerror(err))
OSError: [Errno 24] Too many open files
Aborted (core dumped)
```

Workaround: https://bugzilla.opensuse.org/show_bug.cgi?id=1155700#c1

**Comment by davvid** [comment]
I'm going to make it so that we detect when this happens and have it temporarily disable inotify support in cola.  Thanks for the heads up.

You can workaround this issue by doing `git config cola.inotify false` in larger repositories.  I'll make it more robust shortly nonetheless.

**Comment by akontsevich** [comment]
Got crash recently on a repo with detached head for example. Again on open.

**Comment by davvid** [comment]
Can you post a traceback from a git checkout from master?  If you clone it at `~/src/git-cola` then you can go into the repo where you saw the crash and run `~/src/git-cola/bin/git-cola` to make sure you're testing the latest.

I quickly tried a detached head here locally against the cola repo and it was behaving fine.  Is there an easy way for me to reproduce it?

**Comment by akontsevich** [comment]
> Is there an easy way for me to reproduce it?

I think You can with this repo: https://github.com/PX4/Firmware.git. Steps to reproduce:

- `git clone https://github.com/PX4/Firmware.git`
- `cd Firmware`
- `git checkout v1.9.2`
- Now open in git-cola -  crash for me

```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/fsmonitor.py", line 198, in run
    self._inotify_fd = inotify.init()
  File "/usr/share/git-cola/lib/cola/inotify.py", line 44, in _errcheck
    raise OSError(err, os.strerror(err))
OSError: [Errno 24] Too many opened files
```
Will test the latest now.

**Comment by akontsevich** [comment]
Latest from github seems works fine for me.

**Comment by davvid** [comment]
cheers, thanks for testing!
