### ISSUE TITLE
Add setting to disable automatic staging of new files

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#1017]
I am noticing a new "feature" where new files I add are automatically staged in git-cola.  I do not want this behavior to occur, I _only_ want a file to be staged when I explicitly tell git-cola to stage it, because quite frequently I do not want that file to be included in a particular commit.

Please add an option to Git-Cola's preferences to disable this behavior.

**Comment by davvid** [comment]
I don't quite understand.  If you create a new file Git doesn't know about it until you add it.  Adding the file is equivalent to staging the file.  Nothing has really changed in this area.  Can you elaborate a bit?

**Comment by ulgens** [comment]
I'm not sure git-cola has that ability. Maybe it's your IDE.

**Comment by davvid** [comment]
I'm going to assume that this is not being caused by cola, but please reopen if you discover otherwise.  Also, please leave a message here so that our future selves can find this thread for reference when you find out which tool is causing your woes.  Thanks for the heads-up @zauberparacelsus

**Comment by zauberparacelsus** [comment]
In this case, I am using the Zim desktop wiki, and use git to track changes.  When I create a new page in Zim, git-cola is automatically staging the file.  As well, if I rename a page in Zim, its file gets automatically staged as well.

Also, sorry for the late reply, I tend to tune out github emails because I get so many of them.

**Comment by zauberparacelsus** [comment]
I've figured out the problem.  Apparently at some point I had enabled a Version Control plugin for Zim, so that I could try it out.  But I didn't like how it worked and so forgot about it.  Apparently, one of the features it has is that it automatically stages new files as you create them.

Disabling the plugin has removed the problem.
