### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used

### ISSUE THREAD

**Issue by dniku** [git-cola/git-cola#1028]
I believe that the issue started after I upgraded by Arch (Manjaro) installation to Python 3.8.

Every time I launch `git cola`, the terminal fills up with the following messages:

```
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
```

System info:

```
$ git-cola --version
cola version 3.5

$ python --version
Python 3.8.0

$ uname -srv
Linux 4.19.88-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:04:44 UTC 2019
```

`git-cola` is installed from [AUR](https://aur.archlinux.org/packages/git-cola/).

**Comment by jman-88** [comment]
I get exactly the same on a similar setup.

```
$git cola --version
cola version 3.5

$ python --version        
Python 3.8.1

$ uname -srv                                                      
Linux 4.19.91-1-MANJARO #1 SMP Sat Dec 21 11:18:44 UTC 2019
```

Also installed from AUR.

**Comment by simeonackermann** [comment]
Still an issue in:

$ git cola --version
cola version 3.5

$ python --version        
Python 3.8.2

$ uname -srv    
Linux 5.5.16-1-MANJARO #1 SMP PREEMPT Wed Apr 8 10:07:00 UTC 2020

**Comment by simeonackermann** [comment]
But I dont get the error if I run git-cola directly from github source (version 3.6). May its already fixed here.

**Comment by simeonackermann** [comment]
Ok, I can confirm that the build 3.6 from AUR (https://aur.archlinux.org/packages/git-cola/) fixed the issue.

**Comment by jman-88** [comment]
> Ok, I can confirm that the build 3.6 from AUR (https://aur.archlinux.org/packages/git-cola/) fixed the issue.

I also confirm this with version 3.6.

**Comment by dniku** [comment]
Not an issue anymore for me either.
