### ISSUE TITLE
Fast change font size for diff

### ISSUE THREAD

**Issue by peso** [git-cola/git-cola#1029]
I'm a new user of git-cola. At launch I found the font in the diff pane too small for me to use.
My gut reaction was to use CTRL-mouse-scroll, which works in a browser like Chrome. I then found the fixed-width font under File -> Preferences -> Settings

Would it be possible to add a feature that allows quick change of diff font size?
I would prefer CTRL-mouse-scroll as it is used elsewhere for Zoom.

Git-cola version 3.6

**Comment by davvid** [comment]
Thanks for the sug. I've changed the default behavior so that we now allow mouse wheel zooming by default.

I had intentionally disabled the scroll wheel zoom behavior because it was easy to trigger. There's a config option to opt-out of it now instead.
