### ISSUE TITLE
Authentication textfield not in clear for user

### ISSUE THREAD

**Issue by mkentaro1** [git-cola/git-cola#1031]
Hi everybody, 

using git-cola I found a bit annoying that when signing in to a repository the email/user form contains  not clear text, but a password textfield.

It's a misconfiguration of my client? If yes, how can I fix?

I'm asking, since the user is shown in the form that follows the user declaration, asking for the password.

Thanks

**Comment by davvid** [comment]
Please test PR #1026 by running the latest in `master`.  I believe this is a dup so I'm closing the issue. @mboekhold does that sound about right?

**Comment by mboekhold** [comment]
Indeed pulling from master should fix your issue @mkentaro1
