### ISSUE TITLE
[UI suggestion] About Node graph.

### ISSUE THREAD

**Issue by 625781186** [git-cola/git-cola#1044]
I found another version control GUI.
It't also use pyqt5.
And It's Node graph use `QAbstractTableModel` and `QStyledItemDelegate`.

![image](https://user-images.githubusercontent.com/30521429/74110896-32be5480-4bcb-11ea-9946-dc162f82470b.png)

If you have time, you can improve, ha ha.~

https://bitbucket.org/tortoisehg/thg/src

**Comment by davvid** [comment]
It actually wouldn't be that hard ;-)

**Comment by aspiers** [comment]
This would be great. The big problem with the current DAG view is that you can't correlate each commit node in the DAG with the one-line commit summary on the left.

For me at least that unfortunately makes the DAG useless; currently I would find `git log --graph --pretty=oneline` more useful even though it is substantially less pretty.

Using horizontal alignment between graph nodes and rows in the commit list, as seen in the screenshot above and also in `git log --graph --pretty=oneline` and `gitk --all` would be way better.
