### ISSUE TITLE
Bad translation for "Pull" in French

### ISSUE THREAD

**Issue by Kronopost** [git-cola/git-cola#1046]
Hello,

There is written "Pousser" for either "Pull" and "Push" or it should be for "Push" only as "Pull" is "Tirer".
Also it leads to confusion when we want to push or pull as it is the same word written we don't know which one should be used.

**Comment by davvid** [comment]
Thanks for the report.

Should I change the translation for "Pull" to "Tirer", then?  That sounds like the solution.

To summarize:
- "Push" will stay as "Pousser"
- "Push will become "Tirer"

Is that an acceptable translation?

**Comment by Kronopost** [comment]
Yes that's it.
Thank you :)

**Comment by davvid** [comment]
Oh, I bet you're using an old version.  Please test master.

This was fixed back in 2018 -- b3c389568c1d2400826dd536c8828b25e874acf9

You can run git-cola straight from the source tree -- just run `make` and then `./bin/git-cola` -- you don't need to `make install` it anywhere.
