### ISSUE TITLE
wrong language

### ISSUE THREAD

**Issue by cropr** [git-cola/git-cola#1048]
When starting git cola on Ubuntu the gui starts with a French interface, while none of my locale settings is set to French 

The ouput of the locale cmd is
```
LANG=en_BE.UTF-8
LANGUAGE=en_GB:nl
LC_CTYPE="nl_BE.UTF-8"
LC_NUMERIC="nl_BE.UTF-8"
LC_TIME="nl_BE.UTF-8"
LC_COLLATE="nl_BE.UTF-8"
LC_MONETARY="nl_BE.UTF-8"
LC_MESSAGES="nl_BE.UTF-8"
LC_PAPER="nl_BE.UTF-8"
LC_NAME="nl_BE.UTF-8"
LC_ADDRESS="nl_BE.UTF-8"
LC_TELEPHONE="nl_BE.UTF-8"
LC_MEASUREMENT="nl_BE.UTF-8"
LC_IDENTIFICATION="nl_BE.UTF-8"
LC_ALL=nl_BE.UTF-8
```
I did not alter the standard settings file. 
```
{
    "bookmarks": [],
    "gui_state": {
        "startupdialog": {
            "geometry": "AdnQywADAAAAAAJ8AAABGgAAB4MAAAWfAAACgAAAATcAAAd/AAAFmwAAAAEAAAAACgAAAAKAAAABNwAAB38AAAWb",
            "width": 1280,
            "height": 1125,
            "x": 636,
            "y": 282
        },
        "preferencesview": {
            "geometry": "AdnQywADAAAAAAUMAAABmgAAB2sAAAPOAAAFEAAAAbcAAAdnAAADygAAAAEAAAAACgAAAAUQAAABtwAAB2cAAAPK",
            "width": 600,
            "height": 532,
            "x": 1292,
            "y": 410
        }
    },
    "recent": [],
    "copy_formats": []
}
```

**Comment by davvid** [comment]
We use gettext (See `cola/i18n.py` for details) and what you're describing shouldn't happen, but maybe gettext is falling back to the `fr` translations for some reason.  Could it be that gettext is using French when it gets asked for Belgian?

While we haven't gotten any reports of other users running into this, we do have an existing feature that you can use to workaround the issue.  I wonder if the locales are symlinked or something on your system?  Something is basically making gettext think that it should load the `fr` language files.  You can do this to force cola to use a specific language, irrespective of the environment:

        mkdir -p ~/.config/git-cola
        echo en_US.UTF-8 > ~/.config/git-cola/language
