### ISSUE TITLE
cannot clone from https

### ISSUE THREAD

**Issue by RealTehreal** [git-cola/git-cola#1049]
Hi there,

I'm trying to clone a private repository from Bitbucket via https. This is what I get in response:

`Cloning into '/mnt/filespace/assets'...
extra characters after close-brace
    while executing
"if {"Password" in $prompt}{"
    invoked from within
"if {!$yesno} {
	if {"Password" in $prompt}{
		.e configure -show "*"
	}
}"
    (file "/home/realtehreal/Downloads/git/git-cola/share/git-cola/bin/ssh-askpass" line 29)
error: unable to read askpass response from '/home/realtehreal/Downloads/git/git-cola/share/git-cola/bin/ssh-askpass'
fatal: could not read Password for 'https://RealTehreal@bitbucket.org': No such device or address
`

As mentioned here #469 I tried to install wish, which redirected to tk which was already installed. Now I'm stuck. Any help is very appreciated.

Edit: Ah yeah, I'm on Pop!OS 19.10 and I'm using git-cola 3.6
Edit2: Now I've installed git-cola from my distributions repository (which is the same as Ubuntu's) and with this version I can clone repositories because a password prompt appears. Now I wonder why it won't work with the latest version from this repository.

**Comment by davvid** [comment]
@mboekhold this was an interesting one.  It doesn't trigger the error on macos, but on debian/testing (I can repro it there) and on ubuntu (where we likely have newer tk versions) it now flags a tiny syntax errors.  This is a good one.

```
diff --git a/share/git-cola/bin/ssh-askpass b/share/git-cola/bin/ssh-askpass
index 102465ec..56a4c8ce 100755
--- a/share/git-cola/bin/ssh-askpass
+++ b/share/git-cola/bin/ssh-askpass
@@ -27,7 +27,7 @@ entry .e -textvariable answer -width 50
 pack .e -side top -fill x -padx 10 -pady 10

 if {!$yesno} {
-       if {"Password" in $prompt}{
+       if {"Password" in $prompt} {
                .e configure -show "*"
        }
 }
```

Thanks for the heads-up @RealTehreal .  I'll commit a fix shortly.
