### ISSUE TITLE
Add CFBundleVersion and CFBundleShortVersionString to info.plist

### ISSUE THREAD

**Issue by Feuermurmel** [git-cola/git-cola#1054]
It seems that when following the [build instructions on macOS](https://github.com/git-cola/git-cola#mac-os-x), the version fields of the application bundle are set to `0.0.0`. It would probably be nice to set those fields to sensible values.

Basically, `CFBundleShortVersionString` should be set to the "public" version number the end-user should care about. This is displayed in the "Get Info" dialog in Finder. `CFBundleVersion` can be set to whatever, e.g. include a build number or a commit ID.

Full reference: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349

**Comment by davvid** [comment]
Thanks for the heads-up! We now generate the CFBundleVersion / CFBundleShortVersionString values at build-time.
