### ISSUE TITLE
Branch context menu: pull

### ISSUE THREAD

**Issue by PF4Public** [git-cola/git-cola#1055]
Using main window menu one could change pull behaviour (ff-only, rebase, etc).

But using branch context menu, git-cola always creates merge commit. Is it by design?

Could this context menu respect settings set in pull dialog, accessible from main menu?

**Comment by craigwardman** [comment]
not sure if it's related or a separate bug (or by design) -- but the target branch for the "pull" always seems to be the current branch rather than the one that was right clicked.
