### ISSUE TITLE
Cola on ARM: there's no issue!

### ISSUE THREAD

**Issue by rhaleblian** [git-cola/git-cola#1059]
![snap](https://user-images.githubusercontent.com/94912/82156710-e7ab8180-984a-11ea-9596-a6c316b7576a.png)

Just what i need on a teeny ARM SoC.

**Comment by rhaleblian** [comment]
Not fixing!

**Comment by davvid** [comment]
Thanks Ray, that's awesome.  If PyQt is supported, I'm down to support it ;-)
