### ISSUE TITLE
Cherry pick fail message

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#1062]
Will it be possible to show a message, if there are merge problems with a cherry pick on the visualize screen. If the Cherry pick has no problems it doesn't need to show a message.

The problem is I sometimes have to cherry pick a couple of commits in sequence. So now I am forced to follow the following procedure.
1. Right click on Visualize commit and choose Cherry pick.
2. Open main git-cola screen refresh and look if there is merge conflicts.
3. Go back to visualize screen Cherry pick next commit.
4. Go back to main git-cola screen refresh to see if there is merge conflicts.
etc.

Thanks in advance

**Comment by davvid** [comment]
Thanks for the report. This has been improved and will be part of the upcoming v4.2.0 release.

**Comment by NielBuys** [comment]
Thanks for this. I wanted to test but version 4.2.0 do not work on my Ubuntu 20.04. I created a issue for this. https://github.com/git-cola/git-cola/issues/1286

**Comment by NielBuys** [comment]
Thanks for this change. I tested I get a message now when there is merge conflict with an Cherry pick.
