### ISSUE TITLE
DAG: Graph not updating after push

### ISSUE THREAD

**Issue by fweber144** [git-cola/git-cola#1063]
After pushing (while having the DAG window opened), the graph in the DAG window does not update, neither automatically nor after pressing `Ctrl+R` (for refreshing). It only updates after closing and re-opening the DAG window.

**git-cola version:**
3.6

**System info:**
Ubuntu 20.04 LTS
64 bit

**Comment by maxtat3** [comment]
+1

git-cola version: 3.9
Ubuntu 16.04 LTS

**Comment by davvid** [comment]
Thanks for the heads-up!

**Comment by fweber144** [comment]
No problem. Thanks for fixing this :)
