### ISSUE TITLE
Please implement 'git revert'

### ISSUE THREAD

**Issue by bartasha** [git-cola/git-cola#1068]
Recently I needed to move an old, already pushed commit from one branch to another, as it was deemed to be unrelated work during a code review.  I did this by cherry-picking the commit from the source branch to the target branch; however, I could not find a way to revert the commit in the source branch via the GUI - I had to use 'git revert <SHA>' from the command line.

It would be useful to have a 'Revert this commit' option in the DAG, or a 'Revert a commit...' option in the 'Actions' menu, or preferably both.  Looking at the output of 'git help revert' suggests this might not be straightforward for merges, but for regular commits it should be similar to the 'Cherry-Pick...' option in complexity.  I'd give it a go if I had the time...

Note that a 'git reset' would not do here, as I need to keep all commits that are newer than the one I wish to revert.  Similarly, a 'git rebase' isn't an option either, as that would not play well with existing reviews or our CI infrastructure.

**Comment by TamaMcGlinn** [comment]
Which version are you using? In the latest release, 3.7, I opened the DAG and right clicked a commit; revert is there and works as expected.

**Comment by bartasha** [comment]
I was using 3.0.  I didn't realise the version had moved on so much - Ubuntu 18.04 lists 3.0 as the latest...  Thanks for looking - I've uninstalled Ubuntu's version and have installed from the 3.7 tar.gz.
