### ISSUE TITLE
 spelling control in the "commit summary".

### ISSUE THREAD

**Issue by peter-jensen** [git-cola/git-cola#1070]
I am using ppa for ubuntu 18.04.

Please add spelling control in the "commit summary".

![spelling](https://user-images.githubusercontent.com/28685010/84299110-1bc34b00-ab48-11ea-9668-60eb958b2768.png)

**Comment by davvid** [comment]
Thanks for the sug!

It took a while, but this is now possible. We followed the same general idea as described in http://blog.ssokolow.com/archives/2022/07/22/a-qlineedit-replacement-with-spell-checking/
