### ISSUE TITLE
Changing language with ~/.config/git-cola/language stops git-cola app from opening

### ISSUE THREAD

**Issue by LKirst** [git-cola/git-cola#1071]
I'm on Win10 and installed the v3.7 git-cola release. I tried to change the language to `en` with:
`$ echo en_US.UTF-8 > ~/.config/git-cola/language`
On this machine (it worked on a different machine, also with Win10 and v3.7), when I create the `language` file, git-cola doesn't start (the GUI simply doesn't open up). As soon as I delete the `language` file, I can start git-cola.

For now, my workaround is to delete the German translations in the installation folder `"~\AppData\Local\git-cola\share\locale\de\LC_MESSAGES\git-cola.mo"`. git-cola then reverts to the default language English.

Is there a better way of keeping git-cola from translating to German?
What can I do to figure out what's the issue with the language file? I know the issue is probably connected to the [_install_custom_language()](https://github.com/git-cola/git-cola/blob/51dd49dc2a5022481f310049d8b53822feecb731/cola/i18n.py#L65) function in `cola/i18n.py`, but I'm unsure how to troubleshoot it.

**Comment by davvid** [comment]
Interesting.  Hmm, are you able to get Python3 in a virtualenv with PyQt5 installed?  If so, the way to debug it would be to run `python ./bin/git-cola` from the source tree and it should print a traceback with some clues.

I'm super curious why it's happening.  The `echo` command should produce a regular file so it's odd.

For debugging, as an alternative to the `language` file, does it work if you munge the environment?   ex: `env LANG=en_US.UTF-8 python ./bin/git-cola`

**Comment by LKirst** [comment]
Thanks for your answer. I tried to follow your instructions (with the exception that I used a conda env, but that shouldn't make a difference). 

These are the files in the ./bin/git-cola folder:
git-cola-append.zip
git-cola.exe
git-dag-append.zip
git-dag.exe
launcher_exe.dat

The command `python ./bin/git-cola` results in the error `python: can't open file '.\bin\git-cola': [Errno 2] No such file or directory`

**Comment by prof7bit** [comment]
This might be related to https://github.com/git-cola/git-cola/issues/382 which suggests that it is loading an entirely different configuration when a different language is selected. This is 7 years old and still open.

**Comment by prof7bit** [comment]
Possibly related:
uncommenting line 79 (`compat.setenv('LANGUAGE', locale)`) will make it stop messing up the panel layout. It will unfortunately also stop it from switching the language since none of the LANG, LC_ALL, LC_MESSAGES seem to have any influence on anything at all.

**is it possible that the translators accidentally translated strings that should be property names in the settings file and should be hardcoded?**
