### ISSUE TITLE
File system change monitoring not working under windows when executing bin/git-cola.exe

### ISSUE THREAD

**Issue by ThiemoVanEngelen** [git-cola/git-cola#1072]
This is caused by a problem in pynsist (see [pynsist issue 199](https://github.com/takluyver/pynsist/issues/199) ), which sets bin/ as installdir in the preamble, and because of that adds bin/pkgs/ to the site dir and the sys.paths.

This could be solved in the extra-preamble script, specifically for commands.

**Comment by davvid** [comment]
This was fixed upstream in pynsist. Thanks for the report.
