### ISSUE TITLE
Honor themes for window borders/buttons on Linux (dark mode)

### ISSUE THREAD

**Issue by liquidscorpio** [git-cola/git-cola#1082]
On Linux Mint (Cinnamon), I am running the packaged dark theme (Mint-Y-Dark) for windows, borders, icons etc.
Yet, git-cola only has a dark title bar. Everything else uses a light theme.

I could not get it to working using qt5 style packages either ([example](https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html)).

**Related MacOS issue**
https://github.com/git-cola/git-cola/issues/905

**Comment by davvid** [comment]
What version are you running?  There's theme settings in the preferences.

This is possible.  I use a dark theme myself with the qt5ct setup.  For the icon theme, you may need to do `git config --global cola.icontheme dark`

Please read these links and let me know what you think:

https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-theme

https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-icontheme

**Comment by davvid** [comment]
Please try this out.  You may need to install a separate package to get the qt5ct Qt theme:

```
# Use the style configured using the qt5ct tool
QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORMTHEME
```

Once I hear back, I'm going to leave this issue open so that we can split out a section in the documentation about styling and link to these two configuration knobs.

**Comment by liquidscorpio** [comment]
Thanks! Your suggestions worked. :tada: 

Had install qt5ct
```
sudo apt-get install -y qt5ct
```

And the command (shared by you earlier) fixed the icons:
```
git config --global cola.icontheme dark
```

Amazing software and support you provide.
