### ISSUE TITLE
"Stage selected lines" for untracked files

### ISSUE THREAD

**Issue by mighty-d** [git-cola/git-cola#1084]
Would it be possible to enable staging selected lines from an untracked file?
Currently an untracked file needs to be staged in its entirety and then unwanted lines must be unstaged.

**Comment by living180** [comment]
We could probably add a "Begin tracking" context menu item for untracked files, which would invoke `git add --intent-to-track` on the selected file to add it to the index but without staging any of its contents.  Then selected lines could be staged as usual.

**Comment by davvid** [comment]
Yup, exactly that -- after the initial `git add --intent-to-add` staging will "just work".  A "Begin tracking" context menu makes a lot of sense.

This is basically the same request as #493 and would resolve that issue as well.

**Comment by mighty-d** [comment]
Not sure what the general direction of the project is here, but is it necessary to have one action per git command?
Begin tracking implies a need for "end tracking".

This is how it works in gitextensions, the software I used before:
changed and untracked are all together, they just have with a different icon (green + for untracked and pencil for edited, if I recall)

user: select a file
user: select some wanted lines
user: stage lines (S)
system: track if untracked
system: stage lines


From the staging area (which is in a different gui widget, so ctrl+a it's actually useful):
user: select a file
user: select some unwanted lines
user: unstage lines (U)
system: unstage lines
system: untrack if untracked and file is empty

Also revert (R) works the same and if the file is untracked lines get deleted instead of going to the previous version.
I find that workflow quite handy for precision commit crafting.

**Comment by davvid** [comment]
👍 thank you, that's a great idea.  Indeed, it would be nice if we could make this seamless for users.

On Unix we can "fake" a full diff by leveraging `/dev/null` when diffing:
```
git diff --no-index /dev/null <untracked-file>
```
We could build upon that to create a diff-centric untracked file interface that takes care of doing `git add --intent-to-add <untracked-file>` under the hood automatically when doing partial staging for an untracked file.

Is there's an equivalent to `/dev/null` on Windows?  I guess we can always disable this feature on Windows, but it would be nice if there were a simple approach that worked cross-platform.

I'll have to dust off my old Windows VM and see if Git for Windows supports using `/dev/null` like that -- it might, which would be really cool.
