### ISSUE TITLE
Unable to open Spyder through Ubuntu

### ISSUE THREAD

**Issue by w142236** [git-cola/git-cola#1093]
I installed Spyder into a virtualenv on Ubuntu using:

`sudo pip3 install spyder` (which you are apparently never supposed to use sudo pip together ever)

and every time I tried opening it, I get the following errors:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-quit'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

I have read that the libGL error is often associated with an Nvidia graphics card, but I ran the following [which I found from here which discusses this issue](https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t), but I did not find the "mesa" file which is associated with the Nvidia driver, so I'm assuming that this is not even though I do have Nvidia:

`sudo ldconfig -p | grep -i gl.so`
which outputs:

        libwayland-egl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libwayland-egl.so.1
        libcogl.so.20 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcogl.so.20
        libQt5OpenGL.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libQt5OpenGL.so.5
        libGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGL.so.1
        libEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1

Maybe one of these libs is problematic or there is some other issue?

**Comment by davvid** [comment]
This is not the spyder repository.

**Comment by davvid** [comment]
Check out this link for techniques that you can use to get the system-managed files back to a pristine state:

https://blog.sleeplessbeastie.eu/2015/03/02/how-to-verify-installed-packages/

If you don't have the ubuntu-provided nvidia drivers installed, that may be an important next step to look into.  The `glxgears` program is usually a quick way to verify whether opengl is working.
