### ISSUE TITLE
3.8 is tagged but not labeled as release

### ISSUE THREAD

**Issue by harmathy** [git-cola/git-cola#1099]
There is a v3.8 version tag but it is not labeled as release. The [download page](https://git-cola.github.io/downloads.html) and the [documentation](https://git-cola.readthedocs.io/en/latest/relnotes.html#latest-release) refer to 3.7 as the latest release. From recent commits I can derive that 3.9 is the upcoming release and infer that 3.8 is supposed to be a regular release. This is very confusing.

**Comment by davvid** [comment]
I forgot to commit the 3.8 updates to the website repo, and had to update the readthedocs configuration for the new branch names.  Thanks for the heads-up.
