### ISSUE TITLE
Cannot download 3.8 Windows release

### ISSUE THREAD

**Issue by Andre-LA** [git-cola/git-cola#1100]
On the [download page](https://git-cola.github.io/downloads.html), the Windows Download button leads to this URL:
https://github.com/git-cola/git-cola/releases/download/v3.8/git-cola-3.8.windows.zip

However, this file doesn't exists

**Comment by Andre-LA** [comment]
Just noticed the release update with Windows build, thanks :) 👍

**Comment by davvid** [comment]
Thanks for the heads-up!
