### ISSUE TITLE
[Question] How to run --amend -s

### ISSUE THREAD

**Issue by mbnoimi** [git-cola/git-cola#1104]
How can I execute `git commit --amend -s -m 'my message'` in Git-cola UI ?

**Comment by davvid** [comment]
The commit message editor's sprocket settings menu has an "Amend" checkbox, as well as a "Sign-off" action.

I like keyboard hotkeys.  The Help menu can show all the shortcuts.

If the commit message editor has focus you can use `Ctrl-m` to enter/exit Amend mode (mnemonic eM -> aMend)   and `Ctrl-i` (mnemonic "i" rhymes with "sign") to add your sign-off to the message.
