### ISSUE TITLE
Staged diffs aren't displayed in a repository without commits

### ISSUE THREAD

**Issue by kyanres** [git-cola/git-cola#1110]
Hello!

**To reproduce :**
```
mkdir test && cd test
git init
echo -e "a\nb" > foo
git cola
```
Then use git cola to stage the file.

**Observed behavior :**
When foo is Untracked, the Diff view shows its contents.
When foo is Staged, the Diff view is empty.

**Expected behavior :**
I need to see what's staged before committing  :-) + to be able to unstage some lines.

Hope that helps.
I got around that problem by doing a first commit for .gitignore and squashing it later with rebase -i --root

git version 2.25.1
cola version 3.6

**Comment by nyanpasu64** [comment]
Still an issue on commit f4cdf65dcb950a761d0ff79149ad89caee32ab2a.

This occurs in all repositories with no HEAD (both newly `git init` repos, and `git checkout --orphan $branch_name`).

**Comment by nyanpasu64** [comment]
Using the git-cola-git AUR package, pointing to main 74e94ae1fc4299d36adbb1cc456df9a674fa72b3. Now showing a file diff works, but staged images don't show anything. And if I stage an image, quit and reopen Git Cola, and scroll on the image, the app crashes:

```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/imageview.py", line 330, in wheelEvent
    self.zoomROITo(scene_pos, sign)
  File "/usr/share/git-cola/lib/cola/widgets/imageview.py", line 214, in zoomROITo
    roi_dims = QtCore.QPointF(roi.width(), roi.height())
AttributeError: 'NoneType' object has no attribute 'width'
fish: Job 1, 'cola' terminated by signal SIGABRT (Abort)
```

**Comment by davvid** [comment]
Thanks for the heads-up @nyanpasu64  -- I just pushed b63bc427413b51622fe3088b2423119d4f65db44 which should guard against the scenario you ran into. Interesting I couldn't reproduce it, but I added some extra guard checks.

BTW, I noticed the traceback above says `/usr/share/...` but if you're running from the source tree it should have a path that points into your git clone. You can verify this in the `Help -> About` dialog by checking the listed version.

Nonetheless, this should be better behaved going forward. Cheers

**Comment by nyanpasu64** [comment]
I'm using the `git-cola-git` AUR package, pointing to the newly pushed b63bc427413b51622fe3088b2423119d4f65db44:

> Git Cola version 3.10.1 (v3.10-39-gb63bc427) 
> Linux-5.13.7-zen1-1-zen-x86_64-with-glibc2.33 
> Python (/usr/bin/python) 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0] 
> Git 2.32.0 
> Qt 5.15.2 
> QtPy 1.9.0 
> PyQt5 5.15.4 

When I put this file in an empty folder, then run `git init`, I get a preview before staging but not after staging (no console messages though). At least I no longer get a crash...

[Warning sign.zip](https://github.com/git-cola/git-cola/files/6935822/Warning.sign.zip)

![Screenshot_20210804_210306_cola-test: master _home_nyanpasu64_code_cola-test](https://user-images.githubusercontent.com/913957/128288995-02192410-d96b-47cd-b2d0-64d065e07ffe.png)
![Screenshot_20210804_210308_cola-test: master _home_nyanpasu64_code_cola-test](https://user-images.githubusercontent.com/913957/128289003-33f8cb31-3af6-443e-918b-fd2c9baf221b.png)
