### ISSUE TITLE
Access token support?

### ISSUE THREAD

**Issue by Botspot** [git-cola/git-cola#1112]
I use git cola on a daily basis, and recently I've been receiving many emails similar to this one:

> Hi @Botspot,
> 
> You recently used a password to access the repository at Botspot/pi-apps with git using git/2.20.1.
> 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-au ... perations/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

Using git cola, how to fix this issue?

**Comment by davvid** [comment]
This is more of a git issue.  You can verify by doing `git fetch` and `git pull` from the command-line and you'll likely see these same notifications.

Here are the things to do:

1. Use ssh-based authentication.  https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
2. Make sure your github account has your ssh key associated with it
3. Edit `.git/config` or use the `File -> Edit Remotes...` dialog to change the origin url to github's SSH url, eg. `git@github.com:Botspot/pi-apps.git`

**Comment by Botspot** [comment]
> This is more of a git issue. You can verify by doing `git fetch` and `git pull` from the command-line and you'll likely see these same notifications.

Running `git pull` and `git fetch` never trigger such an email. I should have explained better.

Whenever I've received one of these emails, it's right after pushing commits to a public github repository with git cola. Does that new information change anything in your answer?

**Comment by davvid** [comment]
This is the same issue.  It's when you `git push` that it's asking for your password.  Use SSH authentication.

**Comment by Mastomaki** [comment]
How do I enable SSH authentication in Git Cola (Windows 10)? I can use SSH authentication in Git command line.

**Comment by Mastomaki** [comment]
Thanks. It seems that starting the SSH agent in Git Bash was not enough. I had to start the OpenSSH agent in Windows Services. And then add the SSH key using Powershell, as explained in [How to run ssh-add on windows](https://stackoverflow.com/questions/18683092/how-to-run-ssh-add-on-windows).
