### ISSUE TITLE
Feature request: Checkout branches and initiate rebases from `git dag` view

### ISSUE THREAD

**Issue by nyanpasu64** [git-cola/git-cola#1113]
Right now, if I want to switch branches or initiate rebases, I need to open a `git dag --all` window to find my way around the commit graph, then either write down a branch name or (in case of rebases) copy a SHA1 from the graph, then open a `git cola` window to perform the action.

Is it possible to add this functionality into the right-click menu of `git dag`?

(Some Git GUIs like Git Extensions are centered around a commit graph, holding the majority of functionality there, and only exposing index-manipulating tools and `git commit` from the commit window. Git Cola is reversed, and I feel it's not necessarily the best approach.)

**Comment by davvid** [comment]
This is now available in the latest from git. Please test this if you can before v4.2.0 is released. Thanks again for the sug!

**Comment by nyanpasu64** [comment]
Interesting, checking out branches and creating tags, etc. is triggered on the selected commit, which is not updated when you right-click a different commit or the background of the graph view. Is this intentional? (I know you can identify the *right-clicked* commit separately from the selected one, since that commit is used for "diff this -> selected" etc. menu items.)

I've actually stopped using `git dag` for the most part (I now use git cola as a commit editor, and VS Code Git Graph and CLI rebase for history manipulation), because the commit list is linear but the graph is not, labels can cover lines (or even nodes?), and graph lines can sometimes overlap despite coming from unrelated branches:

![Screenshot_20230225_224744](https://user-images.githubusercontent.com/913957/221396436-7b3988d1-e5ec-458e-932b-5c59d85aa172.png)

On the topic of using Cola as a commit editor, could you add an "edit hunk patch in editor" button like `git add -p`? Or would that be a separate bug report?

**Comment by davvid** [comment]
Cola supports editing of patch hunks as of #1290.

The "Edit Diff Hunk to Stage..." and similar "Edit Diff Hunk ..." context menu actions let you edit the hunk in your editor before it gets applied to the staging area or worktree.

That's a really good point about the selected commit vs. the clicked commit. I think your comment strongly suggests that it'd be more intuitive for it to offer the branches from the clicked commit and then only consider the selected commit if the clicked commit doesn't have any associated branches.

I'm going to change it so that it prefers the clicked commit.

**Comment by davvid** [comment]
Down the line I'd like to change the DAG so that the graph shape better reflects the first-parent history and to fixup the shortcomings you've highlighted about the overlapping labels and lines.

**Comment by davvid** [comment]
I improved the selected vs. clicked commit behavior, so now it follows what you've right-clicked rather than the selected item (even though they are often the same).
