### ISSUE TITLE
DAG does not launch on Kubuntu 20.04

### ISSUE THREAD

**Issue by safield** [git-cola/git-cola#1114]
Git Cola version 3.6 
Linux-5.8.0-43-generic-x86_64-with-glibc2.29 
Python (/usr/bin/python3) 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] 
Git 2.25.1 
Qt 5.12.8 
QtPy 1.9.0 
PyQt5 5.14.1 

Just install on Kubuntu 20.04 from the official repository.

When I open a repo in the app and then select "view > DAG", nothing happens. If I try to launch the DAG from the application launcher, it also fails silently.

**Comment by davvid** [comment]
Sorry for not responding earlier.  Please let me know if your figured out the solution.  I'm curious to know what you did so that we can help others who might run into the same issue on Kubuntu 20.04 in the future.

(hopefully it was just a packaging issue that ubuntu/debian has resolved)

Thank you!

**Comment by paidhi** [comment]
I would be very interested in a solution. Having the same problem on Fedora 35.

My system:
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.11.12-300.fc34.x86_64 (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 31,1 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by penguin86** [comment]
It seems to be happening to me as well. I'm using the current AUR on Arch, build went smoothly with no errors. No message logged in console when trying to open DAG, it simply does not open.
The DAG executable (git-dag), btw, is running:
```
[danieleverducci@Matissepenguin ~]$ ps aux | grep dag
daniele+   25131  0.6  0.5 819660 183980 pts/1   Sl+  08:22   0:00 /usr/bin/python /usr/bin/git-dag
daniele+   25172  0.0  0.0   3308  1712 pts/4    S+   08:22   0:00 grep dag
```
In fact, if I try to launch `git-dag` from command line, nothing happens, but the prompt isn't returned, something runs without creating a window. As before, nothing is logged to command line.

*My config*
Linux Matissepenguin 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
AUR: https://aur.archlinux.org/packages/git-cola v4.1.0 (commit f1f27c3dd5ed949aefdb69a295131b7688551ebb)

Let me know if I can help!
