### ISSUE TITLE
Git Cola doesn't look in `core.hooksPath` for `cola-prepare-commit-msg`

### ISSUE THREAD

**Issue by parkercoates** [git-cola/git-cola#1118]
Since version 2.9, Git has supported a [`core.hooksPath`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corehooksPath) configuration variable to specify where hooks can be found. Git Cola doesn't seem to respect this when looking for its `cola-prepare-commit-msg` hook.

**Comment by davvid** [comment]
Thanks for the heads-up.  Git Cola now honors `core.hookspath`.  Please test the latest from git.  The upcoming `v3.10` will be the first release with this feature.

**Comment by parkercoates** [comment]
Thank you for the quick fix!
