### ISSUE TITLE
Feature: Auto-Wrap text for Diff viewer

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#1120]
In the Diff panel in the main view, Visualize Current Branch, and other places, it would be nice to have a setting you can toggle to auto-wrap the lines.  Among other things, I've been using Git to manage changes for the text files in a git notebook, and so more often than not a single line of text will be an entire paragraph, and so I need to scroll off to the right in order to see the part of a line that is different.

**Comment by davvid** [comment]
<img width="847" alt="Screen Shot 2021-03-15 at 2 46 48 AM" src="https://user-images.githubusercontent.com/13196/111134318-bbc75e00-8538-11eb-838d-641db06c858d.png">

This screenshot shows the two lines that enable word wrapping and a long line showing it in action. Qt makes this feature pretty easy.

We can make the auto-wrapping enabled by default and add a toggle to disable it similar to the other options in the diff tool's menu.

**Comment by ramonbrugman** [comment]
.

**Comment by abid1998** [comment]
@davvid I can start working on this, can you just tell me which file holds the layout where i can add the button ?

**Comment by abid1998** [comment]
Or i can add a checkbox in diff options ?

**Comment by abid1998** [comment]
@davvid I can take up this issue. I have already added the checkbox in options. Due to me being a noob in Qt I am unable to understand how should i add emit event when it is checked in this codebase if you can help out here it would be great.

**Comment by abid1998** [comment]
![image](https://user-images.githubusercontent.com/29145667/111367841-2902fc80-86bb-11eb-834c-a76a3665cf6a.png)

**Comment by abid1998** [comment]
Also what all changes did you make to enable word wrap?

**Comment by davvid** [comment]
Sweet.  Yeah, adding it to the diff options would be great.

We can save and restore the setting using the `export_state()` / `apply_state()` functionality in there, which is currently used for storing the "Show lines numbers" and other settings.

You'll see where that's handled in `cola/widgets/diff.py` (look for `export_state` and trace the variables from there).

The DiffEditor class is where I had to add the word wrap calls, so exposing a function to enable/disable wrapping using those calls *should* do the trick. It's interesting that they didn't seem to work for you -- the way it works is that it wraps to the width of the widget, so if your text isn't long enough you can try making the window skinnier just in case.

What Qt version are you using?  Qt and PyQt 5.15.x over when I tested (The "Help -> About" page has a "Versions" tab that lists the details).

**Comment by abid1998** [comment]
Haha got it working i was using a single word filled with random characters so it was not wrapping it.

**Comment by abid1998** [comment]
Creating a work in progress PR got the basic functionality working. My screenshot tool on ubuntu is not able to take screenshot of the diff options lol.

**Comment by abid1998** [comment]
https://github.com/git-cola/git-cola/pull/1123 @davvid Created a PR

**Comment by abid1998** [comment]
![WordWrap](https://user-images.githubusercontent.com/29145667/111433903-e37b1980-8724-11eb-9db7-46c62456f464.gif)
Enable Word Wrap is enabled on start of git-cola.

**Comment by abid1998** [comment]
@davvid we should close this issue right?

**Comment by davvid** [comment]
Resolved-by: #1123
