### ISSUE TITLE
Interface icons missing on Manjaro linux

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#1124]
I'm not sure when this issue started, but I've noticed that the icons in git-cola's interface have gone missing.  For example, the green check and red X icons in the status pane for individual files are missing.

I ran git-cola from command line and saw a warning about the breeze icon themes missing, so I installed those via Manjaro's package manager, but the problem has not corrected itself.  I also rebooted in case that was needed for the icon changes to fully go through, but git-cola's icons are still missing.

**Comment by algent-al** [comment]
I can confirm this in Solus too. This happened after updating the kde framework to 5.80.0.

**Comment by zauberparacelsus** [comment]
Just checked my kde framework version, and it is version 5.80.0 as well.

**Comment by algent-al** [comment]
Was just fixed on Solus with this [patch](https://invent.kde.org/frameworks/kiconthemes/-/merge_requests/26.patch)

**Comment by zauberparacelsus** [comment]
Manjaro just pushed out an update for the kiconthemes package, which fixes the issue.

**Comment by suside** [comment]
I have the same issue on Ubuntu 21.04 + git-cola 3.9-1 + kded5 5.80.0-0ubuntu1
No warnings in command line though.

**Comment by gyuris** [comment]
Same issue: Ubuntu 21.04 (git-cola 3.9-1)

**Comment by richarson** [comment]
Folks, it's a bug in KDE Frameworks 5.80, not in git cola.

Please ask your distros to update to Frameworks 5.81 or backport the patch from https://invent.kde.org/frameworks/kiconthemes/-/merge_requests/26

**Comment by suside** [comment]
Thanks for the clarification richarson :+1: 
While we wait for distro update here is a workaround on the git cola side:

```diff
diff --git a/cola/icons.py b/cola/icons.py
index 8b4de9e1..755282a2 100644
--- a/cola/icons.py
+++ b/cola/icons.py
@@ -67,7 +67,8 @@ def name_from_basename(basename):
 
 def from_name(name):
     """Return a QIcon from an absolute filename or "icons:basename.svg" name"""
-    return QtGui.QIcon(name)
+    file = resources.share('icons') + '/' + name.replace('icons:', '')
+    return QtGui.QIcon(file)
 
 
 def icon(basename):

**Comment by michalfapso** [comment]
Thanks for the patch, @suside, worked for me on Ubuntu 21.04 with git-cola 3.9-1.
