### ISSUE TITLE
bash completion doesn't work

### ISSUE THREAD

**Issue by pffang** [git-cola/git-cola#1133]
bash completion doesn't work, some arguments wasn't supported.

error info:
git cola --help-commands
usage: git-cola [-h]
                {cola,about,am,archive,branch,browse,clone,config,dag,diff,fetch,find,grep,merge,pull,push,rebase,recent,remote,search,stash,tag,version}
                ...
git-cola: error: unrecognized arguments: --help-commands

**Comment by davvid** [comment]
Thanks for the heads-up!
