### ISSUE TITLE
Linux freezes when running git cola

### ISSUE THREAD

**Issue by KammutierSpule** [git-cola/git-cola#1134]
I'm experience a linux freeze after start git/cola.

I tried latest version of the linux distro repository and also this source code repository

I got his message on the console

QWidget::setMinimumSize: (/MainView) The largest allowed size is (16777215,16777215)

then I have to kill the application

**Comment by KammutierSpule** [comment]
I tried on different WM environments and got the same problem

**Comment by KammutierSpule** [comment]
I found that if I run cola dag, I got the same problem, but after I manage to maximize/unmaximize the window and gracefully close it, I can run it again with no problems.

on git-cola I found that if I manage to remove all the views, it will not freeze but as soon as I start to add views, it will freeze.

**Comment by KammutierSpule** [comment]
I found an workarround, running QT5 settings:
$qt5ct
and change Style from gtk2 to other option will make it work

**Comment by ulgens** [comment]
Which distro is that? Which version? I'm not sure i understand what does "latest version of the linux distro repository" or "different WM environments" means.

**Comment by KammutierSpule** [comment]
Sorry for the confusion, here are the version details:

Linux version: Linux Mint 20.1
Window Manager tested: Cinnamon, Mate, XFCE
git-cola Linux Mint distro repository version: 3.6-1
git-cola source code repository version: current main branch

**Comment by davvid** [comment]
Using `qt5ct` is probably the right solution, especially if you have a long-living $HOME directory where your user settings may have migrated from older gtk2 days to newer gtk3 mint/xfce versions.

It's might be the same steps as getting Qt to follow your window manager theme.

https://git-cola.readthedocs.io/en/latest/git-cola.html#dark-mode-and-window-manager-themes

Does  `echo $QT_QPA_PLATFORMTHEME`  report anything in your environment?

If it says `qt5ct` then you're already setup correctly and you may need to run `qt5ct` and adjust settings as you discovered.

Qt is wild, it can interop with gtk2 and gtk3, but it requires stuff to be configured accordingly and the configuration will have gone stale for users that transitioned from a gtk2 to a gtk3 world.

Let me know if that ended up being related, and whether the `QT_QPA_PLATFORMTHEME` had anything to do with it.

You could also try... `env -u QT_QPA_PLATFORMTHEME ./bin/git-cola` to test what happens what that variable is unset (in case it's already set).

Generally I'm hoping distros pre-configure this for users. IIRC, ubuntu may have been setting this on user's behalf already, but I'm not sure about mint.

I'm a debian/testing user, and in that setup I did have to configure that myself manually.

**Comment by KammutierSpule** [comment]
> If it says qt5ct then you're already setup correctly
its ok then

`env -u QT_QPA_PLATFORMTHEME python3 /usr/bin/git-cola`
runs OK on anycase with white background, no messages on terminal.

The problem happens when I set on qt5ct Style: gtk2

**Comment by davvid** [comment]
Thanks for confirming. I think this isn't really a cola issue, but something that should be reported to the distribution so that they can configure their Qt installation to interop nicely with the desktop environment.

BTW this is a way old thread but it mentions qt5ct and a `QT_STYLE_OVERRIDE` variable. Could this be related?

https://forums.linuxmint.com/viewtopic.php?t=228903

I'd like to close this issue but I also think there could be something we can learn that we can add to our docs, so I'll leave this open for now in case by some stroke of luck that thread is related to the issue you're hitting. Please let me know if you're able to confirm, or whether this is still an issue in the newer Mint versions.
