### ISSUE TITLE
Feature Request: console - linkify support

### ISSUE THREAD

**Issue by jakubklos77** [git-cola/git-cola#1139]
Hello
it would be extremely useful if links in the git-cola console could be clickable. Currently with each push request I need to select the link, copy to clipboard and paste to the browser to create a merge request. I am sure most users would benefit from this functionality
Thank you

**Comment by davvid** [comment]
Great idea, thanks for the sug!

The latest version from git lets you right-click anywhere on a line that contains URLs and it'll offer to open the URLs.

You don't need to select the links or even click directly on them -- right-clicking anywhere on the line that contains a link is enough to detect the link and add them to the context menu.

**Comment by jakubklos77** [comment]
Perfect, works great. Thank you. Made my day :) :1st_place_medal:
