### ISSUE TITLE
Some tests fail if commit signing is enabled

### ISSUE THREAD

**Issue by di72nn** [git-cola/git-cola#1140]
11 tests doing `commit` fail with
```
    self.assertEqual(status, 0)
E   AssertionError: 128 != 0
```
if `gpgSign = true` is set in the global gitconfig (probably when signing requires user interaction).

I'm experiencing this while trying to build git-cola via the [AUR package](https://aur.archlinux.org/packages/git-cola), so maybe it has something to do with packaging, but I would expect tests to ignore global config regardless of the way they are run.

**Comment by davvid** [comment]
Thanks for the heads-up.
