### ISSUE TITLE
Git-Cola is always breaking when its dependencies upgrade their version even against each other below i am attaching the error: (Macbook pro(Big Sur))

### ISSUE THREAD

**Issue by maranza** [git-cola/git-cola#1142]
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtWebEngineWidgets module requires API v12.9

Now should we wait for sip to upgrade its API usage of what can be the solution here, because my git-cola is not starting because of that.

**Comment by Offirmo** [comment]
same error after the last Catalina update.

**Comment by davvid** [comment]
It's not really our fault that Apple / MacOS likes to break its users all the time. I feel your pain, but there is nothing we can really do about it.

There's a section in the README about this specific issue. Please read it and open a PR that adds more details to the README if the steps in there aren't sufficient.
