### ISSUE TITLE
After upgrade to Ubuntu 20.04 git-cola not working. (Qt bindings install problem)

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#1144]
To whom it may concern.
I tried all the different qtpy apt packages I could find in google but the error keeps showing. Can somebody maybe help me with the corrrect "apt install" to install the requirements for  git-cola on Ubuntu 20.04.

My setup before upgrade. I runned from source in Ubuntu 18.04.

I already tried to install "apt install git-cola" that did not help. Maybe the run from source setup and normal install method clashes.

Error I keep getting
![image](https://user-images.githubusercontent.com/8427483/122348263-4316da00-cf4b-11eb-957b-15add0badea3.png)

Thanks in advance

**Comment by NielBuys** [comment]
In file "git-cola/bin/git-cola"

I needed to change a line to get my git-cola working.

I changed the line "#!/usr/bin/env python" to "#!/usr/bin/env python3" and now its working.

I changed the same line in "git-cola/bin/git-dag" also to get that working also.

I am running from source so now I will have to change this every time I do a pull from Github. Can't we do something that it permanently work for both cases. I am not a python developer.

**Comment by davvid** [comment]
I think we can start considering it. We'll still keep python2 support (for reasons), but starting to swap the `#!` lines over is probably okay to do at this point. I was going to wait until the end of the year.

**Comment by NielBuys** [comment]
Do I understand you correct should I create a pull request for the change. Its already showing as changed items in my git-cola.

**Comment by davvid** [comment]
Sorry for leaving you hanging. Yes, please, if you have the `#!/usr/bin/env python3` changes sitting ready to commit I'll merge them anytime now that it's 2022. Please see the linked issue for context.

**Comment by NielBuys** [comment]
@davvid. Ok pull request done. Have a nice day.

**Comment by davvid** [comment]
We use python3 `#!` shebang lines these days so this should be a non-issue. We also now support PyQt6 so there shouldn't be any holdups on newer versions of Ubuntu.

I'm about to tag v4.1.0 which will be the first release w/ Qt6 support.
