### ISSUE TITLE
Git hub request an Oath.

### ISSUE THREAD

**Issue by ca3games** [git-cola/git-cola#1145]
Today I got an email from github saying they will disable soon only password pushes.
And that I need an application oath to allow new pushes.

Would appreciate any help.

**Comment by davvid** [comment]
For pushing, you can use the remote editor to make sure that you're using ssh URLs.

Example transformation:
```
# Replace the https URLs
https://github.com/user/repo.git

# WIth ssh-style URLs
git@github.com:user/repo.git
```

And upload your ssh key to github.com. (this ssh does not necessarily need to have a password attached to it; if you use one you'll want to use an ssh agent).

Please see #1132 for more details.
