### ISSUE TITLE
Support submenus for git-config guitool.*

### ISSUE THREAD

**Issue by vermiculus** [git-cola/git-cola#1150]
This is a pretty sweet tool! Particularly its friendliness to shell scripts and the like.

Something that will be helpful for us is the git-config `guitool.*` support (related: #44). One difference I see between git-cola and `git gui` is that the latter will construct menu hierarchies with things like `guitool.MyCorp/Custom Tool.*`. Considering the modest number of actions we'd like to conveniently support (5-10), having a submenu here would be very helpful.

Was this missed in the initial implementation or was it decided against? In other words, would you be open to an implementation?

**Comment by davvid** [comment]
Ah I missed that feature in the original implementaion. That feature goes back many years so I'm not sure if it was originally part of the spec or if it was later added to `git-gui`.

In any case, we should totally support this feature. 👍
