### ISSUE TITLE
Centos 7.9 - 3.10 not working / 3.9 working

### ISSUE THREAD

**Issue by futureweb** [git-cola/git-cola#1155]
Hey there,
unfortunately V 3.10 won't run on my Centos 7 Server.
It won't accept any Commands supplied.

```
./git-cola version
usage: git-cola [-h] [--help-commands]
{cola,about,am,archive,branch,browse,clone,config,dag,diff,fetch,find,grep,merge,pull,push,rebase,recent,remote,search,stash,tag,version}
...
...
```
Same with every Command ... 
Versions up to 3.9 work as expected.

Any ideas on that?

thx, bye from Austria
Andreas S.

**Comment by davvid** [comment]
Ahh thanks for the heads-up. I bet this commit is related. fb210c07805e9c0b3f7fec0370ac36396070a9b7

How quaint! My macOS environment reports the same exact argparse version, and Python 2.7, and yet it doesn't reproduce there. It does reproduce in my RHEL 7.9 environment. Interesting!

I think we can make this work by detecting the older version, perhaps.

RHEL 7.9 has Python 2.7.5 and this macOS install has 2.7.16. That *could* be related.

I'm now tempted to enable the new behavior from that commit in Python >= 3.7 only. I just tried a 3.7 environment and it's happy with what we currently have, so I'm going to assume that it's safe to do starting at 3.7.
