### ISSUE TITLE
[Feature] [Patch] DAG colors for dark theme

### ISSUE THREAD

**Issue by prof7bit** [git-cola/git-cola#1158]
please see the attached patch.

It still lacks automatic detection of light/dark theme and is now hardcoded for dark theme. It could either just compare window color and windowText color of the current theme to see if background is darker (preferred) or it could be made a config option.

I have identified all of the offending hardcoded colors and moved their definition all to one place (a static class abused as namespace) where they are assigned from two sets of colors, one for white background (the original colors) and one for dark background.

Please tell me whether I can proceed in this direction or whether this is all nonsense.

Attached patch renamed to .txt because stubborn Github won't allow upload of .patch files
[0001-dag-dark-colors.patch.txt](https://github.com/git-cola/git-cola/files/7129865/0001-dag-dark-colors.patch.txt)

**Comment by gnat** [comment]
Please turn this on when you select Dark Icon theme and/or when you select one of the dark themes!

The DAG is wonderful but blinding.

**Comment by davvid** [comment]
The DAG should be respecting dark mode now. I'm a dark theme user so it's nice and dark now in modern versions.
