### ISSUE TITLE
language files should not translate git commands

### ISSUE THREAD

**Issue by prof7bit** [git-cola/git-cola#1160]
git commands like "push", "pull", "commit", "checkout", etc should not be translated into other languages in the user interface. It is the main reason why people are trying to run it in the untranslated version because it completely breaks the mental connection between what I am trying to do with git and how it is called in the localized translation.

I am looking for "push" and then I have to try to reverse the twisted mind of the translator until I find a menu entry that reads "Veröffentlichen" (German) and would actually translate to "publish" which is something entirely different, and there is no way to find out which of these strange commands does what I want, other than clicking it and trying to interpret from the symptoms what it actually did!

please remove all these misleading strings from all translation files.

**Comment by pilarmolinalopez** [comment]
Hello. I think that makes a lot of sense. In fact, if I'm not mistaken, the Spanish translations do not translate those type of strings (strings that correspond to git commands).

**Comment by atharvapatil123** [comment]
Hi @prof7bit, Is the issue still open? If yes, I'd like to take up on it.

**Comment by jalajk24** [comment]
@prof7bit i would like to contribute in this issue can you assign it to me and drop some insight?

**Comment by davvid** [comment]
Thanks @jalajk24 for stepping up. I updated the translation files so that the metadata is up to date.

All of the translations can be found in `cola/i18n/*.po`, for example `cola/i18n/fr.po` contains the French translations.

You should be able to edit the .po files directly and cola will pickup the new translations (there's no "build" step -- the files are consumed as-is).

You can test other languages by launching with a custom $LANG environment variable, eg.:

```
env LANG=fr_FR.UTF-8 ./bin/git-cola
```

**Comment by davvid** [comment]
I took a stab at some of the easy German ones over in https://github.com/git-cola/git-cola/pull/1343

Let me know what you think @prof7bit.  It's not everything but it should be better than what's currently there.

**Comment by OriShalhon** [comment]
where does this issue stand? could I contribute to it?

**Comment by davvid** [comment]
I made some tweaks but pull requests are always accepted. The translation files are located at `cola/i18n/*.po`. This issue should probably be closed by adding a todo note for translators in `CONTRIBUTING.md` noting the preference for leaving git command jargon untranslated.

**Comment by OriShalhon** [comment]
Based on [1343](https://github.com/git-cola/git-cola/pull/1343) I made [1349](https://github.com/git-cola/git-cola/pull/1349) changing Czech, Spanish and French- will continue to additional languages if accepted

**Comment by OriShalhon** [comment]
Created new pull-request [1351](https://github.com/git-cola/git-cola/pull/1351), finished all languages and added a test to verify no language translates basic git jargon.

**Comment by OriShalhon** [comment]
@davvid - IMO once this is accepted - including merge conflict (accept new test) this request can possibly be closed.
