### ISSUE TITLE
LANGUAGE environment variable affects serialization of 'windowstate'

### ISSUE THREAD

**Issue by prof7bit** [git-cola/git-cola#1161]
Steps to reproduce:

- delete all settings in ~/.config/git-cola
- start it with `LANGUAGE=en python3 bin/git-cola` and immediately quit it again
- make a backup of the generated settings file as `en_settings`
- delete all settings in ~/.config/git-cola
- start it with `LANGUAGE=de python3 bin/git-cola` and immediately quit it again
- make a backup of the generated settings file as `de_settings`

diff the two files:
````diff
$ diff -u en_settings de_settings 
--- en_settings 2021-09-09 10:56:06.086221590 +0200
+++ de_settings 2021-09-09 10:55:52.826278913 +0200
@@ -8,7 +8,7 @@
             "x": 0,
             "y": 0,
             "lock_layout": false,
-            "windowstate": "AAAA/wAAAAL9AAAAAgAAAAIAAAUAAAAByfwBAAAAA/sAAAAMAFMAdABhAHQAdQBzAQAAAAAAAADeAAAAcAAAIAD7AAAADABDAG8AbQBtAGkAdAEAAADhAAACDgAAAJMA/////AAAAvIAAAIOAAAAvAD////6AAAAAAEAAAAE+wAAABAAQgByAGEAbgBjAGgAZQBzAQAAAAD/////AAAAlQD////7AAAAFABTAHUAYgBtAG8AZAB1AGwAZQBzAQAAAAD/////AAAAvAD////7AAAAEgBGAGEAdgBvAHIAaQB0AGUAcwAAAAAA/////wAAAKcA////+wAAAAwAUgBlAGMAZQBuAHQAAAAAAP////8AAACGAP///wAAAAMAAAUAAAAByfwBAAAAAvsAAAAIAEQAaQBmAGYBAAAAAAAABQAAAABhAP////wAAAAA/////wAAAAAA////+v////8BAAAAAvsAAAAOAEEAYwB0AGkAbwBuAHMAAAAAAP////8AAABfAP////sAAAAOAEMAbwBuAHMAbwBsAGUAAAAAAP////8AAABjAP///wAAAwYAAAAAAAAABAAAAAQAAAAIAAAACPwAAAAA",
+            "windowstate": "AAAA/wAAAAL9AAAAAgAAAAIAAAUAAAAByfwBAAAAA/sAAAAOAFoAdQBzAHQAYQBuAGQBAAAAAAAAAN4AAAB7AAAgAPsAAAAMAEMAbwBtAG0AaQB0AQAAAOEAAAJKAAAAxgD////8AAADLgAAAdIAAAC8AP////oAAAAAAQAAAAT7AAAAEABCAHIAYQBuAGMAaABlAHMBAAAAAP////8AAACVAP////sAAAAUAFMAdQBiAG0AbwBkAHUAbABlAHMBAAAAAP////8AAAC8AP////sAAAASAEYAYQB2AG8AcgBpAHQAZQBuAAAAAAD/////AAAAqQD////7AAAAEABLAPwAcgB6AGwAaQBjAGgAAAAAAP////8AAACNAP///wAAAAMAAAUAAAAByfwBAAAAAvsAAAASAFYAZQByAGcAbABlAGkAYwBoAQAAAAAAAAUAAAAAggD////8AAAAAP////8AAAAAAP////r/////AQAAAAL7AAAADgBCAGUAZgBlAGgAbABlAAAAAAD/////AAAAYQD////7AAAAEgBNAGUAbABkAHUAbgBnAGUAbgAAAAAA/////wAAAHgA////AAADSAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=",
             "show_status_filter": false,
             "toolbars": [],
             "ref_sort": 0,
````

This results in a completely messed up panel arrangement when switching language on an existing installation. It is responsible for this 7 year old bug https://github.com/git-cola/git-cola/issues/382 and I bet this is also responsible for this: https://github.com/git-cola/git-cola/issues/1071

**Comment by prof7bit** [comment]
The windowstate contains translated window names!

````
hexdump -C de              
00000000  00 00 00 ff 00 00 00 02  fd 00 00 00 02 00 00 00  |................|
00000010  02 00 00 05 00 00 00 01  c9 fc 01 00 00 00 03 fb  |................|
00000020  00 00 00 0e 00 5a 00 75  00 73 00 74 00 61 00 6e  |.....Z.u.s.t.a.n|
00000030  00 64 01 00 00 00 00 00  00 00 de 00 00 00 7b 00  |.d............{.|
00000040  00 20 00 fb 00 00 00 0c  00 43 00 6f 00 6d 00 6d  |. .......C.o.m.m|
00000050  00 69 00 74 01 00 00 00  e1 00 00 02 4a 00 00 00  |.i.t........J...|
00000060  c6 00 ff ff ff fc 00 00  03 2e 00 00 01 d2 00 00  |................|
00000070  00 bc 00 ff ff ff fa 00  00 00 00 01 00 00 00 04  |................|
00000080  fb 00 00 00 10 00 42 00  72 00 61 00 6e 00 63 00  |......B.r.a.n.c.|
00000090  68 00 65 00 73 01 00 00  00 00 ff ff ff ff 00 00  |h.e.s...........|
000000a0  00 95 00 ff ff ff fb 00  00 00 14 00 53 00 75 00  |............S.u.|
000000b0  62 00 6d 00 6f 00 64 00  75 00 6c 00 65 00 73 01  |b.m.o.d.u.l.e.s.|
000000c0  00 00 00 00 ff ff ff ff  00 00 00 bc 00 ff ff ff  |................|
000000d0  fb 00 00 00 12 00 46 00  61 00 76 00 6f 00 72 00  |......F.a.v.o.r.|
000000e0  69 00 74 00 65 00 6e 00  00 00 00 00 ff ff ff ff  |i.t.e.n.........|
000000f0  00 00 00 a9 00 ff ff ff  fb 00 00 00 10 00 4b 00  |..............K.|
00000100  fc 00 72 00 7a 00 6c 00  69 00 63 00 68 00 00 00  |..r.z.l.i.c.h...|
00000110  00 00 ff ff ff ff 00 00  00 8d 00 ff ff ff 00 00  |................|
00000120  00 03 00 00 05 00 00 00  01 c9 fc 01 00 00 00 02  |................|
00000130  fb 00 00 00 12 00 56 00  65 00 72 00 67 00 6c 00  |......V.e.r.g.l.|
00000140  65 00 69 00 63 00 68 01  00 00 00 00 00 00 05 00  |e.i.c.h.........|
00000150  00 00 00 82 00 ff ff ff  fc 00 00 00 00 ff ff ff  |................|
00000160  ff 00 00 00 00 00 ff ff  ff fa ff ff ff ff 01 00  |................|
00000170  00 00 02 fb 00 00 00 0e  00 42 00 65 00 66 00 65  |.........B.e.f.e|
00000180  00 68 00 6c 00 65 00 00  00 00 00 ff ff ff ff 00  |.h.l.e..........|
00000190  00 00 61 00 ff ff ff fb  00 00 00 12 00 4d 00 65  |..a..........M.e|
000001a0  00 6c 00 64 00 75 00 6e  00 67 00 65 00 6e 00 00  |.l.d.u.n.g.e.n..|
000001b0  00 00 00 ff ff ff ff 00  00 00 78 00 ff ff ff 00  |..........x.....|
000001c0  00 03 48 00 00 00 00 00  00 00 04 00 00 00 04 00  |..H.............|
000001d0  00 00 08 00 00 00 08 fc  00 00 00 00              |............|
000001dc
````

Don't identify the windows by their captions, I'm no Tt expert but there certainly must exist a better way in Qt5 to refer to a window independently of its translated caption!

**Comment by davvid** [comment]
Nice find! I think this link might be relevant:
https://forum.qt.io/topic/79570/save-restore-all-layout-settings/2

There is a note there that says:
> For the widget directly handled by QMainWindow i.e QDockWidget, QToolBars, you have to give each widget an object name for the save/restoration to happen properly.

That could explain it. I'll have to read the Qt source code to be sure, but perhaps it's using the dockwidget titles as the object name since we are not setting the names explicitly.

Thanks for tracking this down. This suggests that we should be able to fix this by calling `self.setObjectName('unique-name')` for each of dockwidgets. We may need to set the object name for the top-level dialogs/windows too.

Are you only seeing the dockwidget titles in the file? 

I suspect that this ony affects the QMainWindow objects, as those are the only ones that have dockwidgets. I'll give that a try. BTW, how did you get that hex dump? Did you paste the base64 text into a new file, or did you base64 decode it first?

**Comment by davvid** [comment]
Oh shoot, indeed we are calling `setObjectName()` with a translated string. 😞  Thanks a ton for tracking that down. As they say, debugging the problem is sometimes the hardest part and if it wasn't for your effort we wouldn't have come to this conclusion.

Alrighty, this should be pretty straightforward now that I believe we've narrowed in on the root cause. Thanks!
