### ISSUE TITLE
Allow project selection with Enter key on app open

### ISSUE THREAD

**Issue by kopach** [git-cola/git-cola#1162]
In most cases, I use `git-cola` by running it as a standalone app. In this case, the first view I see after `git-cola` start is recent project list. I can easily select one of recent projects by using arrow keys, but I can't trigger opening of those projects with keyboard. Not sure, if there is any specific shortcut for that (haven't found), but would be great to have `<Enter>` key assigned to this "open selected project" action.

Here is a demo to make things more clear
![2021-09-10 09 40 05](https://user-images.githubusercontent.com/8749624/132819191-75ddec45-b79e-46e0-800d-62f060b583b4.gif)

---
- git-cola version: 3.10.1
- OS: macOS Big Sur 11.5.2

**Comment by davvid** [comment]
Good idea, yeah let's do this.

Right now the we have the `ctrl-o` / `cmd-o` hotkey for "open" but `enter` would be really nice on that screen.
