### ISSUE TITLE
DAG: Thread tried to wait on itself

### ISSUE THREAD

**Issue by juona** [git-cola/git-cola#1166]
Hi there,

I have been running git-cola on Manjaro for a while now, currently using v3.10.1 (installed from the Arch Linux User Repository). I like the GUI but it's always had this problem.

Often (anywhere from 30% to 80% of the time) when I try to launch the DAG GUI, it fails to open and this is logged in the journal:

`python[24839]: QThread::wait: Thread tried to wait on itself`

Occasionally, attempting to launch the DAG GUI will crash the process altogether (segfault). However, this can happen when trying to perform just about any action (not just launching the DAG GUI) - stash, pop, commit, branch, etc.

Perhaps there's a problem with my installation/setup, as I've not been able to find anyone else experiencing this behaviour.

This is the version output:

Git Cola version 3.10.1 
Linux-5.10.52-3-rt47-MANJARO-x86_64-with-glibc2.33 
Python (/usr/bin/python) 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0] 
Git 2.33.0 
Qt 5.15.2 
QtPy 1.9.0 
PyQt5 5.15.4

**Comment by davvid** [comment]
I believe this was resolved during the recent update to use Qt objects instead of our custom observable classes.

54dbf4fca491c8d3bc69e1cacf237b8622b9c5a3 and PR #1206 should have fixed this.

**Comment by juona** [comment]
I broke my previous system and had to reinstall Manjaro. Same laptop, same everything, albeit newer versions of some things, and now all these problems seem to be gone. I hope it's because of your good work! : ]
