### ISSUE TITLE
Replace "Select manually..." with "Browse..." in the open respository dialog.

### ISSUE THREAD

**Issue by safield** [git-cola/git-cola#1167]
The standard language used for this operation is "Browse". The term is quite ubiquitous.

**Comment by jackrsteiner** [comment]
@safield I'm pretty sure I see where this is coming from. Name attribute in calls to QFileDialog are empty strings (caption='') in [qtpy/compat](https://github.com/git-cola/git-cola/blob/main/qtpy/compat.py#L78).

So button labels must be showing defaults based on your system. On my machine, these buttons have reasonable labels, generated from my platform native file browser. I'm using Ubuntu 20.04. Can you clarify, what platform you're on and where exactly you're seeing this? I suspect your system might be different? Maybe the Qt libraries are using a custom file browser.

I think the solution is to set default caption to desired text in https://github.com/git-cola/git-cola/blob/main/cola/qtutils.py#L443

`def opendir_dialog(path, caption='Browse...'):`

But this only impacts systems that are using platform specific Qt libraries that do not use the platform native file browser dialog. So, I think this is why I can't test it.

**Comment by atharvapatil123** [comment]
Hi @safield, Is the issue still open?

**Comment by meaviral17** [comment]
Hi @safield just sent my PR. Please check if it functions properly.

**Comment by davvid** [comment]
Sorry, I should have closed this issue! My mistake. This was resolved a little bit ago.
