### ISSUE TITLE
Double clicking a folder in the Open Repository > Select Manually... dialog, allows you to edit the folder name.

### ISSUE THREAD

**Issue by safield** [git-cola/git-cola#1168]
Double clicking a folder in the Open Repository > Select Manually... dialog, allows you to edit the folder name.

Generally, open folder / file, file explorer dialogs do not allow for editing / writing the file system. Allowing editing / writing in "Open folder/file" dialog goes against established UI patterns found across Windows/Mac/Linux desktop UI's. This is a clear anti-pattern.

**Comment by davvid** [comment]
Thanks for the heads-up!
