### ISSUE TITLE
Improve Mac installation procedure.

### ISSUE THREAD

**Issue by safield** [git-cola/git-cola#1169]
Installing on Mac is a real headache. Could this be simplified at all?

**Comment by safield** [comment]
To follow up. Why do I install via homebrew and then still need to clone the git repo? What is going on here? So many steps, and unclear what is going on.

**Comment by davvid** [comment]
If you install via homebrew you can stop at that step.

Cloning the repo is useful if you're going to be developing on cola, or want to run the latest from source. I'll try to update the instructions to make that clearer.

The point of the homebrew install is to get the PyQt5 dependencies installed. That said, these days we now support the much simpler `pip install git-cola` workflow inside of a virtualenv.

From scratch (and without needing to activate the virtualenv) you can do this:

```
python3 -m venv env39
./env39/bin/pip install git-cola
./env39/bin/git-cola
```

Hope that helps.
