### ISSUE TITLE
Exception unstaging file via toolbar action

### ISSUE THREAD

**Issue by lah7** [git-cola/git-cola#1178]
Spotted a bug when trying to unstage a file via its toolbar action. Unstaging via the keyboard shortcut (CTRL+S) works and context menu is unaffected. 

### Steps to reproduce

1. Add **Unstage** to a toolbar.
2. Stage a file.
3. Click **Unstage** on the toolbar.

### Traceback
```
Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/cola/cmds.py", line 2942, in do
    cmd = cls(*args, **opts)

  File "/usr/lib/python3.9/site-packages/cola/cmds.py", line 2693, in __init__
    staged = self.selection.staged

AttributeError: 'UnstageSelected' object has no attribute 'selection'
```

**Comment by davvid** [comment]
Thanks for the report!
