### ISSUE TITLE
Doesn't detect repositories on WSL

### ISSUE THREAD

**Issue by karolzlot** [git-cola/git-cola#1182]
I installed git-cola on Windows. I tried to open repository from WSL (Ubuntu). Other GUI clients open it, but git-cola wants to create new repository. So it can't detect it.

![AAXx8MnT9V](https://user-images.githubusercontent.com/11590960/140854685-66d1d5df-4fe6-49d1-aa93-d77ef3c2654f.png)

**Comment by karolzlot** [comment]
When I copied repo from WSL filesystem to Windows filesystem it opened ok.

**Comment by p-baum** [comment]
Confirmed

**Comment by davvid** [comment]
Interesting. What do the "Git for Windows" git command-line tools do with these repos? We're just calling into `git` so I wonder if there's something about these repos that confuse native git-for-windows?

**Comment by karolzlot** [comment]
I tried to create repo in git for linux and then use it in git for windows:

![image](https://user-images.githubusercontent.com/11590960/170051841-10bae44e-ec1a-436f-97b2-f4136e40f726.png)

![image](https://user-images.githubusercontent.com/11590960/170051893-f4c01ef9-7f2b-4c69-bf9b-160a2a3c977d.png)

-----

Anyway I think for git repositories inside WSL Linux "git for Linux" should be used from this Linux, at least for performance reasons (currently file access between WSL and Windows is quite slow).

**Comment by davvid** [comment]
Does it work after you follow the advice and run that `git config --global --add safe.directory ....` command?

**Comment by davvid** [comment]
You can yolo and live dangerously by running `git config --global safe.directory '*'` and then you won't have to allow each one separately.

This is dangerous security advice, but it is convenient.

When I get a chance I'm considering putting together a patch for core git that allows `safe.directory` to be set to `'/some/path/**'` so that you can allow any repo under `/some/path`, but that feature does not currently exist.

**Comment by davvid** [comment]
Ultimately this is a limitation in WSL so kindly also report this issue to the WSL team so that they can improve it. There's probably not much we can do on our side.

It also sounds like this may not really be an issue, per the notes above about `safe.directory`.

Related-to: #1194
