### ISSUE TITLE
stage selected lines with capital S keypress does nothing

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1187]
git cola 3.6

When I highlight some lines in Diff view and press capital S, nothing happens.
If I right click and choose "stage selected lines" then the lines do get staged.

**Comment by davvid** [comment]
I forget whether or not there was a strong reason why I didn't map both `s` and `S`, but that seems like it would be a nice usability improvement, since the user may have been using shift to adjust their selection. Good idea. It think this should be really straightforward to add.
