### ISSUE TITLE
[wine] The selection contains a non-folder object

### ISSUE THREAD

**Issue by nick87720z** [git-cola/git-cola#1190]
This error appears when I try to clone something using windows version, installed under wine.
Using installer for version 3.11 from download page.
My actions:
1. Starting git-cola (or git-dag - no difference without opened repo)
2. Clone - opens clone dialog. Used git-cola repo for test.
3. Select Folder dialog - I selected pre-created empty dir `Documents/dist/dev`. This causes error as in title.
4. Tried to manually prepend name of unexisted dir inside existing one. Same error, though prepended by new one, like 'file not found'.

For background - I'm testing for curiosity, how some free software works under windows, while wine is the only option to do it.
Git for windows is installed (from installer too).

++ Nothing in logs besides wine complaining about unimplemented call EnableNonClientDpiScaling - runing from wineconsole.

**Comment by kurtmckee** [comment]
@davvid I recommend closing this issue if git-cola isn't targeting wine as a supported platform.

**Comment by davvid** [comment]
Thanks, yeah I agree. Also, I suspect that the mimedata interop may improve in future versions of Wine and we won't need to do anything to pickup those enhancements, so there's not much for us to do app-side.
