### ISSUE TITLE
Help->About crash

### ISSUE THREAD

**Issue by wojnilowicz** [git-cola/git-cola#1192]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cola/widgets/about.py", line 41, in tabSizeHint
    size.setWidth(width)
TypeError: setWidth(self, int): argument 1 has unexpected type 'float'
Aborting (memory dump)

Using cola version 3.11.0

**Comment by davvid** [comment]
Please test `main`. We have some `setWidth()` fixes that would fix this. I'll plan to tag and release v3.12 soon.

**Comment by davvid** [comment]
`v3.12.0` was just tagged and contains fixes for this. Please test the latest from git. Thanks for the heads-up.
