### ISSUE TITLE
git-cola 3.12.0 runtime issue

### ISSUE THREAD

**Issue by chenrui333** [git-cola/git-cola#1195]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>run failure</summary>

```
==> /opt/homebrew/Cellar/git-cola/3.12.0/bin/git-cola --version You do not seem to have PyQt5, PySide, or PyQt4 installed. Please install it before using git-cola, e.g. on a Debian/Ubutnu system: sudo apt-get install python-pyqt5 python-pyqt5.qtwebkit
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/4887128925
relates to Homebrew/homebrew-core#93493

**Comment by davvid** [comment]
I believe we've resolved this issue now. We now use a PEP-517/PEP-518-compatible build system (setuptools + setup.cfg + pyproject.toml) and we no longer generate `*.mo` files during the build.
