### ISSUE TITLE
git-cola does not launch on Windows without Microsoft Visual C++ 2015 Redistributable

### ISSUE THREAD

**Issue by living180** [git-cola/git-cola#1196]
I installed git-cola on a Windows 10 64-bit virtual machine with very few other programs installed.  When I tried to launch git-cola, I saw essentially the same stack trace as #787.  Digging into a bit, I found that PyQt5.QtCore could not be imported, and that the root cause was that vcruntime140.dll could not be found.  Once I downloaded the Microsoft Visual C++ 2015 Redistributable from https://www.microsoft.com/en-us/download/details.aspx?id=52685 and installed it, git-cola launched successfully.

I don't know if it is possible or desirable to include the necessary Microsoft Visual C++ 2015 Redistributable DLLs in the git-cola Windows installer, but if not, this should probably be mentioned in the README so that other users don't run into this same issue.

**Comment by davvid** [comment]
I suspect that 1945126f33f08a2b2983b123d029d95bdb4d248d may be the root cause, as it added `pkgs/PyQt5/Qt/bin/vcruntime140.dll` to the `pynsist.cfg`

I think we should probably remove that line. Heads-up @Mithil467

**Comment by davvid** [comment]
I believe #1207 should fix this. Thanks for the root cause analysis.
