### ISSUE TITLE
Feature Request: editor setting per repo

### ISSUE THREAD

**Issue by black-silence** [git-cola/git-cola#1210]
I'd like to have a per-repo-override of the editor config.

Use case: so far I've been working with vscode but we're migrating to Kotlin/IntelliJ. For the new repo I don't want to use vscode as editor that I launch from git-cola but I don't want to change my global default yet.

Anyone using several spezialized IDEs could benefit from this feature.

**Comment by davvid** [comment]
I believe we do support this feature already. If you run `git config core.editor <value>` inside a worktree then cola will respect that value when operating inside that repo.

Let me know if this is the setting you had in mind. Most of our settings follow the typical Git config model where we can configure things system-wide in `/etc/gitconfig`, user-wide in `~/.gitconfig` (or `~/.config/git/config` these days, IIRC) and repo-wide in `.git/config`.

The order of precedence is repo-wide, user-wide and system-wide. The first one found typically wins.

**Comment by black-silence** [comment]
Thanks for the tip, I've only ever set this through cola settings so I didn't check the git config. The correct key is ```gui.editor```, the core editor I use is completely different and not a graphical IDE.
