### ISSUE TITLE
Every time someone submits the code, after I pull it, there is no conflict, but it will generate a "Merge branch 'master' of https://xxx" to be submitted. TortoiseGit does not have this problem.

### ISSUE THREAD

**Issue by goophps** [git-cola/git-cola#1216]
Every time someone submits the code, after I pull it, there is no conflict, but it will generate a "Merge branch 'master' of https://xxx" to be submitted. TortoiseGit does not have this problem. Hope it gets resolved.

**Comment by davvid** [comment]
Enable the "Rebase" checkbox in the "Pull" dialog. That should resolve this issue.

The core issue is that you also have a local commit (that they don't have) so it's going to continually create merge commits until they pull from you, or until you rebase/update against their version.
