### ISSUE TITLE
AttributeError: 'BranchesTreeWidget' object has no attribute 'pull'

### ISSUE THREAD

**Issue by jakubklos77** [git-cola/git-cola#1219]
After a recent "main" branch update I can no longer pull with git-cola.
This is the error I get
```
Traceback (most recent call last):
  File "/home/jakub/app/git-cola/cola/qtutils.py", line 950, in run
    self.result = self.task()
  File "/home/jakub/app/git-cola/cola/widgets/branch.py", line 51, in task
    git_action = getattr(self.git_helper, self.action)
AttributeError: 'BranchesTreeWidget' object has no attribute 'pull'
```
If I revert back to some previous commit it works properly. Either this is a Python 3.10.3 issue or it just does not work properly in git-cola.
Can some please take a look at this?

**Comment by davvid** [comment]
Thanks for the heads-up!

**Comment by jakubklos77** [comment]
Wonderful, thank you. Works properly now.

**Comment by living180** [comment]
Thanks @davvid for the quick work on this.  When I saw the report I wondered if it was related to my changes, but didn't get a chance to investigate before you had a fix in already.
