### ISSUE TITLE
Focus lost when changing branches

### ISSUE THREAD

**Issue by jakubklos77** [git-cola/git-cola#1221]
There are 2 issues when checking out branches:

1) Focus is lost instantly
1. Focus/highlight the current branch in the Branches panel
2. Right click another branch you want to switch to and select Checkout
This will cause a lost focus of the switched branch. A moment before clicking Checkout the branch is selected but after clicking, the focus is lost. We should preserve the focus in the Branches panel.

2) After checking out a branch, the focus is reset in some refresh interval.
1. Change / checkout to a branch
2. After the focus is lost (see the issue above), select/focus it instantly (within 500ms)
3. In another 500ms the focus is lost again. There must be some refresh mechanism which loses the selection/focus.
Why is this a problem? If you right click a branch right after checking it out, the focus is lost and no action you click in the context menu gets applied (perhaps because there is no selection so it does not know what branch to apply the action to)

I can provide videos but it should be pretty easy to reproduce.
Thank you

**Comment by kneirinck** [comment]
I've got the same issue where the the branch widget visibly refreshes/redraws 3 times and you have to wait to do anything useful until it completes.
Is there anything we can do to help debug this?

**Comment by davvid** [comment]
Thanks for the heads-up. Yeah, the UI refreshes itself in response to internal notifications so we have to add a bit of logic to get it to save and restore its selection state across refreshes.

We do that already in other places (eg. the status widget) so this is mostly a matter of implementing a similar approach for this widget.

**Comment by davvid** [comment]
Please test the latest from git if you can. This should be much smoother now. Thanks again for the heads-up.

**Comment by kneirinck** [comment]
It's a bit better when you're inside an open tree item (although there is a very light flicker).
But if you're switching to something outside of it it still seems to redraw multiple times.

[Screencast from 25-10-22 21:22:30.webm](https://user-images.githubusercontent.com/3418790/197864080-f765aba3-83b1-4c5a-9bfd-470ec9e63489.webm)

**Comment by davvid** [comment]
Thanks for testing. I found what was triggering the flickering and that should be much better now. We do have to recreate the widgets, and Qt can update the UI in one shot, but we had animations enabled which caused a slight delay when redrawing.

The latest version now disables animations when refreshing the branches widget. That should eliminate the flicker more robustly. Let me know if it's better behaved for you as well.

**Comment by kneirinck** [comment]
That seems to fix it for me. Works great :+1: 
Thanks for the quick response time! :bow:
