### ISSUE TITLE
feature request : keyboard option / menu option   to open terminal to use git command line

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1223]
Sometimes you need to do something directly with git command line. It's useful to be able
to open a terminal easily to do that.

**Comment by davvid** [comment]
What OS are you on? We have this feature on Linux already. There's a `Launch Terminal` option in a few places.

lol.. on macOS that feature actually launches xterm under XQuartz. I should probably make that work with iterm2 somehow.

Are you on Linux?

**Comment by davvid** [comment]
Thanks for the sug -- this should be better behaved now. `Ctrl+Shift+T` is the hotkey for launching a terminal. The "Launch Terminal" action been added to the "Actions" menu as well.

We also include better support for modern gnome-terminal versions (and other terminals).

If want to override the auto-detection and specify the terminal then the `cola.terminal` configuration variable can be used. eg. `git config cola.terminal 'alacritty -e'`

**Comment by boxerab** [comment]
Thanks!
