### ISSUE TITLE
Missing setup.py in share/doc/ in 4.0.0.

### ISSUE THREAD

**Issue by darkshram** [git-cola/git-cola#1230]
Without it, docs and man can't be built. Workaround was creating a relative symlink to setup.py.

**Comment by davvid** [comment]
Thanks for the heads-up. I'm not 100% sure on how the docs process is supposed to be setup in the modern setuptools world.. I can add a symlink if that's recommended, but it seems surprising that it'd need that.

Can you share the exact commands you ran? If you have all dependencies installed (or if you have a virtualenv active with them available) then `make doc` is what I'm usually running.

If you have a virtualenv active, maybe `pip install --editable .` or `python setup.py build` has to be run to make the modules avaiable?

Let me know how you're building stuff so we can help sort things out.

**Comment by darkshram** [comment]
Used `make doc` and tried using manually `sphinx-build` directly. This was more or less the output for both:

```
+ make PYTHON=/usr/bin/python3 SPHINXBUILD=/usr/bin/sphinx-build-3.6 doc
make -C share/doc/git-cola all          
make[1]: Entering directory '/builddir/build/BUILD/git-cola-4.0.0/share/doc/git-cola'
/usr/bin/sphinx-build-3.6 -b html -d _build/doctrees  -a . _build/html
Running Sphinx v4.4.0
making output directory... done
/usr/bin/python3: can't open file '/builddir/build/BUILD/git-cola-4.0.0/share/doc/git-cola/../setup.py': [Errno 2] No such file or directory
Extension error (jaraco.packaging.sphinx):
Handler <function load_config_from_setup at 0xf5c46adc> for event 'builder-inited' threw an exception (exception: Command '['/usr/bin/python3', '/builddir/build/BUILD/git-cola-4.0.0/share/doc/git-cola/../setup.py', '--name', '--version', '--url', '--author']' returned non-zero exit status 2.)
make[1]: *** [Makefile:51: html] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/git-cola-4.0.0/share/doc/git-cola'
make: *** [Makefile:128: doc] Error 2
error: Estado de salida erróneo de /var/tmp/rpm-tmp.V0Fxry (%build)   
Errores de construcción RPM:
    Estado de salida erróneo de /var/tmp/rpm-tmp.V0Fxry (%build)
Child return code was: 1                
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
```
Since both ways were asking for a missing setup.py, just created a symlink.

Tried with github and pypi sources with the same result. At the end, used the pypi sources. Some files are missing in github tarball and fails to build if using %py3_build or %pyproject macros for RPM packages (`python3 setup.py` complains for missing files with github tag sources).

**Comment by davvid** [comment]
Alrighty, I restructured things so that all the docs are in the `docs/` top-level directory. That should make `jaraco.packaging.sphinx` happy.

I think this should work but I'm not sure if you'd be able to test it out without faking out the setuptools_scm component or by having a git repository present so that it can query tags. In any case, I'll plan to tag v4.0.1 over the weekend with this and other small fixes.
