### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by davvid** [git-cola/git-cola#1231]
Subscribe to this issue to be notified about breaking changes.

This issue will be updated as breaking changes are being planned and implemented.

This is not expected to happen very often!

**Comment by davvid** [comment]
# v4.0.0

The build system changed to be based on setuptools. The files installed by git-cola changed -- we now ship our Python modules in site-packages and all of our custom data is tucked away inside the module.

Python2 is no longer "officially" supported (though the code does currently remain python2-compatible in case someone needs it).

The standard Python [build tool](https://pypi.org/project/build/) can be used to generate wheels -- `python -m build -n .`

End users are encouraged to use `pip install git-cola`. Building from source can be done using `pip install .`.

The `Makefile` continues to be supported for .deb, .rpm, homebrew and other standard packaging scenarios.

Please see the [v4.0.0 release notes](https://git-cola.readthedocs.io/en/latest/relnotes.html#v4-0-0) for more details.

**Comment by kurtmckee** [comment]
@davvid I recommend closing this issue, as it duplicates standard CHANGELOG and version numbering functionality.

Breaking changes can reliably be put into the CHANGELOG (as noted by the v4.0.0 comment above, which tells users to look at the release notes for more info).

Major version changes (like the transition from v3 to v4) are also a standard way to indicate potential breaking changes.

**Comment by davvid** [comment]
I guess that's true. I was originally looking into using this issue as a communication method for distro packagers to keep track of larger changes but, yeah, we can do without it.
