### ISSUE TITLE
Disable "File system change monitoring"

### ISSUE THREAD

**Issue by futureweb** [git-cola/git-cola#1232]
Hello,
how to disable "File system change monitoring" in GIT COLA?
Already tried `git config cola.inotify false` but it's still active?
As we are running GIT COLA on a Repo with Millions of Files and tenthousands of Changes it's all very slow and we suppose it's the inode monitoring ...
thx
Andy

![grafik](https://user-images.githubusercontent.com/1698881/170278056-cc9697a1-96bd-4eff-b75b-35e0feb36bdf.png)

**Comment by living180** [comment]
I am not able to reproduce this.  Did you make sure to run `git config cola.inotify false` while in the directory of the slow repo?  To verify, you can make sure there is a

    [cola]
            inotify = false

section in the repo's `.git/config` file.

**Comment by futureweb** [comment]
@living180 - yea - it's correct in the GIT Config File of the slow Repo:

`-bash-4.2$ grep inotify .git/config`
`inotify = false`

**Comment by living180** [comment]
Thanks for that.  I'm not sure then.  @davvid any ideas?

**Comment by futureweb** [comment]
@davvid - global disable did the trick and is no problem in our case ... thx! :-)
