### ISSUE TITLE
Custom GIT_DIR is not respected when starting git-cola

### ISSUE THREAD

**Issue by sergei-dyshel** [git-cola/git-cola#1233]
Steps to reproduce:
```
# run in blank dir

export GIT_DIR=.gitgit
export GIT_WORK_TREE=.

# create empty repo
git init

ls
# => should show .gitgit

git status
# => should not error, git respects these variables

git-cola
# doesn't recognize the repo  in current dir, shows repo chooser dialog instead
```

This kind of breaks `git-cola` for custom .git dirs, although all the machinery is there (in `git.py`).

**Comment by sergei-dyshel** [comment]
seems to be solved by https://github.com/sergei-dyshel/git-cola/commit/26077998ee369a0295bfbdf596923a2860175a32

**Comment by davvid** [comment]
That commit does seem sensible. We did intend to support custom GIT_DIR and GIT_WORK_TREE settings.

There might be a few places (which I think you already found) where `.git` might be hard-coded but I'd be happy to take patches that trim those away.

There is one wrinkle when running in that mode ~ doing things like trying to open a different repository may behave unexpectedly / incorrectly, but that's acceptable as long as the single-repo use case is kept working when a custom GIT_DIR is being used.

Thanks for digging into these edge cases, that's really helpful.
