### ISSUE TITLE
v4.0.0 does not start on MacOS

### ISSUE THREAD

**Issue by sergei-dyshel** [git-cola/git-cola#1234]
The problem seems in this code (`i18n.py:get_filename_for_locale()`):
```
    if not name:  # If no locale was specified then try the current locale.
        name = locale.getdefaultlocale()[0]

    name = name.split('.', 1)[0]  # foo_BAR.UTF-8 -> foo_BAR
```

This code assumes `locale.getdefaultlocale` always returns tuple with first element being string. However in some cases it can also return None (e.g. none of  `'LC_ALL', 'LC_CTYPE', 'LANG', 'LANGUAGE'` defined).

**Comment by sergei-dyshel** [comment]
easily fixed by something like https://github.com/sergei-dyshel/git-cola/commit/6239dca226892a08dbf3d56cf2fc02d4734bc232

**Comment by davvid** [comment]
Thanks for the heads-up, yeah we should merge that in. Would you mind prepping a PR with that change?

**Comment by davvid** [comment]
nevermind, I'll cherry-pick that in and adjust the commit message (I just realized it's a private branch with misc tweaks).

Thanks again.
