### ISSUE TITLE
verbose logging

### ISSUE THREAD

**Issue by tylerhjones** [git-cola/git-cola#1236]
Is there a way to add debug output from the tool to know what it is doing? A verbose mode? I havnt seen it in the docs, but the tools seems to start much slower than it used to even for small repos. Im not sure what is causing the startup delay.

**Comment by davvid** [comment]
https://git-cola.readthedocs.io/en/latest/git-cola.html#git-cola-trace

**Comment by davvid** [comment]
Thanks for the heads-up. Let me know if you're able to spot which git command is slowing things down.
