### ISSUE TITLE
Feature Request: Open multiple repos with tabbed interface

### ISSUE THREAD

**Issue by craigwardman** [git-cola/git-cola#1247]
Hello git-cola team,

I think it would be really nice if you could open multiple repositories at once within a single instance of the app and be able to navigate between them using a tabbed interface (i.e. like web browser tabs). 

This is useful when you're working on something that spans across several related repos, or when you want to leave open your most frequently used repos for when you next start the app.

Cheers.

**Comment by davvid** [comment]
This is a pretty sweet idea. There are a few small technical hurdles, but I think they're things we can overcome.

There are a few places where we use global state. A few singletons but over the years we've just about moved all of them into the `context` object that gets passed around.

The `OpenRepo` class in `cola/cmds.py` is what's used to switch repositories when you double click on a repo from the Favorites or Recent widgets. That action switches the repo in-session, and it touches this global state.

The fsmonitor, for example, would need to be able to have multiple instances of it around. These all seem doable.

We could even "fake" it out by remembering the selection and commit messages and just updating the widgets in-place, but a tabbed interface with an actual separate widget hierarchy could be nice.

This probably isn't a simple thing to implement, but we have eliminated many of the technical hurdles that might prevent this from working over the years so it should be doable without a huge overhaul.

I think if we could work in UI elements without them being overly obtrusive then this would be worth it.
