### ISSUE TITLE
MIT License is not included

### ISSUE THREAD

**Issue by dschwoerer** [git-cola/git-cola#1255]
I did notice that polib is bundled in the code, but the LICENSE file is not included:
https://github.com/git-cola/git-cola/blob/e36b578c59ef1e6183f03ac2fb628df5368dcc60/cola/polib.py#L3

Note that there are several MIT variants, so I am not even sure how that file is actually licensed.

**Comment by davvid** [comment]
Thanks for the heads-up. We do have a copy of the license at `extras/polib/LICENSE` but I should probably update the comment there to reference it.
