### ISSUE TITLE
Unable to stage image files.

### ISSUE THREAD

**Issue by glerroo** [git-cola/git-cola#1265]
Current Behavior

Image files is marked as "Untracked" but there's no "stage file" option in its contextual menu. This is similar to #841 but i have not used ```git lfs track '*.png```.

https://user-images.githubusercontent.com/73607126/195667141-11704c6c-6636-49e6-8f06-4ea582b9f356.mp4

Workaround

Double click on the file works

Additional Information

Git Cola version 3.12.0 
    Linux-5.19.0-2-amd64-x86_64-with-glibc2.35 
    Python (/usr/bin/python3) 3.10.7 (main, Sep 8 2022, 14:34:29) [GCC 12.2.0] 
    Git 2.35.1 
    Qt 5.15.4 
    QtPy 2.2.0 
    PyQt5 5.15.7

**Comment by davvid** [comment]
Kindly test the latest from git -- the interactions for image files has been revamped. I made sure that not only are the Stage / etc. context menu actions available, but now the diff editor properly handles image files such as svg files that are also text and can be partially staged just like regular diffs.

Thanks for the heads-up!
