### ISSUE TITLE
diff.ignoreSubmodules isn't respected

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1269]
When `diff.ignoreSubmodules` is set for the repository, the Status widget still displays them. Worse, having the setting turned on breaks the entire Status widget, making diffs not appear when clicking on items.

Please consider hiding submodules from the Status widget if the Submodules widget is opened, respecting the `diff.ignoreSubmodules` setting, or at least sorting them so they don't appear lexicographically mixed with regular files.

**Comment by davvid** [comment]
Thanks again for the heads-up.
