### ISSUE TITLE
Shortcut Key_T applies in commit text field

### ISSUE THREAD

**Issue by lutra** [git-cola/git-cola#1270]
When writing a commit message either in summary field or description and pressing Key_T (even without CTRL) the "Find files" popup appears.
Also, when pressing Key_D inside of "Commit summary" field, cursor jumps into the description field below.

This results in not able to write a commit message with a `t` in it at all, and no `d` in the summary field.

Bug comes up in git-cola v3.12.0 as well as in latest v4.0.3.
OS is Debian GNU/Linux.

**Comment by davvid** [comment]
Thanks for the heads-up. I pushed a commit that I think should address this issue. I wasn't able to reproduce this locally on Debian/sid but I made some defensive changes that might avoid this issue.

Let me know the latest in git fixes it in your configuration.

BTW I have `QT_QPA_PLATFORMTHEME=qt5ct` configured in my environment, and I use the `qt5ct` Qt integration. I also tried it with this setting disabled and wasn't able to reproduce the issue, unfortunately. I am kinda curious to reproduce it in case there's something else I can do to try and replicate it.

**Comment by lutra** [comment]
Installed version 4.0.4. It works, thank you very much!!

**Comment by ab0de** [comment]
> When writing a commit message either in summary field or description and pressing Key_T (even without CTRL) the "Find files" popup appears.
> 
> Also, when pressing Key_D inside of "Commit summary" field, cursor jumps into the description field below.
> 
> 
> 
> This results in not able to write a commit message with a `t` in it at all, and no `d` in the summary field.
> 
> 
> 
> Bug comes up in git-cola v3.12.0 as well as in latest v4.0.3.
> 
> OS is Debian GNU/Linux.

**Comment by davvid** [comment]
Thanks @ab0de . As noted above, the mitigation wasn't released until v4.0.4 so that's probably while you're still seeing it. Thanks for the heads-up.

It would be good to report this to the Debian maintainers. I suspect they're still working on adopting the PEP-518 new-style build system that v4.0 introduced, as none of the versions after v3.12 have landed in debian yet.
