### ISSUE TITLE
gravarar.py: `'QNetworkReply' has no attribute 'NoError'`

### ISSUE THREAD

**Issue by ernstwi** [git-cola/git-cola#1274]
Steps to reproduce (on mac):

1. `brew install --HEAD git-cola`
2. `git cola dag`

Error:

```
qt.tlsbackend.ossl: Failed to load libssl/libcrypto.
Traceback (most recent call last):
  File "/usr/local/Cellar/git-cola/HEAD-c2d742c/libexec/lib/python3.11/site-packages/cola/gravatar.py", line 122, in network_finished
    if reply.error() == QtNetwork.QNetworkReply.NoError:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QNetworkReply' has no attribute 'NoError'. Did you mean: 'error'?
error: git-cola died of signal 6
```

Maybe this is related to recently added support of Qt6? I installed using `--HEAD` to get around the error reported in #1211.

**Comment by davvid** [comment]
Thanks for the heads-up. Please reinstall the latest using `--HEAD`.

The Qt6 support is brand-new so I appreciate the early testing.

**Comment by ernstwi** [comment]
Thank you for the fix, working well. I'll keep using the HEAD version and open a new issue if there are more problems.
