### ISSUE TITLE
Tuxfamily website redirect broken. Needs update to https://git-cola.github.io/  

### ISSUE THREAD

**Issue by michael-delarue-axomic** [git-cola/git-cola#1281]
On tuxfamily there's a link http://cola.tuxfamily.org/ which is a redirect to https://git-cola.github.com/ which is now broken because GitHub no longer supports .com for sites. It should be changed to https://git-cola.github.io/ 

This is referenced in at least one place on the internet  - "appmus" though I'm not sure what that's worth. 

This was probably set up during this ticket.  

https://github.com/git-cola/git-cola/issues/92

**Comment by davvid** [comment]
Wow, blast from the past (2008). Thanks for the heads-up. I had to dig up my credentials and was able to update the the redirects.

**Comment by davvid** [comment]
The http:// URLs seem to get cached by the browser but I confirmed that it's working by going to https://cola.tuxfamily.org/
