### ISSUE TITLE
Diff context menu is broken in latest Git

### ISSUE THREAD

**Issue by living180** [git-cola/git-cola#1287]
In the latest Git version of git-cola, the context menu for the Diff frame is broken and just has two menu items, Copy and Select All (instead of Stage, Launch Editor, etc.).  git blame points to b7d46317b3891176ed7853ea8e2fbf8c71fe95ce which modified the context menu behavior in the `cola.widgets.text.PlainTextEdit` class, from which `cola.widgets.diff.DiffEditor` indirectly inherits.

**Comment by davvid** [comment]
oops, thanks for catching this early. I'll take a look soon.
