### ISSUE TITLE
Option to use system-wide cursor

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#1293]
Previously I used version from ubuntu repository ant there was system cursor used. Lately I installed flatpak version (unfortunately there is no up-to-date maintained PPA with current version) and I've noticed some non-modern, ugly cursor when it hovers a button. Can we remove it or at least have option to disable it?

**Comment by davvid** [comment]
This looks like https://github.com/flatpak/flatpak/issues/709

I don't use flatpaks so I'm unable to test, but if you could kindly share which of the answers in that thread resolve the issue for you then we can update our docs accordingly.

**Comment by jm4R** [comment]
OK, I see this is not the cola issue. I reverted to deb repository version anyway.
