### ISSUE TITLE
This will drop the need of providing the PUBLIC_IP ENV, as it will resolve from other sources automatically.

### ISSUE THREAD

**Issue by ab0de** [git-cola/git-cola#1296]
This will drop the need of providing the PUBLIC_IP ENV, as it will resolve from other sources automatically.

_Originally posted by @aaronsarkissian in https://github.com/WhatsApp/proxy/pull/24_

**Comment by davvid** [comment]
Thanks for the report. I don't understand this issue so I'll close this for now. Perhaps this was intended for a different repo?
