### ISSUE TITLE
Selecting multiple files no longer consistently works on Linux (Wayland?)

### ISSUE THREAD

**Issue by joshuataylor** [git-cola/git-cola#1302]
Using Sway/labwc (Wayland).

When selecting multiple files, only the first file in the list has the action performed, or very rarely all files do.

I took a quick recording:
[Kooha-2023-03-09-15-29-03.webm](https://user-images.githubusercontent.com/225131/223951186-bef0a8e3-0ee1-43e6-8e1a-26ae6c43b8b0.webm)

I've tried with the following versions:
```
Git Cola version 4.1.0 
Linux-6.2.2-1-x86_64-with-glibc2.37 
Python (/usr/bin/python) 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] 
Git 2.39.2 
Qt 5.15.8 
QtPy 2.3.0 
PyQt5 5.15.9 
```

Main branch with both Python 3.10/3.11:
```
Git Cola version 4.1.1.dev189+gc0d10df5 
Linux-6.2.2-1-cachyos-cfs-x86_64-with-glibc2.37 
Python (/home/josh/programs/git-cola/env3/bin/python3.11) 3.11.2 (main, Feb 16 2023, 06:06:48) [GCC 12.2.1 20230201] 
Git 2.39.2 
Qt 5.15.2 
QtPy 2.3.0 
PyQt5 5.15.9 
```

**Comment by davvid** [comment]
Thanks for the heads-up. How are you triggering the actions?

If you're double-clicking then I can imagine that the initial click might actually change the selection, thus leading to the behavior you're seeing. A more stable alternative is to use the `ctrl-s` hotkey to stage/unstage stuff. That should keep the selection without any timing issues.

Let me know if that's related or not.
