### ISSUE TITLE
git-cola 4.2.0 "Toolbar style" no longer works

### ISSUE THREAD

**Issue by lah7** [git-cola/git-cola#1307]
Since upgrading to git-cola 4.2.0, custom toolbars are no longer using the "Toolbar Style" preference.

![Screenshot_20230326_174015](https://user-images.githubusercontent.com/13032135/227790609-88ad5edf-ae7c-4256-9a81-036c8cf8bda0.png)

All toolbars seem to be stuck with "Text Beside Icon" and seem a bit different compared to earlier versions (for example, the padding/shape is different to other Qt applications). The application isn't reading the global settings (in this case, from KDE) either.

| 4.1.0 | 4.2.0 |
| --- | --- |
| ![Screenshot_20230326_185348](https://user-images.githubusercontent.com/13032135/227794645-9d3562ff-ddb5-4972-9d60-7ea22f0d43b5.png)  | ![Screenshot_20230326_185423](https://user-images.githubusercontent.com/13032135/227794671-61ff8ca5-5e18-4fd3-b0e2-2e3e0e401e84.png)

### The Culprit
The commit affecting this is 796f8ce0b07b184de9848b912e9d0ee748840ba3. Reverting it fixes the problem.

Not sure what that change was trying to fix, as I haven't witnessed any truncated labels in a `QAction` to make them display "..." unexpectedly. Ideally, we can go back to the standard `QAction`, and see if there is an alternate solution to what this commit was trying to fix.

### Environment

git-cola 4.2.0 (from AUR)
Arch Linux
KDE Plasma 5.27.3
Qt 5.15.8
Python 3.10.10

**Comment by davvid** [comment]
Thanksf or narrowing it down to that specific commit. That commit was mostly cosmetic so I'll consider reverting it and seeing if there's another way to handle the truncated text (it's only visible in specific configurations / font sizes).

Sorry 'bout that.

**Comment by lah7** [comment]
Out of interest, which theme, font, OS or Qt configuration causes the truncated text? I must say I haven't seen truncated text on toolbar items under KDE/Breeze, they just disappear into a ➡️  button, even if the text is large.

Technically, the `QToolButton` _could_ have its `toolButtonStyle` set to match, but I think cosmetically, it might still look a bit naff on some themes -- like Breeze here -- hence I'd be in favour of the standard `QAction`.

**Comment by davvid** [comment]
I was seeing it when I had `QT_QPA_PLATFORMTHEME=qt5ct` set in the environment on debian/testing's version of gnome. I think this is mostly my problem and unsetting the variable fixes the issue so I've reverted it.

Thanks for the heads-up!
