### ISSUE TITLE
git cola is freezing in windows

### ISSUE THREAD

**Issue by lenkapolaskova** [git-cola/git-cola#1310]
Almost every operation gets git cola to freeze and not responding like a window opens somewhere and is not visible or obtainable. I used version 4.1.0 and I moved to 4.2.1.

**Comment by theoHC** [comment]
I am experiencing the same issue. The only functions which reliably work without freezing are staging and committing.

**Comment by OriShalhon** [comment]
@theoHC does this still occur? care to share in what instances so I could try looking into it ?
