### ISSUE TITLE
Local Set-up

### ISSUE THREAD

**Issue by turingnixstyx** [git-cola/git-cola#1311]
Please forgive me for asking this possibly redudandant question but can you please tell me the steps to successfully establish a dev-environment  in your local for git-cola

**Comment by davvid** [comment]
Sure thing. The short answer is that if you install git-cola's requirements (Python + PyQt5 or PyQt6) then you're ready to go.

Installing dependencies into a virtualenv is a safe route:
https://github.com/git-cola/git-cola/#install-into-a-python-virtualenv-from-source

If you're on Linux then installing PyQt5 through your package manager is the ideal approach. If you do that then you can run `./bin/git-cola` directly from the source tree and things will "just work".

The core step is to run the Python interpreter you plan to use and try running this code:

```
python3 -c 'from PyQt5 import QtCore'
```

If that snippet succeeds without errors then you're pretty much ready to go and you should be able to run `./bin/git-cola` as-is from the source tree.

You don't have to install git-cola to use it or to develop it. You just need a clone of the repo. It's designed to be run in-place from the source tree.

Let me know if you need any help. Feel free to comment on this issue even after it's closed -- we can keep pushing on it.
