### ISSUE TITLE
1.25 dpi scaling

### ISSUE THREAD

**Issue by orazdow** [git-cola/git-cola#1313]
I wanted to add a feature request for 1.25 high dpi scaling, On my 1900x1200 display on Linux Mint 1x is a bit too small, but 1.5 is too large. The desktop environment is currently on 125%, so I think this would be good to add.

**Comment by davvid** [comment]
That'd be great to add. Please take a look at `cola/hidpi.py` -- all the modes are defined there.

**Comment by orazdow** [comment]
Will do. I saw that after I posted, it's surprisingly clear.

**Comment by akontsevich** [comment]
Where `QT_SCALE_FACTOR` is stored? How to set it manually as with 1.25 "Close" button is not visible - can't close dialog and save settings?

**Comment by davvid** [comment]
@akontsevich the setting is stored in your `~/.gitconfig` (or `~/.config/git/config` if you're using the new-style config path).

The value is the `git config cola.hidpi` value. You can use `git config --global --unset cola.hidpi` to unset it, or find the `hidpi` value under the `[cola]` section in that file and delete it.

If you're unable to see the Close button, resizing the window to be shorter should make it visible.

If you're on Linux, holding the "Windows" key and dragging with the middle mouse button (wheel button) in the dialog should resize it, and dragging with the left mouse button while the "Windows" key is pressed should move the dialog. These are Gnome shortcuts; may not work in other window managers.

Nonetheless, if you press "Escape" it should close the dialog and remember your settings.

**Comment by akontsevich** [comment]
On escape settings not saved.

> [@akontsevich](https://github.com/akontsevich) the setting is stored in your `~/.gitconfig`

Yep, this is it - thanks a lot. However think more natural to store it in `~/.config/git-cola/settings`.
