### ISSUE TITLE
file(s) fail validity check when building

### ISSUE THREAD

**Issue by atomGit** [git-cola/git-cola#1315]
building with pamac on manjaro...

```
Building git-cola...
==> Making package: git-cola 4.2.1-3 (Fri 02 Jun 2023 01:48:26 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found git-cola-4.2.1.tar.gz
  -> Found 0001-Unvendorize-polib.py.patch
==> Validating source files with sha256sums...
    git-cola-4.2.1.tar.gz ... FAILED
    0001-Unvendorize-polib.py.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
Failed to build git-cola
```

**Comment by davvid** [comment]
I don't know anything about manjaro but this route should find someone able to update the packaging:

https://forum.manjaro.org/t/best-practices-for-informing-a-maintainer-of-a-new-version-of-a-package-in-manjaros-repositories/18521

My theory is that the package is pulling tarballs from github (or elsewhere?) and maybe github isn't deterministically producing the same byte-for-byte tarball as they did before, even though the contents are the same.

This came up on the git mailing list a short while back in the context of `git archive`. I wouldn't be surprised if this failure is related.

For context, please read this lengthy thread: https://public-inbox.org/git/a812a664-67ea-c0ba-599f-cb79e2d96694@gmail.com/

Thanks for the heads-up ~ we don't maintain the manjaro packaging so kindly report this to the package maintainers.
