### ISSUE TITLE
slow diff view on jupyter files, freezes UI for minutes

### ISSUE THREAD

**Issue by nevion** [git-cola/git-cola#1316]
So jupyter files get embedded images in them for things like graphs but otherwise are plain text files (json).  When using git cola and changes like an image update occur, it can take about a minute or two for a jupyter document  with many images to render the diff in the UI - I don't think the diffs themselves are reasonable examples to try and render because it's base64 encoding for images.  Interestingly enough git-diff isn't the problem, with GIT_COLA_TRACE it is somewhere between 250-600ms for the actual git diff to complete - so the problem is in ui land.

If this can't inherently be made faster, maybe when the diff is above a certain megabyte threshold it should be treated like  a large binary file's diff which is to say don't try to render it, and very importantly don't freeze the UI.  I find half the time the diff view gets rendered is because I staged or unstaged something else adjacent to a jupyter file.

Any other ideas on how to deal with fairly large text json blobs / ipynb files?

**Comment by davvid** [comment]
Do you have an example repo I can clone to help reproduce the issue?
