### ISSUE TITLE
Version identification

### ISSUE THREAD

**Issue by tester0077** [git-cola/git-cola#1321]
Being a newb to both Linux & git, I am very confused by the git-cola version information.
The GitHub information leads me to believe that the latest version is 4.2.1 as of Mar 31 assumed to be 2023
But when I clone the repo and run the git-cola python file, its about box version tells me I am running 3.12.0 with the latest copyright date of 2020

**Comment by davvid** [comment]
Are you launching it as `./bin/git-cola` from the source tree? That's rather surprising if so.

One way to explain the behavior you're describing would be if an older version is installed through your OS / package manager (apt?) and you're running that version instead.

Another thing to check would be the output of `git log -1` but I doubt that'd be the cause.
