### ISSUE TITLE
'Fetch' action keeps failing

### ISSUE THREAD

**Issue by kanunnikau** [git-cola/git-cola#1339]
Hello. I have a weird issue on OpenSuse Tumbleweed (git-cola version 4.3.0-1.1).

The 'Fetch' action keeps failing with:
```
"git fetch" returned exit status 128
fatal: refusing to fetch into branch 'refs/heads/release' checked out at %SOME_LOCAL_CHECKOUT_FOLDER%'
fatal: the remote end hung up unexpectedly
remote: 
remote: ========================================================================
remote: 
remote: rpc error: code = Canceled desc = user canceled the fetch
remote: 
remote: ========================================================================
remote: 
```
The thing is that:
- "git fetch" from a terminal works just fine. The very first time it asks for the corresponding ssh key password (through the terminal prompt), then it just fetches immediately;
- other git GUIs work fine. For example, gitg reports "everything is up to date";
- other actions in git-cola work just fine. I can pull, push, etc.

I have `wish` installed. I have `SSH_ASKPASS` set to `/usr/libexec/ssh/ssh-askpass`. 

I see that there is *no* file `/usr/share/git-cola/bin/ssh-askpass`. There is `/usr/lib/python3.11/site-packages/cola/bin/ssh-askpass`, though. Not sure whether it should be this way.

How else can I debug this issue? Is it some local setup problem?

Thank you.

**Comment by davvid** [comment]
Thanks for the heads-up. I'll take a look -- it's possible that we didn't correctly adjust where it finds its private bin/ commands when we moved those parts into the ite-packages area.

**Comment by davvid** [comment]
`refusing to fetch into branch 'refs/heads/release' checked out at ...` might be related.

When you run the Fetch dialog, do you hit the "Fetch" button after clicking on a remote only? I'm curious whether you've click on a local branch (on the right-hand side) since that could lead to it trying to update a local (already-checked-out) branch with the fetch.

Another thing to help debug is to `export GIT_COLA_TRACE=1` in your environment before launching cola. That'll get it to print out `git` commands as it runs them. We can then take a look at the `git fetch` command that it runs when you click the Fetch button.

**Comment by kanunnikau** [comment]
Hello
I cannot reproduce the original issue any more :)
All fetches in the root repository complete successfully.

> When you run the Fetch dialog, do you hit the "Fetch" button after clicking on a remote only? I'm curious whether you've clicked on a local branch (on the right-hand side) since that could lead to it trying to update a local (already-checked-out) branch with the fetch.

I was selecting a local branch (which would also select a corresponding remote branch). Today such a thing is working in the main repo.

I did find a problematic fetch — in a submodule:
- open main repo (all fetches work fine),
- from git-cola open 'Submodules' panel and double-click on a submodule,
- fetch from just remote succeeds,
- fetch from a remote branch succeeds,
- fetch with both local and remote branches selected fails with "exit status 1".

```
From <repo_address>
 ! [rejected]        release    -> release  (non-fast-forward)
 = [up to date]      release    -> origin/release
```
As far as I can see in the logs there are 3 commands ran:
```
# 1.146s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false fetch --verbose --tags --prune origin release:release
# 0.008s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
# 0.005s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --symbolic-full-name HEAD
```

> Another thing to help debug is to export GIT_COLA_TRACE=1 in your environment before launching cola.

I didn't think to look this up yesterday. Would have given those curious details I was wondering about...
