### ISSUE TITLE
DAG in Flatpak

### ISSUE THREAD

**Issue by mbnoimi** [git-cola/git-cola#1341]
I tried to use Git-Cola flatpak version because Ubuntu repository has an outdated version (3.12.0). But DAG is unavailable in flatpak.

Is there any trick to enable DAG in Git-Cola flatpak version ?

**Comment by fugenkleber** [comment]
You could install the current git-cola release as python application via pip/pipx. I tried this on Xubuntu 23.04:
`sudo apt install pipx`
`pipx install git-cola`
`pipx ensurepath`

**Comment by mbnoimi** [comment]
> `pipx install git-cola`

I never used `pipx` before. I read [this warning](https://github.com/git-cola/git-cola#installation) so I didn't install it using `pipx`

**Comment by davvid** [comment]
Please open an issue on https://github.com/flathub/com.github.git_cola.git-cola instead.

The flathub packaging is a separate project and I don't use flatpaks so I won't be able to help you.

You're better off not-installing and running from source (that's what I do), installing into a virtualenv (or perhaps pipx as described in this thread). Disclaimer: I don't use pipx so I can't vouch one way or another.

For installing from source, if the instructions ever become outdated the basic idea is to run `./bin/git-cola` and then use `apt install` to install system packages until all of your imports work.

Debian/testing already has a newer version than what you're using (4.1.0 at time of this writing) but not quite v4.3.x new so virtualenvs or something like them are probably your best option if you want a new version.
