### ISSUE TITLE
Avast Is reporting New Version installer as a virus

### ISSUE THREAD

**Issue by Artimidorus** [git-cola/git-cola#1346]
I'm sure this is a false positive. Attached are the details reported.
![Capture](https://github.com/git-cola/git-cola/assets/6559330/ad72e259-0d49-4c7f-8005-3bfb62c0d511)

**Comment by davvid** [comment]
I don't use avast so I don't have time to submit false positives to them, but if you have a moment you might be able to alert them to the situation.

https://forum.avast.com/index.php?topic=234761.0

cheers
