### ISSUE TITLE
clutter in context menu

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1347]
Since the recent addition of 'edit hunk before staging/reverting', the context menu is pretty cluttered. As an existing git-cola user it's difficult for me to locate the option before losing concentration.

![image](https://github.com/git-cola/git-cola/assets/1896811/3bfcb6b1-d548-4fe2-98a8-aa8609dd7f31)

The order is now logically a bit different between the Status area and Diff area which is also confusing for me.

Please consider adding different icons, spacers, or reordering the options to make it more clear as to what to click within a split second.

I'm specifically using dragging using the mouse and then right-clicking rather than using the keystrokes, because accidentally tapping S instead of Ctrl+S leads to ruining all the work. As an unrelated issue, CTRL+U for revert can't be used with the left hand during keyboard + mouse operation so it's difficult to actually use keyboard shortcuts in the first place.

**Comment by sthalik** [comment]
Here's an even better idea.

Allow disabling 'Stage/Revert file' from right-click menu within the Diff window. Leave it as-is in the Status menu.

**Comment by davvid** [comment]
Thanks for the usability feedback on these recent additions. I'll plan to mock up some ideas and work with you to get this to a better place before the next minor release.

**Comment by davvid** [comment]
I reworked the menu to group the "Edit and ..." actions separately from the older options. Let me know what you think -- this should make things easier to spot now.

This also makes the Diff context menu more closely match the Status context menu.

I have implemented this, but I'm open to adding `ctrl-shift-r` as an alias for the `ctrl-u` revert hotkey if you think that'd be helpful as a left-handed shortcut ~ just let me know.

`alt-r` is currently used for rebase and "revert" is a bit destructive so it's good for it to require two modifiers IMO. What do you think?

**Comment by sthalik** [comment]
> I reworked the menu to group the "Edit and ..." actions separately from the older options. Let me know what you think -- this should make things easier to spot now.

It's better overall but now selecting lines to unstage is is much different from all the others.

> alt-r is currently used for rebase and "revert" is a bit destructive so it's good for it to require two modifiers IMO. What do you think?

Alt+R seems safe enough since other keyboard shortcuts tend not to use either Alt or R.

**Comment by davvid** [comment]
Thanks! I added the Alt+Shift+R hotkey and further refined the menu for unstaged lines. I was mostly noticing an issue in Amend mode, but it should be better all-around now (I hope) when unstaging.
