### ISSUE TITLE
dev: replace use of "pylint" with "ruff"

### ISSUE THREAD

**Issue by davvid** [git-cola/git-cola#1353]
Pylint is slow.

[Ruff](https://docs.astral.sh/ruff/) is fast.

Update the CI, Makefile and garden workflow scripts to use `ruff` instead of `pylint`.

Code changes may be required in order to remove old pylint suppressions (`pylint: disable=...`) and add new ones for Ruff as part of this change.

**Comment by OriShalhon** [comment]
@davvid need any help with this development?

**Comment by davvid** [comment]
You're very kind. Sure thing, that'd be super helpful if you'd like to take a stab at it.

**Comment by OriShalhon** [comment]
@davvid Currently pylint evaluates code against python 3.6 :
`# Specify what version of Python to evaluate code against.
py-version = 3.6`

[ruff supports target python version >= 3.7](https://docs.astral.sh/ruff/settings/#target-version)

any thoughts?

**Comment by davvid** [comment]
Ruff checking against a 3.7 baseline should be just fine.

If ruff finds code that it recommends changing to use 3.7-only features then we'll evaluate that code on a case-by-case basis. It's okay if we have to suppress a few minor warnings to continue supporting users on older platforms for now.

**Comment by yaboytabby** [comment]
hello! im new to open source and would like to take a crack at this; im nervous and excited.

**Comment by davvid** [comment]
Hi @yaboytabby definitely just go for it. I've intentionally not implemented this since folks have mentioned interest.

In case you're curious, I already implemented this in a different project. You can take a look at the `pyproject.toml`, `setup.cfg`,  `pytest.ini` and `tox.ini`-related changes that were made over there for comparison:

https://github.com/jsonpickle/jsonpickle/pull/475

**Comment by yaboytabby** [comment]
okay. ill see what to do. im not great at python but ill try my best.

**Comment by miszczes** [comment]
I would also suggest adding ruff screening against the changes made in PR after any push is done. This can be easily implemented through ci.yaml

**Comment by davvid** [comment]
Please do. I don't really care much about the specific pylintrc settings as long as the ruff is configured so that its checks pass.

**Comment by yaboytabby** [comment]
heya! just want to say; i don't think im the best fit for this project as of yet. too many thing so don't understand, and i think its in mine and the project's best interest if i get some more skill before taking something such as this on

**Comment by davvid** [comment]
It's all good. Thanks for the heads-up. If you're still looking to learn, `git log -p` is your friend. cheers!
