### ISSUE TITLE
Checkout branch dropdown re-drops after selcting branch

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#1360]
In Branch → Checkout… dialog, there is this drop-down list. After selecting item the list hides but it re-opens immediately. It's very annoying as it covers "Checkout" button!

History:
Version 4.1.0 works good
Version 4.2 has different bug: empty list shows at start
Version 4.2.1 … 4.4.0 has described bug

Info: Tested on Linux

**Comment by davvid** [comment]
Thanks for the heads-up. This should be fixed in v4.4.1 (just released)
