### ISSUE TITLE
unintuitive context menu option(s)

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1362]
Hey,

There's another thing with the context menu that's a problem for me.

![image](https://github.com/git-cola/git-cola/assets/1896811/2e275dfe-74a8-4a87-a195-89e60a02dd3c)

If there are selected lines, please don't provide the "Unstage" (whole file) option as the very first one.

Or put it to number 2 on the context menu (and possibly say "Unstage the entire file" in it). Whichever you prefer, just as long as it reduces the occurences of unstaging the entire file by accident.

**Comment by sthalik** [comment]
FWIW, this seems to do the job: 

```patch
diff --git cola/widgets/diff.py cola/widgets/diff.py
index 40200b42..104c1c56 100644
--- cola/widgets/diff.py
+++ cola/widgets/diff.py
@@ -976,7 +976,7 @@ class DiffEditor(DiffTextEdit):
         add_action = menu_actions.append
         edit_actions_added = False
 
-        if model.is_stageable() or model.is_unstageable():
+        if (model.is_stageable() or model.is_unstageable()) and not self.has_selection():
             if (model.is_amend_mode() and s.staged) or not self.model.is_stageable():
                 self.stage_or_unstage.setText(N_('Unstage'))
                 self.stage_or_unstage.setIcon(icons.remove())

```

**Comment by davvid** [comment]
Thanks again for the sug. The Diff widget's right-click menu now displays the selection and hunk staging actions before any of the whole-file staging actions.
