### ISSUE TITLE
Suppress "Remote Messages" Popups

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#1363]
I just installed git-cola version 4.4.0 earlier today, and I've found that it has added an annoying popup message when I do certain operations like branch checkouts (example pictured below).  I've looked through the settings window and there does not appear to be any way to disable this.  Could some way be added to disable this popup window?

![image](https://github.com/git-cola/git-cola/assets/548168/dd2cf513-9e16-40c7-9b2d-d23f6fd69ce7)

**Comment by davvid** [comment]
I'm slightly surprised that you mention checkout because these are only supposed to appear in the Fetch, Push and Pull dialogs.

Those dialogs have a checkbox to disable these messages, and I thought it was disabled by default. I'll take a look to see if there's something I missed.

**Comment by davvid** [comment]
Yep, looks like it got wired up a little too deeply when I merged in the remote dialogs feature. It's now fully opt-in and enabled by enabling the "Remote Messages" setting in the Push and Pull dialogs. The Branches widget uses the settings defined there for those two actions.

Thanks for the heads-up!
