### ISSUE TITLE
documentation request: can the Linux installation instructions be improved?

### ISSUE THREAD

**Issue by pirlite2** [git-cola/git-cola#1364]
I would like to install a more recent version than my Ubuntu repo provides (currently version 3.12.0). But the Linux installation instructions exhibit classic 'expert bias'! They assume that everybody is a Python expert and comfortable with virtual environments - an exclusively(?) Python concept. (Although I sometimes use  Python as a scripting language, I am principally a C++ programmer!)

For example, "If you already have the qt5-devel package installed then you can lookup its version so that your virtualenv can install a compatible version of PyQt using qmake:" Right. But supposing I do not have this package installed. What do I do? I am guessing 'pip install qt5-devel' but what about the other dependencies and all the other issues?

Can the installation instructions be improved to explain _exactly_ what to to, step-by-step, to install the latest version from PyPi under the assumption that not everybody is a Python developer?

(Sorry to sound grumpy, but so much excellent open source software is let down by deficient documentation.)

**Comment by davvid** [comment]
Thanks for the sug. Please take a look at the updated README and let me know what you think. I added a dedicated section that explains which packages to install using `apt` for Debian / Ubuntu systems.
