### ISSUE TITLE
Request: A tar release

### ISSUE THREAD

**Issue by RandallFlagg** [git-cola/git-cola#1366]
Can you please create a tar.gz/tar.xz release in addition to what you have in the packages?
That way it will be usable on any distro regardless if the package exists or not.

thanks

**Comment by davvid** [comment]
I'm not particularly opposed to the idea, but I want to mention that tarballs are already available from various trusted sources.

All of the tagged releases have tarballs associated with them:

* Gitlab: https://gitlab.com/git-cola/git-cola/-/tags

* Github: https://github.com/git-cola/git-cola/tags

* Pypi: https://pypi.org/project/git-cola/#files

Let me know whether or not these suite your needs. If it'd help, we can link to these from the README if that'd help make them more discoverable ~ just let me know.

Cheers

**Comment by RandallFlagg** [comment]
Thanks.
I found the way to run it by cloning and running from the bin directory. I think it should be more clear that this is the way to run the project as I was expecting the release to be in the release section.

Maybe it would be better to explicitly write it in the README or on the [download page](https://git-cola.github.io/downloads.html) as currently it is under the source part.

thanks again
