### ISSUE TITLE
The title bar (or something else) should show the name of the file currently selected

### ISSUE THREAD

**Issue by albertvaka** [git-cola/git-cola#1367]
When the paths are long, there's no way to know which file is being viewed just looking at the selected entry in the sidebar. This could be easily solved by showing the filename of the currently selected file in the title bar or some other place in the window.

Eg: What's the name of this file?

<img width="1246" alt="Screenshot 2023-12-27 at 12 10 08" src="https://github.com/git-cola/git-cola/assets/980842/2e7eab8f-c5b9-4bf5-af5e-8f8fd3517e9e">

**Comment by davvid** [comment]
Thanks for the sug!

Please try the latest from git. There's now a "Show filenames" option in the diff widget's options menu (the sprocket in the upper-right corner of the widget).
