### ISSUE TITLE
Wrong name for toolbar tool

### ISSUE THREAD

**Issue by pkzc** [git-cola/git-cola#1371]
In Git Cola version 4.3.2 , in the Commit group of the list of the toolbar operations there is a tool named "Stage All Untracked", which in my experience in fact stages all modifieds.

I am happy with the actual behavior, but it would be nice to read in the tool tip "Stage All Modified".

**Comment by davvid** [comment]
Thanks for the heads-up! I'll get this patched shortly (before the next upcoming release).

**Comment by davvid** [comment]
nterestingly, I wasn't able to reproduce this behavior.

The "Stage All Untracked" action is only staging new (untracked) files, as originally intended. I just added a new "Stage Changed Files To Commit" action to handle staging just modified files. That new action should do what you're describing.

I'm kinda surprised that you're seeing different behavior. Here's where the two commands are registered. They're definitely hooked up to the correct commands at this level:

https://github.com/git-cola/git-cola/blob/a290ba51fa81db4d75ff5ef4e05cb4beaed568e7/cola/widgets/toolbarcmds.py#L180

Let me know if the latest version behaves differently. In theory it shouldn't, but we'll see. Thanks for the heads-up.

**Comment by pkzc** [comment]
You are right, it's a bit more complicated, after some experiments I can report this:

I have in the [gui] section of the git config file this:
**displayuntracked = false**
When I comment this out, then git-cola shows the untrackeds, and the "Stage All Untracked" stages exactly the untrackeds, the modified ones are left in place.

However,  when I put back that line in the config, I get back the behavior that I originally reported.

**Comment by davvid** [comment]
Alrighty, that totally explained it. Thanks for the tip about `gui.displayuntracked`. That setting caused the tool to go into a fallback code path that stages all files (because the list of files to stage will always be empty), which is obviously something we don't want to do.

This has been corrected.

**Comment by pkzc** [comment]
> The "Stage All Untracked" action is only staging new (untracked) files, as originally intended. I just added a new "Stage Changed Files To Commit" action to handle staging just modified files. That new action should do what you're describing.

Just one more thing: I would suggest to call the new operation "Stage All Modified" instead of "Stage Changed Files To Commit" because
1. it follows the pattern of "Stage All Untracked" making it easier to comprehend,
2. in the GUI, the files affected by the operation are listed under the title "Modified" as shown in the attached picture.

![Screenshot at 2024-01-04 09-56-29](https://github.com/git-cola/git-cola/assets/23018794/9df9e011-3277-4b17-9ab4-bcd95e967f61)
