### ISSUE TITLE
How does cola start on Windows?

### ISSUE THREAD

**Issue by orazdow** [git-cola/git-cola#1372]
The reason I'm asking is there is a minor annoyance that child processes on windows can't be disowned but when using the START command there is an extra console window started by the pyinstaller program git-cola.exe which I guess is a launcher?

It seems like there should be a way launch git-cola on windows through the terminal without the extra launcher terminal. 

Is it correct that that's what the exe does? I'm wondering where in the source I could try changing this to see if there's a better way to launch on Windows.

![Screenshot 2024-01-11 182040](https://github.com/git-cola/git-cola/assets/10949483/386a5a0b-0cf6-4da8-9310-b1048f45a873)

**Comment by davvid** [comment]
The installer is created by running `./contrib/win32/run-pynsist.sh` which uses [pynsist](https://github.com/takluyver/pynsist) against our [pynsist.cfg](https://gitlab.com/git-cola/git-cola/-/blob/main/pynsist.cfg) file to generate the installer.

The launcher icons are actually generated by `pynsist` using the metadata in there so it might actually require changing `pynsist` itself to change the behavior.

In case it helps, there's a [contrib/win32/pynsist-preamble.py](https://gitlab.com/git-cola/git-cola/-/blob/main/contrib/win32/pynsist-preamble.py) file which gets injected into each of the `pynsist`-generated entry points.

We've tried to hide console windows in the past, but those for the `git` commands themselves. [Here's a link to that code](https://gitlab.com/git-cola/git-cola/-/blob/main/cola/core.py?ref_type=heads#L217) in case it helps at all.

**Comment by orazdow** [comment]
Hm ok, it says [here](https://pynsist.readthedocs.io/en/latest/cfgfile.html) there's a `console=false1 option in the cfg to run using pythonw.exe. I'm not sure when I would get around to trying to build with that option though, so feel free to close. It seems like a simple thing to try though so I may try.

**Comment by davvid** [comment]
Awesome! Thanks for pointing out `console = false`. I'm going to go ahead and add that to our `pynsist.cfg` file. There shouldn't be any downsides.

We should also upgrade the pinned dependency versions while we're in there.
