### ISSUE TITLE
Version 4.5.0 Wont start after update

### ISSUE THREAD

**Issue by Artimidorus** [git-cola/git-cola#1376]
On windows 10 I updated from version 4.3.2. the new version wouldn't launch no error code. also no GUI. I uninstalled via the uninstaller installed to a new directory same problem program wont open. no error message. I installed 4.4.1 after uninstalling 4.5.0 and it works with version 4.4.1. How can I give more helpful information to help resolve this issue?

**Comment by pkzc** [comment]
Same issue here, except when started from a terminal, it reports "ImportError: No Qt bindings could be found".
In pkgs\PyQt5\__init__.py there are references to \Qt5\bin directory and to Qt5Core.dll file in that directory, but they are missing under the Qt5 directory.
I guess some packages are missing from the distribution, and the missing part must be quite big at that: the zip distribution file of 4.4.1 was 39.6 MB, while the 4.5.0 file is a mere 23.8 MB.

**Comment by davvid** [comment]
Thanks for the heads-up. It's good to know that this is just an issue with the installer. The main things that changed from last time are in 41f63a8f79f560095eda4f29f3e1f250e1504afb

```
diff --git a/pynsist.cfg b/pynsist.cfg
index 4d14f101..214913f0 100644
--- a/pynsist.cfg
+++ b/pynsist.cfg
@@ -14,7 +14,7 @@ console=false
 # nsi_template=contrib/win32/pynsist-template.nsi
 
 [Python]
-version=3.7.9
+version=3.11.7
 bitness=64
 include_msvcrt=true
 
@@ -47,11 +47,11 @@ extra_preamble=contrib/win32/pynsist-preamble.py
 [Include]
 packages=cola
 pypi_wheels= packaging==21.3
-    PyQt5==5.14.2
-    PyQt5-sip==12.7.2
-    pywin32==304
-    QtPy==2.0.1
-    send2trash==1.8.0
+    PyQt5==5.15.10
+    PyQt5-sip==12.13.0
+    pywin32==306
+    QtPy==2.4.1
+    send2trash==1.8.2
 files=share/
 exclude= pkgs/PyQt5/Qt/bin/Qt5Bluetooth.dll
     pkgs/PyQt5/Qt/bin/Qt5DBus.dll
```

We upgraded to Python 3.11 (instead of 3.7) and updated the PyQt version. In theory it could have been either of those two changes.

Does anyone here have a Windows machine where they can run `./contrib/win32/run-pynsist.sh` (after installing pynsist)? That's the script that builds the installer.

I'll start looking into this from the installer side to see if there's something else in the build process that might've changed.

**Comment by davvid** [comment]
I see you're on Windows 10. These issues might be related:
https://github.com/takluyver/pynsist/issues/195
https://github.com/takluyver/pynsist/issues/176
https://github.com/takluyver/pynsist/issues/225

The last issue is interesting ~ it contains a compatibility matrix that suggests that maybe I should stick to Python 3.7.9 (for now).

It's also noteworth that Python 3.8 and newer dropped support for older (Vista) Windows versions. I'm going to try the versions listed there.

**Comment by davvid** [comment]
I uploaded a new installer. The file size is much larger now and I've pinned down to previously-known good versions so this should do it for now. I'll probably try Python 3.8 later, but for now we should be good to go.

Please test out the latest installer and let me know if this is all good on your end now.

**Comment by pkzc** [comment]
It works for me, too, thanks.
