### ISSUE TITLE
Feature Req: Stage single lines within a diff hunk

### ISSUE THREAD

**Issue by teymuri** [git-cola/git-cola#1381]
I am not sure if this is possible in GC, but it would be very useful to be able to just do Stage some Lines For Commit (from all changed lines). Please close this, if this already is supported.

Thank you

**Comment by davvid** [comment]
We've had this feature for a very long time. Git Cola was actually the very first Git UI to have this feature back in 2007.

Use `alt-j` and `alt-k` to select the file.

Use `ctrl-j` to highlight the diff editor and use `j` and `k` to move around. Hold shift to select lines while moving and hit `s` to stage those lines. The same hotkeys work for staged files -- `s` will unstage lines when the content is staged.

You can also use `ctrl-u` to Revert lines from a modified file. It'll revert the entire hunk if nothing is selected. It'll revert just the selected lines when you have specific lines selected.

**Comment by teymuri** [comment]
Great! Many thanks!
