### ISSUE TITLE
git-cola died of signal 11

### ISSUE THREAD

**Issue by gerkereitz** [git-cola/git-cola#1389]
Hello,

I have been setting up a Mac mini for development. I have installed brew and used it to install git-cola.

In the beginning this worked fine. However now when I want to open git-cola using the terminal, it crashes with the message "error: git-cola died of signal 11":
![image](https://github.com/git-cola/git-cola/assets/58658920/7d0f65ca-7862-4a3c-9002-458762781071)

When starting git-cola while not being in a repository folder, it works fine:
![image](https://github.com/git-cola/git-cola/assets/58658920/d73d34d8-5828-450c-bda2-aae938b7315b)

It only happens when navigating to a repository folder using the git-cola screen or starting git-cola while already being in a repository folder.

I have tried completely reinstalling and following the commands of the README, but with no success:
``brew reinstall pyqt@6``

and

    # update homebrew
    brew update

    # uninstall git-cola and its dependencies
    brew uninstall git-cola
    brew uninstall pyqt5
    brew uninstall sip

    # re-install git-cola and its dependencies
    brew install git-cola

Is anyone familiar with this issue? Can't really find anything about it.

**Comment by davvid** [comment]
Sorry you ran into that. Signal 11 is a segfault and that *usually* suggests that there's something funky with the homebrew-provided environment or something along those lines.

Narrowing it down can be a little tricky, but the first thing I would try would be to clone the repo and run `./bin/git-cola` inside the repo. That might point towards a clue.

Once you have that you can also see the git commands that are getting executed by running `env GIT_COLA_TRACE=1 ./bin/git-cola` in case we can find a case where a specific git command is leading to errors.

Another thing you can try doing is running `python3` and inside the interpreter run these commands to see what happens:

```python
from qtpy import QtWidgets
app = QtWidgets.QApplication([])
```

If that succeeds without issues then we know that it's not related to Qt / PyQt.

Did you maybe recently upgrade homebrew or your macOS version, BTW? That's usually what triggers this kinda stuff since Apple does tend to break userland pretty often.

**Comment by gerkereitz** [comment]
Thank you for the response @davvid!

When cloning the repository and running git-cola locally, it also gives a segfault:
![image](https://github.com/git-cola/git-cola/assets/58658920/06e43ea4-2192-4fe6-afd0-c4fac04cff26)

Running git-cola with the trace option gives me the following:
![image](https://github.com/git-cola/git-cola/assets/58658920/da7bb8b8-9137-4c1e-b305-08136d6673fa)

Running the qtpy commands in a python3 session shows no errors and seems to work as expected:
![image](https://github.com/git-cola/git-cola/assets/58658920/06d8aaa8-bdc9-483d-915f-d54060edf5f9)
![image](https://github.com/git-cola/git-cola/assets/58658920/a41605da-bf36-43da-bf1e-88e92413a3b0)

I updated my Mac to the latest version before installing homebrew and git-cola, so that shouldn't be it. I did run the brew upgrade and update command at some point after already having installed git-cola. However, it still worked fine for a little while after that. Following the guide in your README for fixing git-cola after updating did also not work.

Any other suggestions?

**Comment by davvid** [comment]
One  way to to debug this would be to start adding `return` calls into the `cola/main.py` logic to see if you can find the line of code that's causing the error. That said, segfaults are usually something like old python modules sitting somewhere unexpected.

Have you ever run `pip install` outside of a virtualenv? That can sometimes leave cruft in `~/.local/lib/python*` that sometimes has to be removed (especially .so files).

The are other directories on macos as well -- run `python3 -c 'import sys; print('\n'.join(sys.path))'` to see the locations where python is looking for modules. The paths to check for cruft are typically in your home directory and similar.

I'm wondering whether installing into a virtualenv will make things work in your setup. I'd suggest trying this first. Run this to install cola into a virtualenv called "env3":

```bash
python3 -m venv env3
./env3/bin/pip install PyQt5
./env3/bin/pip install git-cola

# Now launch it
./env3/bin/git-cola
```

If that works then it suggests that the outer python environment has some busted modules that need to be rebuilt/reinstalled.

Here's a wild guess.. if you open a python interpreter does `import AppKit` work?

**Comment by matthiasdg** [comment]
Also seeing this issue (macbook pro with M3 pro, git-cola installed through homebrew). I can open a repo and commit just fine. If I close git-cola and open it again, it segfaults, unless I remove the settings file in ~/.config/git-cola, then it works again

**Comment by gerkereitz** [comment]
@davvid I have not run pip install outside of a virtualenv. Almost nothing was done on this Mac when the error started occurring. `~/.local/lib/python*` also does not exist for me, so it can't be that.

Installing and running git-cola inside a virtualenv works perfectly as it should.

When running a python interpreter, running `import AppKit` returns `ModuleNotFoundError: No module named 'AppKit'`.

**Comment by davvid** [comment]
> brew autoremove

Thanks for the pointer. I'll update the docs to recommend doing an uninstall + autoremove + install cycle with homebrew.

**Comment by matthiasdg** [comment]
Same happened after a `brew update`, `brew upgrade` cycle today; it upgraded qt to 6.6.2_2 (from 6.6.2_1). Tried the uninstall, autoremove and reinstall cycle, but it only worked after deleting the settings file too. (And after that it kept working, unlike before when I had only tried deleting the settings without the autoremove and it only worked upon the first run). Is there something in the geometry or windowstate in the settings file that could cause problems?

**Comment by gerkereitz** [comment]
@matthiasdg problem had indeed re-emerged for me too. I also was also able to fix it using the same steps

**Comment by gerkereitz** [comment]
@matthiasdg @davvid somehow it re-appeared again after a couple of uses. What I have done now to fix it is just create a venv of git-cola and alias it in my .zshrc. I'll just let that be my fix because the global one just keeps breaking.
