### ISSUE TITLE
Commit message input box pre-filled at startup

### ISSUE THREAD

**Issue by antoine-gallix** [git-cola/git-cola#1392]
Whenever I start git-cola, there is already something written in the `commit message` box. It's a commit message I wrote long time ago. It somehow is stored somewhere and is being loaded at each startup.

I'm using version 4.6.1 distributed via flatpak on Ubuntu 22.04.4 LTS

Issue on the git-cola flatpak repo: https://github.com/flathub/com.github.git_cola.git-cola/issues/57

**Comment by davvid** [comment]
Check permissions on the `.git/GIT_COLA_MSG` file in the repo. Maybe you wrote it as `root` once and cola isn't able to overwrite it anymore?

Removing that should reset things. That's the file we use to persist the commit message in case you write one and quit the app w/out committing. When you restart the message will still be there for you to continue where you left off.
