### ISSUE TITLE
Ignoring a file locally fails if within a worktree

### ISSUE THREAD

**Issue by dschwoerer** [git-cola/git-cola#1394]
git-cola ignores that I am working in a worktree, and tries to put the local ignore in `.git/info/exclude`.
It should check whether `.git` is a file and then check that to figure out where `.git/info/exclude` actually is.

This can be reproduced with:
```
git clone https://github.com/git-cola/git-cola
cd git-cola/
git worktree add mwe
cd mwe/
touch please-ignore-me
git-cola
```
right click on the file, select ignore, add to local .git/info/exclude.

Fails with:
```
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/cola/cmds.py", line 3113, in do
    return cmd.do()
           ^^^^^^^^

  File "/usr/lib/python3.12/site-packages/cola/cmds.py", line 877, in do
    core.write(filename, new_additions)

  File "/usr/lib/python3.12/site-packages/cola/core.py", line 147, in write
    with xopen(path, mode) as fh:
         ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/cola/core.py", line 403, in xopen
    return open(mkpath(path, encoding=encoding), mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NotADirectoryError: [Errno 20] Not a directory: b'.git/info/exclude'
```

**Comment by davvid** [comment]
We should absolutely make this do the right thing when using worktrees. I'm planning on getting this fixed before the next release unless someone beats me to it with a PR. Thanks for the heads-up.

**Comment by dschwoerer** [comment]
Awesome, thanks for the fast fix!
