### ISSUE TITLE
Programmatically change the UI theme?

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#1395]
In my office, I find myself having to toggle between dark and light theme.

How can I change the theme of git cola, programmatically?

**Comment by davvid** [comment]
The best way would be to use `git config` to configure the corresponding config variables.

```
git config --global cola.theme dark
git config --global cola.icontheme dark
```

https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-theme

https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-icontheme

There's environment variables for it as well in the docs.
