### ISSUE TITLE
Feature request: Go up one directory to clone when in a repository

### ISSUE THREAD

**Issue by Poikilos** [git-cola/git-cola#1402]
Git Cola version 4.6.1 
- Windows-10-10.0.19045-SP0 
- Python (C:\Users\Owner\AppData\Local\Programs\git-cola\Python\pythonw.exe) 3.9.13 (tags/- v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] 
- Git 2.44.0.windows.1 
- Qt 5.15.2 
- QtPy 2.4.1 
- PyQt5 5.15.4 

(tested on Fedora 38 and Windows 10)

## Actual Behavior
When a repository is open and the Clone feature is used, the destination defaults to a subfolder of the current repo (if the git-cola repo is open, something like `$HOME/git/git-cola` is the default for the choose directory dialog, resulting in cloning to somewhere like `$HOME/git/git-cola/git-cola.github.io`), which is basically never right. Therefore, this is bordering on a bug (It is unexpected behavior leading to user error).

This odd default may lead the user to think that they are supposed to choose a blank folder or something rather than a parent folder (Though the dialog box does say "Select a parent directory for the new clone").

A related non-git-cola issue is that some Linux DEs make it painful to choose the parent directory in a directory chooser dialog: Clicking the Up arrow to go up one directory (such as to `$HOME/git`) still leaves the subfolder (such as `$HOME/git/git-cola`) selected in some cases, or navigates back to the child when trying to click the Open/confirm button instead of confirming, so the only workaround is to go up *twice* (such as to `$HOME`) then back down (such as to `$HOME/git`) before clicking whatever is the confirm button.

## Expected Behavior
To avoid human error in the case of the default and the case of changing it incorrectly:
- If a repo is open, use the parent directory containing the repo (instead of the repo dir) as the default for the choose directory window.
- If a repo is not open, use the last directory where cloned (add a setting, and change the setting automatically or just do it automatically if the setting is empty)

**Comment by davvid** [comment]
Thanks for the detailed write-up. This is a good idea -- if we're in a repository then defaulting to the parent directory is a better default all around in my opinion as well.

If we're not in a repository and we have no previous settings then we'll use the current directory as usual, just like one might. From then on  we'll use the last directory used and store a setting to track it. I don't think this setting needs to be exposed through the UI.

The only scenario this doesn't cover is if we wanted the tool to always default to a specific clone directory and ignore one-off occasional clones into other directories.

We *could* add configuration setting to select either, "use the last directory," or, "use a specific directory", but I suspect we won't need that configuration at all and the behavior to, "use the last directory," should be sufficient and intuitive for day to day use. Furthermore, most of the time we'll be in a repo so we'll be defaulting to the parent directory of the current repo and not relying on this setting in many cases.

As usual, if any of the configured paths don't exist at runtime then we'll default to the current directory, but that's more of an exceptional scenario. We could also use parent of the missing directory (or its parent, if also missing, and so on) and use that that directory as long as it's not `/`. If we hit the root `/` then we'll fallback to the current directory as a final last-resort fallback.
