### ISSUE TITLE
Reset dialog should save used value

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#1406]
Currently every reopen of reset dialog has pre-filled `HEAD^` value. Changing it is not saved for next session.

The value I (and I belive many users) use in most case is `@{upstream}`, which is generic form of tracking branch name (eg. `origin/current-branch-name`). I want to save `@{upstream}` and use it forever.

In short, I want simple and fast action for `git reset --hard origin/master` :)

**Comment by quinn-sasha** [comment]
Hi, I am new to open source software community.
I would like to contribute to git-cola.

Can I take on this task?
I will ask questions if I get stuck.

**Comment by davvid** [comment]
Thanks for the sug!
