### ISSUE TITLE
Source installation doesn't report correct application version

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#1425]
Contrary to pipx installation, source installation doesn't report accurate application revision information:

```txt
git-cola $ ./bin/git-cola --version
cola version 4.8.2
git-cola $ git describe --always --tags --dirty
v4.8.2-27-gf54808a7
git-cola-pipx $ ~/.local/bin/git-cola --version
cola version 4.8.3.dev27+gf54808a7
```

Fixing it may help troubleshoot problems.

### OS

Ubuntu 24.04 (w/ Linux 6.8.5-45-generic)

### Python

3.12.3 from Ubuntu 24.04 software archive

### Git

2.43.0 from Ubuntu 24.04 software archive

### Qt

5.15.13

### QtPy

2.4.1

### PyQt5

5.15.10

**Comment by davvid** [comment]
This would definitely help debugging. The old behavior is a limitation from our use of setuptools-scm but we can handle it on our end as long as we're going through the `bin/*` wrapper scripts.

Thanks for the sug. This should be better behaved now when running the code directly from the cola's git repository.
