### ISSUE TITLE
Show & copy commit hash in cola

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#1430]
Currently commit hash is visible and copyable in git-dag. I run dag very often just to copy commit hash. Can I have it in git-cola?

Maybe in commit menu under "Load Previous Commit Message" and "Fixup Previous Commit" would be a good place?

**Comment by davvid** [comment]
Good idea, I'll take a look soon. We can have it use the same ctrl-alt-c hotkey as git-dag. I'll probably add this to the "Edit" dialog since that's where the current "Copy" action lives.
