### ISSUE TITLE
The pre-commit hook does not honour desktop proxy settings

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#1431]
I noticed this problem when committing to a repository that has its [pre-commit](https://pre-commit.com) hook uninitialized:

![Screenshot](https://github.com/user-attachments/assets/2b33f273-b306-4ade-b32c-9297fc6278d4)

We probably should also export the following environment variables if proxy settings are detected:

* `http_proxy`
* `https_proxy`

Reproduced using the 3645fcec revision.

**Comment by davvid** [comment]
Good catch, thanks for the sug. We now setup proxy settings when authoring commits as well. Let me know if that does the trick in your setup.

**Comment by brlin-tw** [comment]
@davvid 

Thanks for the support!  I can verify that the 7c8b0d48 revision works at my end.
