### ISSUE TITLE
wrong tab order regression in Commit pane

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1436]
Hey,

There's an issue where the tab order doesn't go from the commit's header line to the description in the Commit pane.

***EDIT***: **see my second message below for a better attempt at finding the cause.**

![image](https://github.com/user-attachments/assets/bce064da-f915-43eb-982e-8237301fa2e6)

Now pressing Tab should move to the description, like so:

![image](https://github.com/user-attachments/assets/49b2df4e-798c-4a7a-989b-d9e2cad12d04)

However, it only works when working around by unlocking the widgets, then dragging the Commit pane then putting it in the same place.

It appears that upon pressing Tab, the focus goes right into the Diff pane which is the next *pane* after the Commit pane, but the Commit pane should have 2 tab slots (commit header and message), as on the screenshot.

![image](https://github.com/user-attachments/assets/74591028-d951-4201-b276-a605d3fc0c02)

**Comment by sthalik** [comment]
Ah, there's the simple explanation: the tab order for the commit title/message is reversed.

So pressing Shift+Tab goes from title to the multi-line message. Can you make it as before please?

**Comment by davvid** [comment]
Well spotted, thanks for reporting that regression. I usually hit "enter" to switch from the summary field into the extended description which is why I hadn't noticed it, but I did not intend to lose this key behavior. cheers!
