### ISSUE TITLE
Feature Request: dark theme

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1437]
I use dark theme for VS code and Brave browser, it would be nice if my git client has one too, otherwise it is a bit of shock when viewing the non-dark git-cola display.

**Comment by davvid** [comment]
Is this on Windows? There's a few dark themes available. `File -> Preferences -> Settings -> Appearance`

**Comment by davvid** [comment]
Sweet, glad that helped.

For Linux users on Debian/Linux and running gnome, cola will follow gnome's dark theme if you have it configured as the platform plugin for Qt.

This boils down to having this set in your environment:

```bash
export QT_QPA_PLATFORMTHEME=gnome
```
