### ISSUE TITLE
Problem with set upstream branch

### ISSUE THREAD

**Issue by sbuspl** [git-cola/git-cola#1440]
Hi. We've got a lot of branches in repository. They don't match in the set upstream branch list. Can You fix it by adding, a scrollbar?

![git_cola_4_9_0_main_window](https://github.com/user-attachments/assets/581a710a-f22c-4d82-9b26-0eb79a7858b5)

![git_cola_4_9_0_set_upstream_list](https://github.com/user-attachments/assets/4af029e5-13b7-4f3d-96f9-63526722ba9a)

**Comment by davvid** [comment]
Thanks for the heads-up. I changed it to use a custom dialog instead. It's much nicer now.
