### ISSUE TITLE
4.10 broke the rebase window/no changes displayed on windows

### ISSUE THREAD

**Issue by Hoernchen** [git-cola/git-cola#1442]
While messing with different versions for #1441 I have discovered that even the recently released 4.10 version does not display the changed files/changes in the rebase window (still on windows, and wsl1, but this affects plain old windows repos without any wsl magic, too!), while all previous versions work just fine. Both panes are just empty.

**Comment by davvid** [comment]
Doh :shaking_face: I missed this when support for the "git init" state was added.

Thanks for the heads-up. I'm planning on tagging a new patch release in a few days.

https://github.com/git-cola/git-cola/actions/runs/12309460945 has the latest version with this fix.
