### ISSUE TITLE
Option to ignore whitespace difference

### ISSUE THREAD

**Issue by glenjamin** [git-cola/git-cola#150]
A little tick-box on the diff viewer that allowed white-space ignoring would be nice :)

**Comment by souch** [comment]
I managed to ignore whitespace change by adding -w (--ignore-all-space) to the git command line 

in file cola/git.py line 335 :
```
        # Prepare the argument list
        git_args = [
            GIT,
            '-c', 'diff.suppressBlankEmpty=false',
            '-c', 'log.showSignature=false',
            dashify(cmd),
            '-w' # <---------- ignore whitespace change
        ]
```

I'll see later if I can make this as an option in a clean pull request.
