### ISSUE TITLE
'git mv' command integration into browser

### ISSUE THREAD

**Issue by OmegaPhil** [git-cola/git-cola#239]
Please could the 'git mv' command be integrated into the browser (or other useful place) in git-cola?

Thanks

**Comment by ulgens** [comment]
That's hilarious to see how my idea changed in 3 years :D I think now it's an important feature, thanks! :tada:

**Comment by hackel** [comment]
Perhaps this should be a separate feature request, but I would like to see renames shown in the status pane, as they are in `git status` instead of as a separate delete/create.
