### ISSUE TITLE
.gitignore file not being used

### ISSUE THREAD

**Issue by ispmarin** [git-cola/git-cola#26]
There is a .gitignore file on the git repo for my project. The files listed there are correctly ignored using on command line or git gui, but git-cola does not use the .gitignore and does not ignore the files.

**Comment by ArchakGoel** [comment]
Hi, 

I am using the latest 3.12.0 version of git-cola and its still not ignoring files mentioned in .gitignore. The same .gitignore in the same repo was working fine with other version control software.
Any workarounds to it @davvid ?
Thanks

**Comment by davvid** [comment]
I suspect that your files are already tracked. Are you seeing this in a public repository you can share?

Run `git ls-files`

Do you see the "ignored" files listed in the output?

If you see the filenames listed there then they're not candidates for being ignored until you remove/untrack them from git.

You can use the `View -> File Browser` tool as well. From there you can right-click and "Untrack Selected" to remove them from git.


I'm making a wild guess that you're basically running into a symptom of this: https://upokary.com/file-added-in-gitignore-but-still-shows-up-on-git-status-why/
