### ISSUE TITLE
Support git init

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#277]
### Current behavior
- User have to `git init` manually in terminal in order to use git-cola for other operations
- The "New..." button in the default dialog when git-cola doen't find an existing repository is _nearly equivalent_ to choosing "Select manually..." then "Open..." and doesn't have the functionality user may expect(if no repository exists in user specified directory then initialize a new one)
  ![git-cola_077](https://cloud.githubusercontent.com/assets/1192163/3202451/f27caac8-ed90-11e3-8548-93ecc4d5bff1.png)
- The "New Repository" and "Open/Open in New Window..." menu item in "File" menu has the same issue too.  
  ![_082](https://cloud.githubusercontent.com/assets/1192163/3207866/7abcf95a-ee0a-11e3-8e88-b878c001805b.png)
### Proposed behavior
- When ${CWD} isn't inside a Git repository
  - `$ git cola`(or directly launch git-cola from menu) should provide an option to initialize an empty Git repository at user specified directory(default: ${CWD}) then launch git-cola with that repository
  - The "New repository" menu item in "File" menu should initialize a new Git repository but not open an existing one.
  - `$ git cola init [directory]` initializes an empty Git repository in [directory](default: ${CWD}) then launch git-cola with that repository

**Comment by bensmrs** [comment]
Shouldn't we close this issue?

**Comment by davvid** [comment]
Sure, this can probably be closed.  The "New" button in the "Choose repo..." dialog now creates the repo, so that should match expectations.  We don't have `git cola init ...` but if we really want it we can always submit a new issue for just that use case.  Thanks
