### ISSUE TITLE
Create a system notification when push completes

### ISSUE THREAD

**Issue by victorhaggqvist** [git-cola/git-cola#350]
It would be nice to get a system notification when a push (and maybe similar tasks like pull) completes. This would be use full if the GUI is not in focuse when the task completes.

**Comment by davvid** [comment]
This would be a nice feature to make opt-in. Maybe we can leverage https://pypi.org/project/notify-py/ to do it.

We'd probably have this disabled by default. Also, if the notify-py module is not installed then things should be made to still work, similarly to how the Send2trash functionality and dependency is "optional".

**Comment by pratyaksh177** [comment]
hey, I want to work on this.

**Comment by Vrushutup** [comment]
is this issue completed?

**Comment by davvid** [comment]
@pratyaksh177 @Vrushutup ~ Feel free to pick this up. I'll be happy to answer questions and review PRs. Thanks for reaching out.

**Comment by Anurag404OpenSourceRules** [comment]
Hey, I'm new to the community. I'd like to contribute and grow. Please let me know how I can help build this feature!

**Comment by Anurag404OpenSourceRules** [comment]
@davvid I read the documentation of https://pypi.org/project/notify-py/ and would love to contribute to this feature, but I am new to contributing, so, it would be great if you could kind of give me an idea of how I can get started. It would be really helpful.

**Comment by davvid** [comment]
Sure thing. I'd suggest first reading the cola code, starting from `./bin/git-cola` and then working your way through `cola/main.py` and `cola/widgets/main.py` to get a sense of where how things get started.

From there, I'd suggest using the `ctrl-g` grep feature and search for `send2trash` and study how it's integrated. You'll want to integrate a similar "optional" dependency that should only activate itself when the modules are available.

`cola/widgets/remote.py` is where you'll find the code that does the pushing. `def push_to_all(...)` is of particular interest.

This code is a bit older and it wasn't written to leverage the editor commands pattern that we have going in `cola/cmds.py`. Not required, but if you're inclined to refactor the code a bit, it would be good to take some of that responsibility out of the widgets module and move it into a new `class Push(...)` editor command defined in `cola/cmds.py`.

Lastly, take a look at the `cola/interaction.py` file which provides `class Interaction`. This class is used as a proxy between editor commands and displaying information. I think it'd make sense to implement a simple `def notification(...)` method in here. You'll need both a non-gui implementation

`interaction.py` contains the non-GUi implementation. Then take a look at `def install()` in `cola/widgets/standard.py`, `cola/guicmds.py` and `cola/widgets/cfgactions.py` (and a few others). This is where we monkeypatch the "real" implementations that provide the Interaction interace used by commands.

You'll want to patch your new function similarly. This new function probably makes sense to be in `cola/widgets/guicmds.py`. The patching happens in the `class ColaApplication` constructor in `cola/app.py`.

This new behavior should be opt-in and disabled by default. Take a look at `cola/widgets/prefs.py` and `cola/models/prefs.py` to see how existing git-config preferences are stored. `cola.notifications.push` is probably a good git config variable to use for it this new setting. The rationale is that maybe later you might want to start having notifications for other actions (eg. `Fetch` or `Pull` at `cola.notifications.fetch`, etc).

If we believe that we're going to have other notifications then also add support for a global `cola.notification.enable` that can serve as a single catch-all for disabling notifications full stop. Let me know what you think.

Are there existing chat communities related to pyqt, git or python (gitter?) that you already frequent? If so I could probably try to hop on somewhere and start a thread there in case you have any questions on how to go about implementing it.

Thanks for offering to give that a go. Give it a try and we can iterate on it via PRs, etc.

**Comment by Ra00f1** [comment]
Hello
Is this issue still open to PRs?
