### ISSUE TITLE
wishlist: git-forest-like visualization

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#352]
Please support visualisation of all branches as https://github.com/jwiegley/git-scripts/blob/master/git-forest does.

It's very soothing, not to mention useful. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/1896811/4503295/eb43ae58-4ad5-11e4-827a-dc5122c28cc7.png)

**Comment by jm4R** [comment]
I like the idea. We could add it to git-dag.
