### ISSUE TITLE
Different widget layout used when launched using different locale

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#382]
![1_001](https://cloud.githubusercontent.com/assets/1192163/5211952/7453519a-7627-11e4-8fd6-4f935945cb18.png)
The right window is launched using LANG=zh_TW.UTF-8 LANGUAGE=zh_TW:zh_HK:zh:en git cola (default locale)
The left window is launched using LANG=en_US.UTF-8 LANGUAGE=en git cola

**Comment by prof7bit** [comment]
7 years later and this bug still exists.

**Comment by davvid** [comment]
Thanks to @prof7bit  we now have a fix!
