### ISSUE TITLE
Feature request: Allow temporarily change committer's(author's?) name/email

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#387]
There's two case when this is useful
1. When `user.name` and `user.email` are not initialized: when I'm on public machines and didn't want to `git config`
2. When `user.name` and `user.email` are initialized, but not actual committer's identity: In some cases multiple users use same account on the same machine to commit changes.
## Proposal
1. When `user.name` and `user.email` are not initialized and that user commits, ask user to enter a temporary committer identity(also give a choice to save it to git-config, or just use it during this Git Cola session), this also fixes #385 
2. Multiple committer profiles: Allow Git Cola to maintain multiple committer's identity, and let user choose which to use as alternative when committing

**Comment by kyanres** [comment]
Do you consider this issue fixed ?
(Since there are now fields for user and email in File > Preferences)
