### ISSUE TITLE
git-cola rebase should default on @{upstream}

### ISSUE THREAD

**Issue by ptbrowne** [git-cola/git-cola#416]
`git rebase` without argument defaults on `@{upstream}`. I think `git-cola rebase` should do the same.

**Comment by davvid** [comment]
Thanks for the sug. I made it so that `git cola rebase` matches the cli syntax for `git rebase` more closely.

**Comment by ptbrowne** [comment]
Wow! Such speed :+1: Small thing though: I have seen that you wrote in the commit "Suggested by Patrick Browne <patrick.browne@amadeus.com>". The thing is, I do not work there anymore... Where did you get this email so that I can correct it where you found it ?

**Comment by davvid** [comment]
I basically just trolled through github, found a commit you authored, and then got the email from there.  I probably chose a commit that was a bit too old ;-) Thanks for the heads-up.
