### ISSUE TITLE
integrate with git-deps?

### ISSUE THREAD

**Issue by aspiers** [git-cola/git-cola#418]
Cool project!  Perhaps you'd like to consider [integrating it](https://github.com/aspiers/git-deps/issues/23) with the [`git-deps` tool I recently announced](http://blog.adamspiers.org/2015/01/19/git-deps/)?

**Comment by davvid** [comment]
This could be pretty cool. One way would be to use https://git-cola.readthedocs.org/en/latest/git-cola.html#custom-gui-actions to implement custom git-deps guitool actions, similar to what I suggested on the git-cola list for implementing a git-flow workflow.

We could have git-deps integration as a prominent example in the git-cola documentation. Do you have a sense of the extent of the actions that would be needed? It seems like it boils down to one action, `git deps <commit>`, correct?

**Comment by aspiers** [comment]
> It seems like it boils down to one action, git deps <commit>, correct?

@davvid No, I am proposing integrating the whole git-deps web UI.

**Comment by davvid** [comment]
That could be pretty cool since we have QtWebKit available, so we could leverage that.  This is also another vote for adding a simple plugin/extension mechanism to `git-cola`. What kinda ideas are you thinking about?

I have a few other use cases where we want to customize cola. `git-deps` is a good reason to add a python-based extension mechanism.  Even if it's an extension, we'd ship it by default and make it really easy to enable (or possibly have it enabled by default).

Are you thinking of reimplementing `git-deps`, or more of a bundling approach where we communicate with it and render its results into a WebKit view?

**Comment by aspiers** [comment]
> Are you thinking of reimplementing git-deps, or more of a bundling approach where we communicate with it and render its results into a WebKit view?

I'm not sure what you mean by "reimplementing"?  The `git-deps` web UI is a client-server model where the server is currently run using [Flask](http://flask.pocoo.org/) and the client (view) requests JSON data from it via AJAX.  But this could be changed if necessary, and the HTML views could easily be integrated within any HTML rendering widget.

**Comment by davvid** [comment]
That sounds cool. By "reimplementing", I was asking if you were planning on reimplementing `git-deps` "from scratch" using qt widgets, but it sounds like you want to embed it in a web view, which is what I was hoping for as well. This would be very cool.

**Comment by aspiers** [comment]
Definitely not going to do any rewrite! That would be a horrific waste of time :-) It would be much harder to do without d3, and I can't think of any significant benefit either.

**Comment by davvid** [comment]
That sounds good. How are you planning to embed git-deps?  Should git-cola manage a server instance, or should git-cola know only about a URL for a git-deps REST API server?

Would it make sense to have them as separate processes, or will git-deps be running as part of the main git-cola process?  Sorry for all the questions ~ I can always wait to see the code and answer them myself by reading it ;-) just curious about how to best structure the interaction between git-cola and git-deps.

**Comment by aspiers** [comment]
I think `git-deps` needs a small bit of refactoring so that the webserver code resides in a library module which `git-cola` can use to spawn a webserver thread (or process).  [The webserver code is very small and simple](https://github.com/aspiers/git-deps/blob/master/git-deps#L679) so this should be easy.  Perhaps we could work together?  I'd be glad to do this refactoring; sadly I won't have time to make the corresponding changes on the `git-cola` side myself although I could certainly give you pointers if you got stuck.
