### ISSUE TITLE
Desaturated diff colours

### ISSUE THREAD

**Issue by StanAngeloff** [git-cola/git-cola#420]
As part of commit 1317378355c8300ddf0e4a6881efb78baf531a2f the diff colours were desaturated. On my particular set up the result is very unappealing and makes the added/removed background look too similar.

I'm opening this issue to discuss the possibility of restoring the old contrasting backgrounds or to consider making this change configurable (happy to submit a pull if enough people get on behind the idea).

| Before | After |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/93127/6665261/effdd3de-cbdf-11e4-881a-d632e435e9b0.png) | ![image](https://cloud.githubusercontent.com/assets/93127/6665238/cba172de-cbdf-11e4-97cd-5ab696c2b75f.png) |

**Comment by Vdragon** [comment]
Making this change configurable+1

**Comment by joshuataylor** [comment]
Hate to be a 'me too!' issue poster, but I was about to make an issue for this.

Would love a way to make this configurable, as the old contrast was 'good for me'.

I'm sure there are pro/cons for look, which is why configurable would be awesome.

**Comment by joshuataylor** [comment]
Wow @davvid that was a quick change. Awesome work :+1:

**Comment by StanAngeloff** [comment]
Awesome indeed! :tada:
