### ISSUE TITLE
Add keyboard shortcuts for pull and push

### ISSUE THREAD

**Issue by yktoo** [git-cola/git-cola#423]
This git client, otherwise brilliant, has one very annoying issue: one has to revert to mouse to click Pull or Push button. Would be very helpful to have any keyboard shortcut for those, very common, operations.

**Comment by yktoo** [comment]
Sorry had to upgrade to the latest version to see it's already there. BTW it may be a good idea to update [this page](https://git-cola.github.io/share/doc/git-cola/hotkeys.html) to let people at least google it :) Thanks for the app!

**Comment by davvid** [comment]
Good idea, thanks for the reminder.
