### ISSUE TITLE
Repository Collection Widget; or, add git repositories to favorites list recursively

### ISSUE THREAD

**Issue by djhaskin987** [git-cola/git-cola#427]
Adding git repositories to the favorites list recursively was an optional part of #289, but it's the only part of that issue that I want. Seeing all the repositories I have on my machine at once would make git cola a _lot_ more usable. 

I don't just want a list of repositories which are my favorite or which ones are the most recently used. I want the option of having a widget displaying all the repositories on my system in an intelligent manner.

I don't have favorite repositories at work. I just have repositories that I need to work on. It's still important to have a favorites list, but I also want a sort of "master" list. I feel like this is the _one_ feature that solutions like SourceTree and SmartGit has, but git cola doesn't. In every other way, I feel that git cola is superior in its functionality. This feature would, IMHO, make git cola a much better tool.
# User Stories
## Repository Collections Widget

As a user, I have a notion of repository collections. This means I have directories which themselves contain git repositories in a directory tree.

If I have a directory with git repositories that looks like this:

![examplegitcollectionslayout](https://cloud.githubusercontent.com/assets/1186534/6871484/85a708a2-d468-11e4-9764-4175623997a8.png)

I want a widget that can display repositories in a tree, (same type of tree as the above image) where the parents are called the "Repository Collections" and the children are the git repositories themselves. This widget aims to list all git repositories that "you care about". Call this widget the "Collections" widget.

I want it to show up in git cola looking something like this:

![examplerepositorycollectionslayout](https://cloud.githubusercontent.com/assets/1186534/6871485/85b9a408-d468-11e4-8371-3921fed47929.png)

In the example above, we see there are two directories with git repository collections. One collection is labeled "github.com" and one collection is labeled "gitlab.workplaceexample.com". These collections are represented on the filesystem by simple directories.

In the repository collections view, it shows in a flat list the git repositories inside these directories, listing their paths relative to the path of the repository collection. Submodules are listed similarly, with their names as the directory relative to the parent repository in which they reside.

As can be seen, this widget would display collections, repositories and submodules in a tree relative to where they can be found on the filesystem.

This widget would then work much like the favorites list, where if I double-clicked on a git repo listed in the collections widget, git cola would bring that repo up.
## Repository Collections Widget refresh

The application refreshes the tree in the repository collections widget on start-up.

As a user, I also want a refresh button in the widget so that I can choose when the application refreshes the list if needed.
## Add Repository Collection

I want to hit a button in the "Collections" widget indicating that I want to add a git repository collection. Perhaps this could be a "+" button just like the pre-existing "+" button in the "Favorites" widget.

A window would pop up, with a text field asking me to specify which directory is associated with the new git repository collection.  to look in. Call this window the "recursive search" window. The text field would have a "browse" button next to it so that I could browse through the file system to find the directory containing git repositories.

Once the search begins, the gui will then display information indicating that git-cola is searching for repositories. This could be in the form of the "Search" button's text changing to "searching", another window popping up with a spinning wheel or loading bar, etc.
## Remove Repository Collection

There should be a button, maybe a "-" button, allowing me to remove repository collections from the collections view. This would simply stop showing me the repositories within a repository collection directory.
## Default Layout

The new widget would likely be turned off by default in its initial debut so as to not violate the principle of least surprise. However, I think it would be very useful to have it in the default layout.

Personally, I think the default layout including the repository collection in it could be most useful if it looked like this:

![Example default layout including the repository collection.](https://cloud.githubusercontent.com/assets/1186534/6872433/c16d49f4-d46e-11e4-8def-d9b541ae3ead.png)
# Alternative/Minimum Viable Feature: Add directories to the "Favorites" list recursively

If the repository collections widget is too much work or simply not what git cola is about, I would still get lots of value out of a feature which allowed me to recursively add all the git repositories within a particular directory to the favorites widget. I don't know if this should be done, as that is effectively saying "ALL the repositories are my favorite", so defeating the purpose of making a list of favorite repositories. However, if that feature was in place, it would certainly make my life easier :)

If we were to go this route, the feature would include a dialog box asking which directory should be searched in, _as well as_ a "browse" button so that I didn't have to type in the directory's name from memory.

The window would also have a check box indicating that I want to include submodules in the list, checked by default. If unchecked, this means that git repositories that are in sub directories of other git repositories are ignored in the search. If checked, it means that such git repositories are not ignored, but are included in the list. There is a "Search" button which, once pushed, searches the directory and adds all git repos in the directory to the favorites list.

**Comment by djhaskin987** [comment]
what's the stance / status on this? is this something that other people want too? I think it would really help make git cola better.

**Comment by Vdragon** [comment]
Personally I :+1: this, although I don't speak Pythonese.

**Comment by davvid** [comment]
I dig this one too. That's a nice design.

**Comment by djhaskin987** [comment]
Yay! thanks for adding it to the wishlist
