### ISSUE TITLE
Error: The application “git-cola” can’t be opened.

### ISSUE THREAD

**Issue by sitnikovme** [git-cola/git-cola#428]
mac os x 10.10.2 (14C1514), git cola version 2.1.1 (built from source via make git-cola.app)

Steps:
1) open git-cola from launchpad
2) select and open repo
3) repo is opened ok
4) open git-cola from launchpad one more time

Result: Error message: "The application git-cola can’t be opened."
Expected: activate already opened application.

**Comment by davvid** [comment]
Hmm, strange, I don't see the issue. We might be able to get some clues from `console.app`.

Use `Spotlight`, search for `Console`, open it and then perform steps 1-3.  Next, click the `Clear Display` button before performing step 4.

There may be some details in the `Console` log that are revealed after performing step 4.  Do you see anything there?

**Comment by davvid** [comment]
Closing, no response.
