### ISSUE TITLE
Error launching history browser

### ISSUE THREAD

**Issue by deniz1a** [git-cola/git-cola#429]
git-cola shows an error dialog when I click "Visualize Current Branch" or "Visualize All Branches". Error dialog says:
Cannot exec "C:\Program Files (x86)\Git\bin\gitk --all": please configure a history browser.

Traceback (most recent call last):

  File "C:\Program Files (x86)\git-cola\share\git-cola\lib\cola\cmds.py", line 1634, in launch_history_browser
    core.fork(argv)

  File "C:\Program Files (x86)\git-cola\share\git-cola\lib\cola\core.py", line 186, in _fork_win32
    return subprocess.Popen(argv, cwd=cwd, creationflags=DETACHED_PROCESS).pid

  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

WindowsError: [Error 193] %1 is not a valid Win32 application

I am using Windows 7, git 1.9.5.msysgit.0, Python 2.7.9 32 bit, PyQt 4.11.3-Py2.7-Qt4.8.6 32 bit and git-cola 2.1.1. I tried Installing 64 bit versions of Python and PyQt but the same error occurs. gitk is configured as the history browser in settings. gitk works when I launch it from git bash.

**Comment by deniz1a** [comment]
OK gitk launches from git-cola if the history browser option is set as:
C:/Git/bin/sh --login -i C:/Git/bin/gitk

But I can not launch an external diff tool by right clicking a file and choosing launch diff tool. The same diff tool opens when I set it as the editor. I think the file paths are not handled correctly on windows...

**Comment by geotavros** [comment]
I have the same error. Don't understand what did you do to fix it

**Comment by deniz1a** [comment]
I put the above line to history browser path and it worked. You have to launch gitk from git shell.

**Comment by davvid** [comment]
Thanks for the notes, that helped me come up with a good solution.  You *may* need to reconfigure things if you have existing settings, otherwise the new defaults should do the right thing now.  I've also documented how to use gitk as the history browser on Windows in README.md.
