### ISSUE TITLE
Clear "Commit Summary" and "Extended Description" text boxes

### ISSUE THREAD

**Issue by Kryten0807** [git-cola/git-cola#431]
I use git-cola for most of my commits, but when it comes time to merge a branch, I do it in the shell. This is because I'm using [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) for my workflow and I use the handy [gitflow extensions](https://github.com/nvie/gitflow) to make it easy.

The problem is that when I finish up a feature, release, or hotfix branch and execute my `git flow feature finish ...` command (for example), the merge commit summary and description appear in the Contract Summary and Extended Description text boxes and are not cleared when the merge operation is finished. So the next time I go to make a commit, I have to manually clear the summary and description.

I believe the problem arises because issuing a `git flow feature finish` command begins a series of operations:

1. check out the `develop` branch
1. merge the feature branch into develop
1. delete the feature branch

When the merge starts, it appears that git-cola detects this and picks up the commit summary & description and populates the text boxes. But it does not notice that the merge has been completed and doesn't clear the summary and description.

Thanks

**Comment by davvid** [comment]
Thanks for the sug.  If it happens again and `git-cola` doesn't notice that the file is gone then use `Ctrl+R` to refresh.  Refreshing now clears the message if it had previously been read from e.g. `.git/MERGE_MSG` and it has not been edited since it was first read.
