### ISSUE TITLE
Can't push changes

### ISSUE THREAD

**Issue by makitso** [git-cola/git-cola#433]
Using git-cola 1.9.3 on Ubuntu 14.04.  I can do git push origin master from the command shell and it works correctly.  
rob@ubuntu-desktop$ git push origin master
Username for 'https://github.com': xxxxx
Password for 'https://makitso@github.com': 
Counting objects: 115, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (21/21), done.
Writing objects: 100% (21/21), 15.60 KiB | 0 bytes/s, done.
Total 21 (delta 13), reused 0 (delta 0)
To https://github.com/xxxx/xxxx
   ec79dd9..c30d3a9  master -> master
Username for 'https://github.com': xxxxxxxxxxx
rob@ubuntu-desktop:~/git/xxxxxxx$ 

However, in git-cola when I do a push (remote branch origin local branch master I get an error: 
Pushing to https://github.com/xxx/xxx
error: cannot run None: No such file or directory
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by davvid** [comment]
Can you please test `master` (anything after eac0926bf4c0542667b816a3ae519048406768a2) and let me know if it fixes this issue for you?  I'd also be curious to know whether it works using an ssh `git@github.com:xxx/xxx.git` style url in `.git/config` instead.

**Comment by makitso** [comment]
Actually, I updated to github version 2.1.2 and that fixed the problem.  I will close the issue.
