### ISSUE TITLE
Consider removing "Revert Uncommited Edits..." command?

### ISSUE THREAD

**Issue by living180** [git-cola/git-cola#438]
For modified files, there are two similar commands, "Revert Unstaged Edits..." and "Revert Uncommitted Edits...".  Personally, I would like to have only the first of these.  This way, the unstaged changes can go two directions, either revert (discarded) or stage (to index).  Having a command that also affects the staged changes is to me confusing and error prone:  more than once I'll stage the changes that I intend to commit, and want to throw away the rest (e.g. perhaps they were for debugging).  I always have to stop and think carefully to make sure I chose the correct "Revert" menu item to avoid throwing away the staged changes as well.  This does require two steps if wanting to revert staged changes (unstage, then revert), but for me personally at least,  I'm willing to deal with that to avoid the risk of accidentally throwing away changes I wanted to keep.

If this would be a desirable change, I'm happy to implement it and make a PR.

**Comment by ugtar** [comment]
I actually +1 this

**Comment by davvid** [comment]
I'm convinced too :+1:

**Comment by living180** [comment]
Great, then I'll work on getting a PR up sometime next week.

**Comment by living180** [comment]
Closed by PR #454.
