### ISSUE TITLE
auto close cola when every change is committed

### ISSUE THREAD

**Issue by robkorv** [git-cola/git-cola#439]

**Comment by davvid** [comment]
Are you saying that you'd like something like `git gui citool` that closes the dialog after the commit is performed?  One way to do that would be to implement a `git cola citool` sub-command for this purpose. I can see that being useful for quick one-off commits, and it can probably reuse a lot of code.

**Comment by robkorv** [comment]
I use the terminal as a starting point for all my commits and use `git cola` to check the code I'm going to commit. Usually this is a done with:

1. a glance at the code
2. writing a commit msg
3. `ctrl + enter`
4. `alt + f4` or move the mouse to the close button

I see this as a setting in `git cola`, a check box for auto closing after all changes are committed. Gitext has a similar feature for it's commit dialog.
