### ISSUE TITLE
Move `aptitude` to `apt-get`

### ISSUE THREAD

**Issue by envygeeks** [git-cola/git-cola#440]
Ubuntu no longer contains `aptitude` and it's a Debian-based Distro.  It would be nice if `aptitude` could be moved to `apt-get` since all Debian-based distros do have that by default (as far as I'm aware since it's core.)

I'll send a pull request if you do not mind this change.

**Comment by davvid** [comment]
Thank you, yes, this would be good to do.

**Comment by envygeeks** [comment]
Man you beat me to it! Thanks for fixing this before I did this morning. :heart:
