### ISSUE TITLE
Allow diff view to display images?

### ISSUE THREAD

**Issue by mkonecny** [git-cola/git-cola#444]
When working on a project with a lot of image assets and preparing a commit, I find myself leaving the git-cola UI and switching windows back and forth often to see which images I should stage.

I think it would be great if I could simply preview the image within git-cola itself. I wouldn't mind providing this via a pull request if anyone else thinks this would be useful.

**Comment by Vdragon** [comment]
Maybe upgrade diff view to diff/preview?

**Comment by mkonecny** [comment]
@Vdragon exactly more of a preview in the case of an image.

**Comment by Vdragon** [comment]
@mkonecny Thus diff/preview not diff&preview :P

**Comment by davvid** [comment]
This would be supercool. The diff viewer already has a little header menu, so we could add a little eye icon to the header that's only active when an image file supported by Qt is selected.

Enabling the eye toggle would put cola into the image diff mode.

That mode could have a few different layouts for how it shows the image.
It could show them side-by-side, and vertically.

Super fancy would be a mode that rendered them in a single view with a slider to wipe or blend between the images.

Zoom controls would be helpful too, with the same mousewheel interaction we have in `git-dag`.

QGraphicsScene would probably be the "lightest" way to implement it.  QtWebkit would be an interesting way.. we'd basically render it using html + javascript, in an embedded web view.

Thoughts?

**Comment by Vdragon** [comment]
I wonder if the toggle is really needed when we already know the file is a picture..

**Comment by davvid** [comment]
@Vdragon that's true.

**Comment by davvid** [comment]
I have a prototype in the works in case anyone wants to test an early version.  It should be closer to what'll ship in master by this weekend, but until then experimental versions are in my fork's `imagediff` branch.
