### ISSUE TITLE
Interactive rebase won't halt to let you do the editing

### ISSUE THREAD

**Issue by Mailaender** [git-cola/git-cola#445]
This seems to be a regression in version 2.1.2

**Comment by davvid** [comment]
What's does `git config gui.editor` print?  If the command you have configured doesn't block in the foreground then `git` will think that it's finished (e.g. when using the "reword" action) and continue on with the rebase, despite the file being unchanged.

I have `gvim -o -f` set as my `gui.editor`.  Does setting yours to the same work for you?

I tried reproducing it but the `git cola rebase origin/master` seemed to do the right thing for me.  Let me know what you find.

**Comment by Mailaender** [comment]
```
git config gui.editor
kwrite
```

**Comment by davvid** [comment]
How about `git config core.editor`?  I just fixed a bug where we were not always using `gui.editor`, specifically in the skip and continue commands, so Git may have fallen back to the non-gui editor.

I installed kwrite and it seems to do the right thing, so I think it was probably the hole I just patched. Let me know if that fixed it for you.

**Comment by Mailaender** [comment]
`git config core.editor` was empty.
