### ISSUE TITLE
Allow commit messages starting from «#»

### ISSUE THREAD

**Issue by Maaaks** [git-cola/git-cola#446]
In my `~/.gitconfig`, I have following lines:
```ini
[core]
    commentchar = ";"
```

It works fine for Git's CLI, so I am able to make commit messages starting with «#», and these lines are not parsed as comments.

But in git-cola (v2.0.6, Ubuntu 15.04), I still can't make such commit. It says «Aborting commit due to empty commit message.»

**Comment by Vdragon** [comment]
It is similar with issue #383, but the fix hardcoded to deal with '#'
