### ISSUE TITLE
Crash while staging selected lines for a commit

### ISSUE THREAD

**Issue by Pastafarianist** [git-cola/git-cola#447]
Traceback (most recent call last):
    
      File "/usr/share/git-cola/lib/cola/cmds.py", line 1314, in do_cmd
        return cmd.do()
    
      File "/usr/share/git-cola/lib/cola/cmds.py", line 168, in do
        apply_to_worktree=self.apply_to_worktree)
    
    ValueError: need more than 2 values to unpack

Seems that the reason is that the part I selected was in the very end of the file, and contained `\ No newline at end of file`.

**Comment by living180** [comment]
What version of git-cola are you using?  That code underwent a major overhaul in version 2.1.0, and it looks like you may be using an older version.

**Comment by Pastafarianist** [comment]
I am on 1.9.4.
I will upgrade and re-open this issue if the problem persists. Meanwhile, thank you for your time.
