### ISSUE TITLE
Release binary package for other OS distros too.

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#449]
Hi Git Cola developers, currently Git Cola only release binary package for MS Windows platform, it would be great to include other platforms'(as long as we implemented) as well.

This is a derived issue of #448 .

**Comment by Mailaender** [comment]
I highly don't recommend it doing all the Linux distribution packaging on your own from Ubuntu build boxes with limited support for other  We do the packaging at @openSUSE so you don't have to. You are of course invited to s

**Comment by davvid** [comment]
The distro-neutral way to have an always-up-to-date git-cola is to just clone a copy and keep it in e.g. `~/src/git-cola` and symlink `~/bin/git-cola` to `../src/git-cola/bin/git-cola`. Prepend `$HOME/bin` to `$PATH` in e.g. `~/.bashrc` to make it all work.

Homebrew on OSX works in a similar way, essentially, and I often send pull requests over there to update their git-cola version (but I often forget, too).

I'd be happy to merge a pull requests that adds documentation encouraging users to contribute to distro-specific packaging efforts, e.g. debian, fedora, homebrew, opensuse, et al. and documents the symlink trick for users that like to live on the bleeding edge.

That said, if a kind volunteer provided a fully automated CI system that made common deb, rpm, etc. packages available to users (similar to fedora's koji service) then I would have no way to refuse and would happily link to these builds from the homepage.
