### ISSUE TITLE
Implement upstream Git Cola update detection.

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#452]
Hi Git Cola developers!
It would be great if Git Cola supports detecting new releases from GitHub on Git Cola(in case that user build the software without using any maintained software sources).

**Comment by kkofler** [comment]
The problem with this RFE is that, as a packager, I explicitly DON'T want this. I don't want my users to get notified of updates that are not yet available to them.

**Comment by Vdragon** [comment]
@kkofler Made an option to disable this feature?

**Comment by davvid** [comment]
I manage my git-cola installs at $dayjob using the distro-provided package manager and homebrew pacakges, so I wouldn't really use this feature myself.  But, it is pretty easy to implement a custom guitool command that provides this feature if someone really wanted it.

Add the following to `.gitconfig`:
```sh
[guitool "Update git-cola"]
    cmd = git-cola-update
```
And provide a `~/bin/git-cola-update` shell script:

```sh
#!/bin/sh
cd "$HOME/src/git-cola" &&
git fetch origin &&
git rebase origin/master
```

This will make an "Update git-cola" action appear in the `Actions` menu.  It's not quite automatic, it'd at least be only a few clicks away.
