### ISSUE TITLE
RedHat/Centos 6 support

### ISSUE THREAD

**Issue by pmalek** [git-cola/git-cola#461]
We would like to try out git-cola for our team where we use RedHat/Centos 6.

Is it possible to package it for that distro?

**Comment by davvid** [comment]
I use git-cola on el6 everyday.  You should just need to install the redhat-provided pyqt4 packages and you should be all set.  Clone this repo and you can run in-place, just run the git-cola script in bin/.

If you want an rpm, you can find it on koji. Please see https://koji.fedoraproject.org for rpm packages.

http://koji.fedoraproject.org/koji/packageinfo?packageID=7660

They should install fine on any arch (it's python, platform-independent).  If not, just rebuild the src.rpm.  I'll leave this open if you'd like to mention some of these details in the docs somewhere, or please feel free to close it.

**Comment by pmalek** [comment]
I have tried installing all of those packages:

```
PyQt4-webkit-devel-4.6.2-8.el6.x86_64
PyQt4-webkit-4.6.2-8.el6.x86_64
PyQt4-devel-4.6.2-9.el6.x86_64
PyQt4-4.6.2-9.el6.x86_64
```

and still:

```
git clone https://github.com/git-cola/git-cola.git
...
./git-cola/bin/git-cola
Sorry, you do not seem to have PyQt4 installed.
Please install it before using git-cola.
e.g.: sudo apt-get install python-qt4
```

**Comment by davvid** [comment]
are you using the system python? if so, what happens if you launch it and enter:

    from PyQt4 import QtGui
    import sip

**Comment by pmalek** [comment]
Ok so the issue was that I have 2 `python`s installed on my pc and the packages that are being installed are designed for the one that I don't use every day. After explicitly launching `git-cola` with python that I get the packages for (`PyQt`) it runs fine :)
