### ISSUE TITLE
Interactive rebase does not work under windows

### ISSUE THREAD

**Issue by ThiemoVanEngelen** [git-cola/git-cola#463]
This is caused by the fact that git-cola sets GIT_SEQUENCE_EDITOR to git-xbase in cmds.py, but it is set to the windows path while the variable is used inside a shell script in git which requires linux style paths.

I got it to work by setting GIT_SEQUENCE_EDITOR in my global windows environment and removing the compat.setenv('GIT_SEQUENCE_EDITOR',...) and the compat.unsetenv('GIT_SEQUENCE_EDITOR') from cmds.py.

**Comment by davvid** [comment]
Thanks for the careful diagnosis. Can you show me an example of what the windows path looks like, and what the linux path should look like?  is it,

    C:/Program Files/share/git-cola/bin/git-xbase

which should instead be

    /c/Program Files/share/git-cola/bin/git-xbase

?  If so, we can probably do a platform check there and have a function that tweaks the variable we emit into the environment.  what do you think?

**Comment by ThiemoVanEngelen** [comment]
Tested by including the merging the changes to cmds.py into my installed version of git-cola.
It now seems to work, although my git-cola is not installed in "Program Files (x86)" and I don't know for sure if these spaces give problems.

**Comment by davvid** [comment]
Thanks.. I'm not actually hard-coding any paths, just doing a conversion :-) thanks for testing, and thanks for the report.

**Comment by loehnertj** [comment]
Fails with network paths!

Cure: in cmds.py:

    def unix_path(path, is_win32=utils.is_win32):
        """Git for Windows requires unix paths, so force them here
        """
        unix_path = path
        if is_win32():
            first = path[0]
            second = path[1]
            if second == ':':  # sanity check, this better be a Windows-style path
                unix_path = '/' + first + path[2:].replace('\\', '/')
    +        else:
    +            unix_path = path.replace('\\', '/')

        return unix_path

**Comment by davvid** [comment]
Nice catch @loehnertj I just pushed up a fix.  Let me know if that works for you.
