### ISSUE TITLE
Ask for confirmation before staging unmerged file containing markers

### ISSUE THREAD

**Issue by albertdev** [git-cola/git-cola#464]
A feature request: everyone has it happen every few times that they're dealing with some Unmerged changes.

Sometimes I do make the mistake of double-clicking such a file in git-cola, which will automatically stage it with these markers:

    <<<< HEAD
    ====
    >>>> Updated / Stashed

Unstaging won't put it back in the "Unmerged" state though, meaning that I can no longer call `git mergetool` through the CLI or git-cola and I need to undo all those markers by hand.

Since I don't think git allows to put a file back to the Unmerged state, could git-cola detect that a file still has markers and ask the user for confirmation or even give the third option of opening the mergetool?

**Comment by albertdev** [comment]
Ping! No comments on whether this is a good idea or at all possible?

**Comment by davvid** [comment]
This is a great idea. It's totally possible.  When implementing, please make sure to also consider the "diff3"-style conflict markers, which are enabled by `git config merge.conflictstyle diff3`.

http://psung.blogspot.com/2011/02/reducing-merge-headaches-git-meets.html
