### ISSUE TITLE
Add "Launch Diff Tool" option to DAG viewer

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#468]
Just like the main window allows for viewing changes to an individual file in an external diff viewer, it would be nice to be able to view changesets in an external diff viewer (i.e. using `git difftool -d ...`  mode). There would be two ways of using this feature:

- Select a single commit (either in the Log or the Graph view), then right click to get a "Launch Diff Tool" context menu option (or just use `Ctrl-D` shortcut). This would show the differences between the selected commit and its parent (`git difftool -d xxxxxxx^..xxxxxxx`)
- Select two commits by holding Ctrl and selecting two commits (either in the Log or the Graph view), then right click to get a "Launch Diff Tool" context menu option (or just use `Ctrl-D` shortcut). This would show the differences between the two selected commits (`git difftool -d xxxxxxx..yyyyyyy`)

Related side note: selecting two commits in the Log view is currently broken for me - holding Ctrl while clicking multiple commits behaves as if I where holding Shift.

**Comment by davvid** [comment]
Sounds like  good idea.  Right now the log view should work for diffing commits by clicking one, and then, without trying to select it, just right-click a different commit.  Like gitk, it should have "Diff selected -> this", and vice versa in the context menu.

**Comment by feinstaub** [comment]
What about adding a new button "Show in external diff tool" to the embedded diff viewer? So by default one would see the diff in the embedded viewer and when this is not enough the external one can be launched.

**Comment by davvid** [comment]
That sounds like it'd be pretty useful.

**Comment by nocnokneo** [comment]
I agree - sounds like a good idea. It goes against git-cola's current UI pattern a bit (minimal buttons; most operations accessed by context menu or keyboard shortcut) but I'd still say it makes sense here.

**Comment by nocnokneo** [comment]
Cool, thanks. Although I was hoping to get a directory diff (`git difftool -d ...`) somehow. Could we add a "Compare All" button to the "git-cola diff" dialog?

**Comment by davvid** [comment]
I'll take your "Compare All" button and raise you a `Ctrl+Enter` hotkey (for that dialog) and a standalone `Ctrl+Shift+D` hotkey for launching dir-diff via git-dag.

**Comment by nocnokneo** [comment]
Sweet!
