### ISSUE TITLE
git-cola does not push

### ISSUE THREAD

**Issue by mase-tech** [git-cola/git-cola#469]
Hi peps,

I got this problem.... I cannot push...

git push" returned exit status 128

Have you rebased/pulled lately?

Already up-to-date.

Versende nach https://github.com/mase-tech/FreeCAD-LEGO.git
/home/creep/git-cola/git-cola/share/git-cola/bin/ssh-askpass: 3: exec: wish: not found
error: unable to read askpass response from '/home/creep/git-cola/git-cola/share/git-cola/bin/ssh-askpass'
fatal: could not read Username for 'https://github.com': No such device or address

I think it has something to with the lack of not be able entering a password

**Comment by davvid** [comment]
That is correct.  Do you have tcl/tk (wish) installed?  We use the `share/git-cola/bin/ssh-askpass` program to ask for the password.  It looks like it can't find "wish" in your path.

    sudo apt-get install wish

**Comment by mase-tech** [comment]
I will try your suggestion. I hope it works, because I like git-cola (very nice gui).

So ssh is needed. That means a further use "git-cola" and https is not supported yet (as i understand right).

So I have to create a ssh key. AM I right ?

**Comment by mase-tech** [comment]
HEy davvid,

thx your suggestion solved the problem. 

VERY easy and nice
