### ISSUE TITLE
windows installer multiple issues

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#471]
The Windows installer has multiple issues compared to installing cola by cloning the repository and running build.py:

There's no git-cola(.pyw) and git-dag(.pyw). The git-cola.launch.pyw script always goes straight to repo open screen, ignoring whether working directory is a git repo

Installing into existing directory, such as previous git-cola installation, causes installed files to be skipped rather than overwritten, silently.

It should install pywin32 for file notification support but it doesn't.

**Comment by davvid** [comment]
@takluyver do you think these would be easy fixes?

**Comment by takluyver** [comment]
- Entry points: right, I hadn't thought about using it from the command line in Windows. It's probably easy to make the `.launch.pyw` script respect the working directory. Installing a `git-cola.cmd` or similar should be possible with a custom template, though I don't quite know where the best place to put it is.
- Overwriting existing files: hmm, that's a bit troubling. I assumed NSIS would default to overwriting files. I'll try to look into this, but it will be a few days before I'm back at my Windows VM to test.
- pywin32: that should be easy, but IIRC pywin32 generates some of the modules at runtime, so it might necessitate building the installers on Windows (when the application runs, it won't have write access to its own directory, so those files need to be generated before building). Maybe that's only for win32com, though?

**Comment by sthalik** [comment]
@takluyver the "git-cola" and "git-dag" modules are fine to launch with Windows pythonw.exe. They could be included in the Windows distro.

Perhaps pywin32 stuff is ABI-compatible when generated on a different system using the same Python. I'm unfamiliar with the issue though. There's the option of bundling a stipped-down version for cola's purposes only.

**Comment by nocnokneo** [comment]
> pywin32 generates some of the modules at runtime, so it might necessitate building the installers on Windows

In theory this should be possible with the mingw packages in Ubuntu, but the details of reality may get in the way.

**Comment by collinsmichael** [comment]
Any update on fixing this broken approach to windows installation? The current suggestions from the readme are utterly broken.

**Comment by takluyver** [comment]
Pynsist grew the ability to install command line commands since the last round of discussion ([see docs](http://pynsist.readthedocs.io/en/latest/cfgfile.html#command-sections)). There's a  Pynsist config file in the repository, but it doesn't look like it's being used at the moment.

If anyone wants to play with that, I'd recommend updating it to use Python 3 and PyQt5, which can be fetched from a wheel. [Here's a PyQt5 example](https://github.com/takluyver/pynsist/blob/master/examples/pyqt5/installer.cfg). With this, the `fetch_pyqt_windows.sh` script would not be needed.

**Comment by sthalik** [comment]
Is Python 3 and PyQt5 fully working?

**Comment by takluyver** [comment]
As far as I know, yes. I use Git Cola on Python 3 (though on Linux, not Windows). I'm not sure how to quickly check which Qt module it has loaded - I probably have them all installed.

**Comment by nocnokneo** [comment]
I've been using git-cola with Python 3 and PyQt5 on Windows for about a
year with no problems.

**Comment by davvid** [comment]
Thanks to @takluyver and pynsist I finally got what (seems to be) a sensible, 64bit newly working installer working.  Please test the latest beta release -- it should have resolved these issues.

Also, the instructions with the new installer are much simpler now.  You don't need to install python, pyqt5, or any of that stuff.  Just install "Git for Windows", "Git Cola" and that's it.

**Comment by takluyver** [comment]
:+1: I will take a look at your PRs to Pynsist later on. :-)

**Comment by davvid** [comment]
The latest beta installer now include launcher commands for git-cola and git-dag so I think this issue can be closed now. 

Also, if you're still seeing the "not overwriting existing files" issue then we should open a pynsist issue to look into it.   Thanks for the sugs.

**Comment by nocnokneo** [comment]
Works for me except for file system change monitoring. Does `pywin32` need to be added to the `packages` list in `windows-installer.cfg`?

**Comment by takluyver** [comment]
It's listed in `pypi_wheels` - it shouldn't be necessary to specify it in `packages` as well. But there are some complexities with pywin32 - IIRC it generates modules at runtime, which may be causing issues.

**Comment by nocnokneo** [comment]
@takluyver Thanks. Are file system changes working for you with this new installer?

**Comment by takluyver** [comment]
No idea - I don't use Windows much (despite making a tool for building Windows installers...)
