### ISSUE TITLE
git window appears despite Popen hidden flag

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#477]
Using this distribution <<https://github.com/madhur/msysgit-2.0.0>>, Git window popups on every invocation. That's despite the Popen flag to specifically hide the window.

**Comment by living180** [comment]
I've put it on my to-do list to try to reproduce to figure out why this is happening.  In the meantime, have you looked at trying [Git for Windows](http://git-for-windows.github.io/)?  It is the successor to the [msysGit version](https://msysgit.github.io/) and provides an installer for Git 2.4.5.

**Comment by sthalik** [comment]
Thanks for the "Git for Windows" link.

I can reproduce this also with this Git distribution.

**Comment by sthalik** [comment]
If you can't reproduce, please note it's a Windows 10 machine where this behavior is observed.

**Comment by living180** [comment]
OK, good to know. Are you able to run git-cola from the standard Windows command prompt to see if it happens in that case? If so, it is probably a Windows 10 issue and I'll have to look into the Windows 10 documentation to see if I can figure out a solution.

**Comment by sthalik** [comment]
There's no stderr or stdout when dag is run from console.

**Comment by sthalik** [comment]
Same thing happens on Windows 7. I begin to think it has to do with this particular Git distribution. I use Git for Windows' git binary from "cmd/" subdirectory.

**Comment by sthalik** [comment]
@living180 see #486

**Comment by living180** [comment]
Your PR looks good to me. Sorry I haven't had time to look at this - I've basically been on the road the entire last month.
