### ISSUE TITLE
QNativeImage: Unable to attach to shared memory segment. 

### ISSUE THREAD

**Issue by Azd325** [git-cola/git-cola#482]
I use arch in a VBOX.

```bash
~/p/m/m () $ git cola
QNativeImage: Unable to attach to shared memory segment. 
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
```

**Comment by Azd325** [comment]
Works with after update to v2.2.1

**Comment by dxli** [comment]
I still have gray window problem, causing the whole window to be grey, and can not read anything.

I'm not using vbox. Just running Gentoo/Linux.

Is there an easy way for me to troubleshoot?
![screenshot from 2015-09-18 16-37-55](https://cloud.githubusercontent.com/assets/827425/9970533/a6446a56-5e23-11e5-9e1e-7276ab261203.png)


```
$ git cola version
cola version 2.3
$ git cola 
QNativeImage: Unable to attach to shared memory segment. 

(python3.3:21255): Gdk-WARNING **: shmget failed: error 28 (No space left on device)
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
```

**Comment by davvid** [comment]
@dxli are you low on memory or hard disk space? The error message is from the kernel and says that shared memory allocations are failing.

As a curiosity, you could try running it on python2. That might not make any difference but it might if there's a bug in one of the lower-level libraries.

The icons in your screenshot are the older icons. Try the latest from git too ;-)

**Comment by davvid** [comment]
if profiling finds that cola is using lots of memory then I'd definitely be interested in looking at ways to minimize it, but hopefully this is something else.

**Comment by dxli** [comment]
@davvid please do not spend your time on this, unless you are convinced it's a git-cola issue. I asked in hope the answer was already known to you, based on troubleshooting the particular issue at git-cola side.

I'm pretty sure this is not a cola bug, because I got similar bug (shmget error 28) for LyX also. I think it's something wrong with either Qt or kernel, since I'm running gentoo, hard to figure out.

I actually got the same bug with python-2.7 and 3.3, and I switched from 2.7 to python-3.3, hoping python-3 might help.

The system is low on memory or hard drive space;

```
 $ free -m
              total        used        free      shared  buff/cache   available
Mem:           7537        2612        2512         353        2412        4474
Swap:          1023         271         752

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       120G   53G   63G  46% /
devtmpfs        3.7G     0  3.7G   0% /dev
tmpfs           3.7G   23M  3.7G   1% /dev/shm
tmpfs           3.7G  1.2M  3.7G   1% /run
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
none            3.7G  472K  3.7G   1% /tmp
/dev/sdb1       238G  110G  127G  47% /home
tmpfs           754M   28K  754M   1% /run/user/1002
```

Thank you!

**Comment by harumaki** [comment]
I can reproduce this problem with any Qt application when a Java Swing application is running. 
It seems that OpenJDK is eating all shared memory.

**Comment by dxli** [comment]
I can confirm this is a problem of the current openjdk 7, upgrade to oracle-jdk (java8), or downgrade to openjdk 6:

[openjdk 7 leak](https://bbs.archlinux.org/viewtopic.php?id=201488)

**Comment by Azd325** [comment]
Thanks @dxli for the information. I upgraded to openjdk-8 on my arch and it works now for me again.

**Comment by tienhm0202** [comment]
When I type
`java -version` it returns:
```
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

And `git cola` still get error:
```
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
```

**Comment by Azd325** [comment]
This is mine
```
~/p/kenhub (4650-trainer-redesign) $ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Do you have also 1.7 on system?

**Comment by ArcoOost** [comment]
I had this problem with git-cola and tortoisehg (thg) as well after receiving an update in ubuntu 15.04. I found this link: https://ercpe.de/blog/error-unable-to-attach-to-shared-memory-segment-after-upgrading-qt

At the bottom it says to include QT_X11_NO_MITSHM=1 .

Starting git-cola as: QT_X11_NO_MITSHM=1 git-cola works for me. I have added this variable to my ~/.profile

**Comment by tienhm0202** [comment]
`QT_X11_NO_MITSHM=1` is worked for me, thanks @ArcoOost 

@Azd325 I have also 1.7 on system

**Comment by davvid** [comment]
Please also report this bug upstream to Ubuntu.

Setting that variable makes the window redraws slower on my debian/sid laptop, so it's possible that you have reduced redraw performance for all qt apps due to the broken mit-shm x11 extension. It could be a wayland thing, though, too, I dunno, so it's best to at least bug upstream about this.

**Comment by The-Compiler** [comment]
This looks like this issue with OpenJDK7: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799587

I had this with another application, and it went away after I closed a java application which was open.

**Comment by Mingun** [comment]
I can confirm, that `QT_X11_NO_MITSHM=1` not fully worked, at least for some Qt applications (I not tested git-cola). Some Qt windows after apply this fix looks fine, but some still not. Also, this bug appeared also in Java8. Versions:
```sh
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```
Qt 4.8.6

Besides, not all Java Swing applications cause this bug. For example our Swing application not cause this bug, but SQLDeveloper does.
