### ISSUE TITLE
Copy and paste only works when git-cola is open?

### ISSUE THREAD

**Issue by joshuataylor** [git-cola/git-cola#484]
So I want to copy something out of git-cola, so I CTRL+C (or right click, copy), then copy it elsewhere. Cool, all works.

I then close git-cola, and try and paste the same thing elsewhere, and it has cleared the copy/paste clipboard? This happens on Ubuntu 15.04, running XFCE.

edit: I'm also running the latest master.

**Comment by Vdragon** [comment]
Please refer <https://wiki.ubuntu.com/ClipboardPersistence> if this is your problem.

**Comment by davvid** [comment]
I think I found a (workaround?) we can use to make this work.  Thanks for the heads-up.

**Comment by joshuataylor** [comment]
:+1: , you two are awesome.

Didn't know about that clipboard persistence bug, how annoying! @davvid , confirmed that this fixes the issue, awesome!
