### ISSUE TITLE
sphinx-build: No such file or directory

### ISSUE THREAD

**Issue by ScreenDriver** [git-cola/git-cola#489]
I wanted to install git-cola on Mac OS X. I followed the [instructions](https://github.com/git-cola/git-cola#mac-os-x) but unfortunately I get the following error:

```sh
make[2]: sphinx-build: No such file or directory
make[2]: *** [html] Error 1
make[1]: *** [install-doc] Error 2
make: *** [git-cola.app] Error 2
```

**Comment by Vdragon** [comment]
@ScreenDriver It seems that you haven't install Git Cola's build dependency, Sphinx Python component

**Comment by Vdragon** [comment]
I wondered if this should be mentioned in the project's [homepage](https://github.com/git-cola/git-cola)...

**Comment by ScreenDriver** [comment]
How can I install `Sphinx Python`? Brew did not find it:

```sh
$ brew search sphinx python
cmu-pocketsphinx    cmu-sphinxbase	sphinx
homebrew/php/libsphinxclient	 homebrew/php/php54-sphinx	  homebrew/php/php56-sphinx
homebrew/php/php53-sphinx	 homebrew/php/php55-sphinx
```

And yes this should be mentioned. I believe that almost everyone run into the same issue as I do here :wink:

**Comment by davvid** [comment]
If you got this far you don't need to worry about the sphinx parts.  Just run `bin/git-cola` and it should work.  The pyqt dependencies should be available in /usr/local.

**Comment by ScreenDriver** [comment]
Ok. But why is there no simple application that I can launch from within my finder window like every other application? I don't understand why I should install git-cola via brew in the first step and in the second step I should clone and build it mentioned [here](https://github.com/git-cola/git-cola#mac-os-x)?

**Comment by davvid** [comment]
Simple reason: disk footprint.  The biggest parts of git-cola are really our dependencies.  Qt and PyQt are the bulk of what would constitute a self-contained app if we were to build one, and re-uploading those libraries every time would be a waste of time and bandwidth for downloaders and, most importantly, me.

The `make git-cola.app` target builds just the git-cola parts, which are much smaller. It really only makes sense to update those parts.

Anyways, I was reading the sphinx docs and it seems like, for osx, you really should just use `pip install sphinx` to get sphinx-build installed.  That probably means using sudo.  homebrew does not package sphinx, and their webpage mentions macports, but let's not go there.

I'll update the readme to mention the pip install step in the osx section.  Package management is a bit of a wasteland on OS X, unfortunately.

**Comment by ScreenDriver** [comment]
That's true. `homebrew` for the rescue but unfortunately `brew` can't deal with updates very well :disappointed:

**Comment by davvid** [comment]
Closing for now.. let me know if the `pip` thing didn't work out so we can update the instructions accordingly. Hopefully that did the trick.  Thanks for the heads-up.
