### ISSUE TITLE
Docked browser does not refresh when I switch repositories

### ISSUE THREAD

**Issue by djhaskin987** [git-cola/git-cola#490]
I have two repositories in my favorites list, say `a` and `b`. I open up git cola with `a`, and the (dockable) browser displays files as normal from `a`. Then I double-click the `b` repository in the favorites list. The browser does not update what files it displays. Hitting "refresh" in the actions lists does nothing.

**Comment by davvid** [comment]
This was already fixed recently.  Please try what's currently sitting in `master`.

**Comment by djhaskin987** [comment]
Thanks!
