### ISSUE TITLE
[enhancement] status: preserve horizontal scroll across updates

### ISSUE THREAD

**Issue by StanAngeloff** [git-cola/git-cola#494]
This is related to #178. I tried to solve it again, but failed to do so. This has really been annoying me on projects with long directory paths. If the status widget is not wide enough to fit a filename, a horizontal scroll bar will appear. Scrolling to the right to reveal the filename and then selecting a different file from the list resets the horizontal scroll position.

![Demo](http://i.imgur.com/pG09L5y.gif)

**Comment by davvid** [comment]
Ugh, I tried making this work but it looks like Qt is doing something automatically when the item is clicked.  I'd like to get this working if possible.  I hope there's a way to do it..

**Comment by StanAngeloff** [comment]
Same here, I thought I nailed it in #178 and then gave it another go a month ago, still not found what's causing it. Bummer.

**Comment by davvid** [comment]
I think I found a crucial missing ingredient.. `self.setAutoScroll(False)` and then a few extra bits to store/restore the horizontol scroll.  I think I should have something shortly...

**Comment by StanAngeloff** [comment]
Works great! :star2: All I need to do now is unlearn to use the scroll wheel after each click.

**Comment by PetrGlad** [comment]
There is a problem with this behavior: if you scroll right to see ends of long paths and then scroll vertically to files closer to project root then items will look empty.
