### ISSUE TITLE
"Create branch" dialog does not populate "Branch Name" correctly when selecting a remote branch with slashes in the name

### ISSUE THREAD

**Issue by djhaskin987** [git-cola/git-cola#496]
# Steps to Reproduce
1. `Branch > Create Branch...`
2. Select the `Tracking branch` radio button.
3. Select a remote branch with a forward slash (`/`) in the name. For example, `origin/feature/my-feature-branch`.

# Problem
When these steps are completed, I expect to see the "Branch Name" text field populated with "feature/my-feature-branch". Instead, it is populated with "my-feature-branch". This does not track with `git checkout feature/my-feature-branch`, which creates a branch called `feature/my-feature-branch` that tracks the branch of the same name from the remote `origin`.

**Comment by davvid** [comment]
I was thinking about this the other day. The fix should be simple.. give me a sec... thanks for the report.

**Comment by mathstuf** [comment]
I'm going through old emails and came across one for git-cola and saw this commit at the top when I decided to pop back in and see how it's going :) . So, remotes can also have '/' in the name (e.g., I name github remotes `gh/$username`). I don't know if git exposes a tool to split the remote from the branch name or not, but it's another corner case.

**Comment by davvid** [comment]
I just pushed an additional safeguard that allows for slashes in remote names too.  You can have slashes in branches and remotes, no problem.  See 34d68536839fcd809c70fc0041c74c85a584fa4d

**Comment by djhaskin987** [comment]
Yay! Thanks. Rebuilding.
