### ISSUE TITLE
Feature Request: side scroller or hand tool for the DAG

### ISSUE THREAD

**Issue by djhaskin987** [git-cola/git-cola#500]
When I zoom in to the DAG, sometimes the branch name gets off screen because I have to zoom in far enough to read the branch name, but the branch name is too long to fit inside the window. When I zoom out to fit the branch name in the window, it's too small; I can't read it. Or, sometimes multiple branches track to the same commit, and I can't see which ones there are because when I zoom out to include all branch names, I can't read them.

This could be fixed by a side-to-side scroll bar or a hand tool, so that when I zoom in, I can move the DAG around side to side so that I can scroll over to see the full name of the branch, or all the branches that track to the same commit.

**Comment by systemovich** [comment]
:+1:

**Comment by davvid** [comment]
There should be a scrollbar there these days.  Let me know if you're not seeing it.  The arrow keys should also pan the view around.
