### ISSUE TITLE
merge done by git-cola incorrect one-liner

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#508]
The one-line message on the commit list is wrong/unusual.

![image](https://cloud.githubusercontent.com/assets/1896811/10336406/cc4acb62-6cf8-11e5-86fd-d26ec0d72d1d.png)

Might be caused by

<pre>[merge]
        log = 75
</pre>

**Comment by sthalik** [comment]
Shows the same with git-forest, might be the actual merge generated by Cola having incorrect message. Normally merge looks like:

> Merge branch 'unstable' into trackhat-ui──(c3fef33)

But the one I did with cola looks like:

> * unstable:   qfc: increase precision──(95080ba)

**Comment by davvid** [comment]
This was worth fixing for 2.4, so I think I just merged the last topic and will be releasing v2.4 shortly.  This merge was done with the fix. Please test it if you can in case I goofed ;-)  Thanks for the report.

**Comment by sthalik** [comment]
Gives the following commit message

<pre>
commit 4f5439ff0427e5061c07d91c2f5b2e803695533f
Merge: fd8843b 16b12d9
Author: Stanislaw Halik <sthalik@misaki.pl>
Date:   Sun Oct 11 11:47:34 2015 +0200

    Merge branch 'aa' into unstable

    * aa:
      xccc
      v
</pre>

Should be good, thanks.
