### ISSUE TITLE
[feature] Spell check commit summary

### ISSUE THREAD

**Issue by StanAngeloff** [git-cola/git-cola#518]
The commit extended description (large box, second one in screenshot) already has spell checking enabled.

Is it possible to have the same enabled for the commit summary (short box, first one in screenshot)? Is it a Qt limitation?

![](http://i.snag.gy/deNZW.jpg)

**Comment by StanAngeloff** [comment]
I've messed about with my local copy of git-cola and it appears to not be as trivial as I had hoped. Changing `CommitSummaryLineEdit` to inherit from `SpellCheckTextEdit` and a few more changes renders and works as expected. However this introduces issues on its own, e.g., newline can be entered in the commit summary (or copy -> pasted). The validator has to be re-implemented.

Any better ideas?

**Comment by davvid** [comment]
This came up before. It's a Qt limitation.  Feel free to dig at it, but it's a non-trivial problem (I already wasted time on it, not making that mistake again!)
