### ISSUE TITLE
Don't include the extended description when selecting a commit to fixup

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#522]
Is there any value in including the extended description when selecting a commit to fixup? My preference for fixup commits is describe only what is being "fixed up". When I decide to squash (i.e. replace `fixup!` with `squash!` in the commit summary) then I definitely don't want the previous extended description. Maybe there are workflows that actually make use of these extended descriptions? If so, then it probably makes sense to keep them since deleting the extended description (Ctrl+a, Delete) is a lot easier than manually adding it in.

**Comment by davvid** [comment]
I think we should remove the extended description from there.  Only the subject line matters, and we should match what `git commit --fixup <sha1>` does by using just `fixup! <subject>` as the message.

**Comment by nocnokneo** [comment]
Sounds like a good rationale to me.

**Comment by nocnokneo** [comment]
Thanks!
