### ISSUE TITLE
UnicodeDecodeError when "View History..." is triggered in File Manager and gitk isn't installed and zh_TW locale is used

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#529]
Similar with #528 but reproduces in File manager

## Traceback
```
Traceback (most recent call last):

  File "/usr/local/share/git-cola/lib/cola/cmds.py", line 1810, in do_cmd
    return cmd.do()

  File "/usr/local/share/git-cola/lib/cola/cmds.py", line 1738, in do
    launch_history_browser(self.argv)

  File "/usr/local/share/git-cola/lib/cola/cmds.py", line 1763, in launch_history_browser
    _, details = utils.format_exception(e)

  File "/usr/local/share/git-cola/lib/cola/utils.py", line 38, in format_exception
    details = '\n'.join(details)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 19: ordinal not in range(128)
```

**Comment by davvid** [comment]
I think you must be running the old code.  Line 38 looks like this:
```
    details = '\n'.join(map(core.decode, details))
```
so I think this has already been fixed.  let me know if this is not the case.  thanks for the heads-up.

**Comment by Vdragon** [comment]
@davvid I've pulled, rebuild, and re-install Git Cola before reproducing so it should be the latest code...
Maybe we can add a Git clean/smudge filter to add commit SHA-1 hash to the about screen to clarify the actual revision Git Cola is running...?

**Comment by Vdragon** [comment]
**UPDATE**: I've uninstalled, cleaned, maked and reinstalled Git Cola and can't reproduce the same issue, it seems just something's wrong in my previous reproduce.
