### ISSUE TITLE
Stuck pushing, UI freezes

### ISSUE THREAD

**Issue by joshuataylor** [git-cola/git-cola#540]
Hello!

For the last few months, when pushing to a slow remote, after pushing is finished the UI will freeze:
http://i.imgur.com/hNJrDhu.png

Is there a way I could enable verbose logging, this way I could provide a log file.

My environment is Ubuntu 15.04, running XFCE, Desktop compositing should be disabled.

**Comment by Vdragon** [comment]
Please refer issue #377

**Comment by joshuataylor** [comment]
Closed due to duplicate.
