### ISSUE TITLE
Changes sometimes are not highlighted in diff preview with diff.suppressBlankEmpty = true

### ISSUE THREAD

**Issue by Coacher** [git-cola/git-cola#541]
Hello.

Subject says it all.

Here are the steps to reproduce this (on Linux):
```
$ git init
$ echo -e '\n\n123\n\n'>file.txt
$ git add file.txt
$ git commit file.txt -m 'Initial commit'
$ echo -e '\n\n456\n\n'>file.txt
$ git-cola
```

System info:
git is 2.7.0. git-cola is built from master at 1ed741e275fde74382c86579c59dd5a2dca73e23.

Please fix.

**Comment by davvid** [comment]
Nice catch, thanks for the report.  This should be easy.

**Comment by Coacher** [comment]
Thank you for the quick fix.
