### ISSUE TITLE
Support reverting a previously created commit

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#542]
As title.

**Comment by davvid** [comment]
Currently the `Unstage All` action effectively does a `git reset -- .`.

Are you interested in the other `reset` flavors, specifically the `git reset --merge <SHA1> --` operation?

**Comment by Vdragon** [comment]
@davvid I'm interested with reverting a previously created commit

**Comment by davvid** [comment]
Ah, that would be very useful.  This should be straightforward to add to Actions and DAG.

We could do `git reset --mixed <SHA1> --`
The `git reset --soft` mode is kinda interesting, but probably not something we need.

Maybe we can use a string in the interface like, "Reset branch head to commit (git reset --mixed)"
What do you think?

**Comment by Vdragon** [comment]
> We could do git reset --mixed <SHA1> --
> The git reset --soft mode is kinda interesting, but probably not something we need.
> Maybe we can use a string in the interface like, "Reset branch head to commit (git reset --mixed)"
> What do you think?

@davvid That's great, maybe provide `--hard` mode as well would also be useful.
