### ISSUE TITLE
windows downloads missing...

### ISSUE THREAD

**Issue by jedie** [git-cola/git-cola#543]
On https://github.com/git-cola/git-cola/releases the newest release downloadable for windows is v2.3

https://git-cola.github.io/downloads.html pointed to https://github.com/git-cola/git-cola/releases/download/v2.5/git-cola-2.5.windows.zip with doesn't exist :(

**Comment by davvid** [comment]
Oh, I know why my workflow that I setup way back in 2013 when they announced this https://github.com/blog/1547-release-your-software suddenly stopped working.

Dec. 5th passed, and thus https://github.com/blog/1302-goodbye-uploads

The API I relied on for uploading the zips went away.  We'll start hosting zip files on the github.io site shortly. I have to update my scripts now. :-/

**Comment by Vdragon** [comment]
@davvid I belive the GitHub API to upload release assets are still available, maybe we should use it if it satisfies our needs?
<https://developer.github.com/v3/repos/releases/#upload-a-release-asset>

Also the feature specifies in <https://github.com/blog/1302-goodbye-uploads>(2012) seems to be different than the feature in <https://github.com/blog/1547-release-your-software>(2013), so the goodbye-feature post doesn't applies to GitHub Releases Assets...?

**Comment by davvid** [comment]
You're totally right.  Time to update the load script again ;-) turns out I just need to tweak a few things to support v3 of the API.  Thanks for the heads-up.
