### ISSUE TITLE
Show the diff of two revisions

### ISSUE THREAD

**Issue by feinstaub** [git-cola/git-cola#552]
CURRENT SITUATION:
To view the diff of two revisions, I currently got to View -> DAG...

The embedded diff viewer always shows the diff between the selected commit and the previous one.

To view the diff of two user-selected commits, one can use the context menu and choose "Diff this -> selected". The result (list of filenames) is shown in an extra dialog.

SUGGESTION:
Is it possible to show the diff in the embedded diff viewer? Because there, it is much easier to get a quick overview of the total diff across multiple files.

**Comment by feinstaub** [comment]
see also https://github.com/git-cola/git-cola/issues/468

**Comment by jm4R** [comment]
@davvid Can git-dag show a diff between 2 randomly-selected revisions like author suggested? I don't see such option. Selecting 2 commits on the list shows diff between last-selected and previous one...

**Comment by davvid** [comment]
It won't display in the embedded diff view, but you can inspect diffs between any arbitrary two commits by clicking on the first commit (in the node view) and the right-clicking on the second commit. I believe this works with the list widget as well -- if one is selected and then a 2nd item is right-clicked then menu items will allow you to diff between the two.

**Comment by davvid** [comment]
In addition to the new "Diff Mode" I just modified the DAG viewer so that it displays an inline diff between the start and end commits when multiple commits are selected.
