### ISSUE TITLE
Linked working trees no more recognized

### ISSUE THREAD

**Issue by weo** [git-cola/git-cola#554]
In 3a5c09f git-cola doesn't recognize a linked working tree anymore. The menu to select a repo is shown instead.

I bisected the problem and found that bea1333 might introduce the problem.

**Comment by davvid** [comment]
Interesting. I'm not familiar with "linked working trees".  Can you explain how to recreate this kind of setup?  I'm sure we can make this work again.

**Comment by weo** [comment]
A repository can have multiple worktrees. You manage them with "git worktree". In such a "secondary" (or "linked") worktree, ".git" is just a file with a pointer to its own ".git" directory within the repository's ".git" directory.
