### ISSUE TITLE
GNOME Files(Nautilus) integration

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#555]
Currently it seems that only MS Windows has Git Cola shell integration, this issue is for adding support for GNOME Files(previously named Nautilus) as well.

**Comment by davvid** [comment]
`share/applications/git-cola-folder-handler.desktop` is in place to handle this feature.

We currently register for the `inode/directory` mimetype.  In Gnome, I right-click on a directory and choose "Open With Other Application".  A dialog is presented where "Git Cola" can be chosen.

I wish I could have an action available in the immediate right-click menu without having to go through the dialog, similar to the "Open in Terminal" action  I'm not exactly sure how to make that happen.

Comparing the two `.desktop` files, there doesn't seem to be much of a difference between them, so I'm not sure how gnome handles the menu.  Is gnome-terminal special-cased?  Does it require writing an extension to change the right-click menu?

`git-annex`, for example, installs scripts into `~/.local/share/nautilus/scripts`, which provide a sub-menu where the user can select `git annex add`, etc.  We could, for example, add a script for opening cola.  Is that what you had in mind?

**Comment by Vdragon** [comment]
My expectation is the same with Windows platform, same with the "Open in Terminal" action in Nautilus.

Currently Dolphin FM also supports the "Open with Other Application" scheme:
![screenshot_20180313_133557](https://user-images.githubusercontent.com/1192163/37324281-98818de8-26c3-11e8-9652-4456079dc301.png)

**Comment by Vdragon** [comment]
The seems-to-be-merged-to-the-upstream nautilus-open-terminal is implemented as a Nautilus extension using the C extension api AFAICT from the [outdated package source](http://archive.ubuntu.com/ubuntu/pool/universe/n/nautilus-open-terminal/nautilus-open-terminal_0.20.orig.tar.xz).

**Comment by Vdragon** [comment]
This might be rather helpful: https://wiki.gnome.org/Projects/NautilusPython

**Comment by dev-DTECH** [comment]
I would like to work on this issue.
