### ISSUE TITLE
External diff tool setting is ignored

### ISSUE THREAD

**Issue by vgsuvi** [git-cola/git-cola#560]
I changed the diff tool path in the settings, but git-cola still uses KDiff3 to show diffs.

**Comment by davvid** [comment]
what "path" did you enter?

that config variable is the tool name, not a path.  custom tools must be registered with git difftool. 

built-in tools include meld, xxdiff, etc

https://git-scm.com/docs/git-difftool

**Comment by vgsuvi** [comment]
Ah, gotcha.  It works now.  Thanks.
