### ISSUE TITLE
interactive rebase broken on win32

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#573]
Selecting `Rebase -> Start interactive rebase` on win32 results in a message of

`exit code 1`

Note that I have an editor configured for Ctrl+E on the tree. Perhaps there's a need for a terminal command on win32 (like mintty or cmd.exe).

**Comment by living180** [comment]
I am able to reproduce this.  The problem for me, at least, is that I run `git-cola` using my normal Windows Python installation.  However, when git invokes `share/git-cola/bin/git-xbase` (from the `GIT_SEQUENCE_EDITOR` environment variable), it uses the Python from the git environment, which does not have PyQt4, which causes the script to fail.  I'm not sure if this is the same issue you are hitting or not.  I'm playing around with some solutions, but don't have a viable fix just yet.

**Comment by sthalik** [comment]
Hey,

`dash` from MSYS2 invokes native python when the path is appended. Is `PYTHONHOME` et al significant here?

**Comment by sthalik** [comment]
I can send a pull request if you point me to the right file or function.

**Comment by davvid** [comment]
If there are multiple python interpreters then maybe we can use `sys.executable` when constructing the rebase editor string so that we can ensure that the same interpreter is used?

I think `git` itself might be manipulating `$PATH` internally so that might explain why a different python is used after being executed via `git`.

**Comment by sthalik** [comment]
git adds a `libexec`-like directory to `PATH`. There's nothing there but git subcommands. Merely using a sensible `PATH` when calling git is enough.

**Comment by davvid** [comment]
I pushed up a solution that ensure that `sys.executable` is used to launch the `git-xbase` script.  Can you please try it out and let me know if it fixes your reproducible case?

We can reopen this issue if the fix I pushed up wasn't sufficient.

**Comment by sthalik** [comment]
Unfortunately I can't reproduce the issue anymore on the old revision.

**Comment by BinToss** [comment]
### This issue has returned, it seems.
![image](https://user-images.githubusercontent.com/7243190/124557950-f22e2f00-ddee-11eb-9797-ea2b0ae442c3.png)

### Git Cola version info
- Git Cola version 3.9 (v3.9) 
- Windows-10-10.0.22000-SP0 
- Python (D:\Apps\git-cola\Python\pythonw.exe) 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] 
- Git 2.32.0.windows.1 
- Qt 5.14.2 
- QtPy 1.9.0 
- PyQt5 5.14.2

**Comment by davvid** [comment]
I'll have to take a look at the installer. That shouldn't be in the root directory. Usually it's in bin/ (or in Scripts/ on Windows.. can't recall so I'll have to double-check).

Which folder is the `git-cola` script in? It should be in the same one as that.. Is there a `bin` dir?

**Comment by davvid** [comment]
This was a fallout of 44ac5094ad6f1c81abd21085d52fb51e7e3f3d87 where we promoted the `git-cola-rebase-editor` up into the `bin/` directory. This has been updated to support Windows and is part of `v3.10`.

https://github.com/git-cola/git-cola/releases/tag/v3.10

**Comment by BinToss** [comment]
Ah, excellent. Thank you!
