### ISSUE TITLE
"Generate patch" option in the DAG window doesn't support non-ASCII filename

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#580]
As the following screenshot, all non-ASCII characters from the commit title are truncated:

![_010](https://cloud.githubusercontent.com/assets/1192163/16545949/3c784d5e-416c-11e6-823b-0efac8704acd.png)

**Comment by davvid** [comment]
Interesting. I'm guessing you're just using the cola feature to export patches.  cola in turn calls out to `git format-patch`, which is probably the one that's filtering the string to make it "filename safe".

This looks like an upstream Git issue, and they can probably help guide us through how to fix it. Would you mind starting a thread on the `git@vger.kernel.org` mailing list and seeing what they have to say?

Changing the behavior may not qualify for "default behavior" status, but we may be able to add an opt-in `.gitconfig` option that allows us to have better file names coming out of `git format-patch`.

**Comment by Vdragon** [comment]
@davvid If it's the upstream Git's behavior I'll leave it as-is anyway, it is indeed originally designed for the kernel development which unsafe filename is not sane in the first place.

The `git format-patch` manpage does noted:

```
By default, each output file is numbered sequentially from 1, and uses
the first line of the commit message (massaged for pathname safety) as
the filename. With the --numbered-files option, the output file names
will only be numbers, without the first line of the commit appended.
The names of the output files are printed to standard output, unless
the --stdout option is specified.
```
