### ISSUE TITLE
Cannot delete first character in commit message if follow space or #

### ISSUE THREAD

**Issue by guoyunhe** [git-cola/git-cola#585]
![spectacle bc8140](https://cloud.githubusercontent.com/assets/5836790/17456950/f979e9fa-5bf0-11e6-9ec9-7ac287ce4a88.png)

If I type "B#12" and want to delete "B", I found I cannot delete it by pressing backspace key.

![spectacle ju8140](https://cloud.githubusercontent.com/assets/5836790/17456972/b118d8a0-5bf1-11e6-97ca-9dbebcd8ecd9.png)

If I type "final fix issue 12" and want to delete final, I found I cannot delete the last "f" because it followed by a space.

This is really strange because here is nothing alert me. If the commit message cannot begin with space or #, git-cola should give some notification.

**Comment by Vdragon** [comment]
It might be related to the fix of #383 , or commit 48ef0871

**Comment by davvid** [comment]
I'd say it's actuall working as designed.  You can't start a commit message with `#`.  That's a comment.

**Comment by Vdragon** [comment]
@davvid Git does support `#` leading commit message without changing the CommentChar config, we should enable them or keep but put them into documentation/tooltip.

**Comment by davvid** [comment]
Ah, thanks @Vdragon .  I changed it so that whitespace is now allowed at the front because Git will strip that whitespace.

We still cannot allow the CommentChar to be at the front because Git will drop that line completely when passing the commit message via a file, which cola does under the hood.
