### ISSUE TITLE
Toolbar for often used functions

### ISSUE THREAD

**Issue by guoyunhe** [git-cola/git-cola#586]
I found I use fetch, pull, push functions very often. But using menu is not very convenient. I know here is a widget of action buttons, but the position is not good, button size is small in small window, no icon:

![spectacle hfb938](https://cloud.githubusercontent.com/assets/5836790/17463209/d11e6268-5cc9-11e6-9734-6fdeb2b7f4ca.png)

It is better to add an toolbar like normal KDE and GNOME applications.

**Comment by davvid** [comment]
I just realized that this feature has already been implemented ~ thanks @javierrodriguezcuevas !
