### ISSUE TITLE
git cola ignores editor for rebase rewording

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [git-cola/git-cola#587]
i configured my git to use atom as editor,
that works fine for the normal git cli
however when using git cola rebase -i i get an error about missing gvim (which i indeed have not installed)

im not sure what to provide to help with this issue

im on git-cola-2.5 from nixos-unstable

**Comment by davvid** [comment]
There should be a setting in the preferences page that lets you set the editor for cola. `File menu -> Preferences -> Settings tab`

core command line git uses the `core.editor` config, and it's recommended to use a command line editor for cases like editing over ssh where X is unavailable. 

cola uses the `gui.editor` config, which allows you to have different tools configured.

Let me know if you have any questions. cheers!
