### ISSUE TITLE
Display regression in file browser

### ISSUE THREAD

**Issue by KayEss** [git-cola/git-cola#588]
I've checked HEAD and a couple of tags, and somewhere between 2.2 and 2.7/HEAD the file browser behaviour has changed in a couple of ways.

1. It no longer shows messages (status, last commit etc.) for anything other than the top level of the repository.
2. The name column no longer auto-sizes to accommodate the file name lengths.

There is some other change I can't quite put my finger on in the way that the file refresh happens.

I can have a go at narrowing down the actual commit. Maybe that'll give me a hint about a fix too.

**Comment by Vdragon** [comment]
Mind doing a binary search to find the bad commit?

**Comment by davvid** [comment]
Thanks for the heads-up.  This was a small porting bug when switching over to QtPy. I'll push a fix shortly.

**Comment by KayEss** [comment]
Thanks for fixing that. I can confirm that it's alright in master.
