### ISSUE TITLE
segfault when git-dag is closed under python3

### ISSUE THREAD

**Issue by ohaessler** [git-cola/git-cola#592]
If you use python3 and close git-dag, you get the following segfault:

Starting program: /usr/bin/python3 /usr/bin/git-dag
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 22409.
Detaching after fork from child process 22410.
Detaching after fork from child process 22411.
[New Thread 0x7fffd675b700 (LWP 22412)]
[New Thread 0x7fffce3b3700 (LWP 22413)]
[New Thread 0x7fffcdbb2700 (LWP 22414)]
[New Thread 0x7fffcd3b1700 (LWP 22415)]
[New Thread 0x7fffbf38b700 (LWP 22416)]
Detaching after fork from child process 22418.
Detaching after fork from child process 22419.
[New Thread 0x7fffbe973700 (LWP 22420)]
[New Thread 0x7fffbd00b700 (LWP 22421)]
[New Thread 0x7fffbc80a700 (LWP 22422)]
Detaching after fork from child process 22423.
Detaching after fork from child process 22424.
Detaching after fork from child process 22425.
Detaching after fork from child process 22426.
Detaching after fork from child process 22427.
Detaching after fork from child process 22428.
Detaching after fork from child process 22429.
Detaching after fork from child process 22430.
Detaching after fork from child process 22431.
[New Thread 0x7fffae964700 (LWP 22432)]
Detaching after fork from child process 22433.
Detaching after fork from child process 22434.
[Thread 0x7fffae964700 (LWP 22432) exited]
[New Thread 0x7fffae964700 (LWP 22435)]
[Thread 0x7fffae964700 (LWP 22435) exited]
Detaching after fork from child process 22436.
Detaching after fork from child process 22437.
Detaching after fork from child process 22438.
Detaching after fork from child process 22439.
[New Thread 0x7fffae964700 (LWP 22440)]
[New Thread 0x7fffae123700 (LWP 22441)]
Detaching after fork from child process 22442.
Detaching after fork from child process 22443.
Detaching after fork from child process 22444.
Detaching after fork from child process 22445.
Detaching after fork from child process 22446.
Detaching after fork from child process 22447.
[Thread 0x7fffbc80a700 (LWP 22422) exited]
[Thread 0x7fffbd00b700 (LWP 22421) exited]
[Thread 0x7fffae123700 (LWP 22441) exited]

Thread 6 "QDBusConnection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbf38b700 (LWP 22416)]
0x00007fffeee6740d in QObject::disconnect (sender=0x7fffb0006490, signal=signal@entry=0x0, receiver=receiver@entry=0x7fffb800f210, method=method@entry=0x0)
    at kernel/qobject.cpp:2949
2949        const QMetaObject *smeta = sender->metaObject();
(gdb) bt full
#0  0x00007fffeee6740d in QObject::disconnect(QObject const_, char const_, QObject const_, char const_) (sender=0x7fffb0006490, signal=signal@entry=0x0, receiver=receiver@entry=0x7fffb800f210, method=method@entry=0x0) at kernel/qobject.cpp:2949

```
    signal_arg = 0x0
    signal_name = {d = 0x7fffeeef8ea0 <QArrayData::shared_null>}
    signal_found = false
    method_name = {d = 0x7fffeeef8ea0 <QArrayData::shared_null>}
    method_arg = 0x0
    membcode = <optimized out>
    method_found = false
    res = false
    smeta = 0x7fffea554a40 <QDBusServiceWatcher::staticMetaObject>
    signalName = {d = 0x7fffeeef8ea0 <QArrayData::shared_null>}
    signalTypes = 
        {a = 10, s = 0, ptr = 0x7fffbf38ac80, {array = "\002\000\000\000\000\000\000\000\000\357\327\344\302x@\030\001\000\000\000\000\000\000\000\020\372\000\270\377\177\000\000\002\000\000\000\000\000\000\000x\000\000\270\377\177\000\000 \000\000\270\377\177\000\000\020\b\000\000\000\000\000\000\020\b\000\000\000\000\000\000x\000\000\270\377\177\000\000\017'\000\000\000\000\000\000\244\371\311\366\377\177\000\000P\000\000\000\000\000\000\000`\255\070\277\377\177\000\000\b\b\000\000\000\000\000\000_\255\070\277\377\177\000\000\200\000\000\000\000\000\000\000\200\255\070\277\377\177\000\000\030\000\000\000\000\000\000\000\177\255\070\277\377\177\000", q_for_alignment_1 = 2, q_for_alignment_2 = 9.8813129168249309e-324}}
    methodName = {d = 0x7fffeeef8ea0 <QArrayData::shared_null>}
    methodTypes = 
        {a = 10, s = 0, ptr = 0x7fffbf38ad30, {array = "\004\000\000\000\000\000\000\000\201R\307@\000\200\377\377\000\000\000\000\000\000\000\000\002\000\000\000\060", '\000' <repeats 19 times>, "[\000\000\000n", '\000' <repeats 19 times>, "w\000\000\000|\000\000\000\001\000\000\000\000\000\000\000 \000\000\270\377\177\000\000\b\b\000\000\000\000\000\000\212\245\366\254\000\000\000\000\020\362\000\270\377\177\000\000 \000\000\270\377\177\000\000\030\000\000\000\000\000\000\000\220n\002\270\377\177\000\000\340\274\002\270\377\177\000\000\340^\000\270\377\177\000", q_for_alignment_1 = 4, q_for_alignment_2 = 1.9762625833649862e-323}}
```
#1  0x00007fffea4f4580 in QDBusConnectionPrivate::closeConnection() (member=0x0, receiver=0x7fffb800f210, this=<optimized out>)

```
at ../../src/corelib/kernel/qobject.h:361
    locker = {<QDBusLockerBase> = {<No data fields>}, self = 0x7fffb800f210, action = CloseConnectionAction}
    oldMode = <optimized out>
    allObjects = {q_hash = {{d = 0x7fffb802bce0, e = 0x7fffb802bce0}}}
    sit = <optimized out>
    oit = {i = {i = 0x7fffb8027cf0}}
```
#2  0x00007fffea4f4580 in QDBusConnectionPrivate::closeConnection() (this=this@entry=0x7fffb800f210) at qdbusintegrator.cpp:1128

```
    locker = {<QDBusLockerBase> = {<No data fields>}, self = 0x7fffb800f210, action = CloseConnectionAction}
    oldMode = <optimized out>
    allObjects = {q_hash = {{d = 0x7fffb802bce0, e = 0x7fffb802bce0}}}
    sit = <optimized out>
    oit = {i = {i = 0x7fffb8027cf0}}
```
#3  0x00007fffea4e1672 in QDBusConnectionManager::run() (this=0x7fffea556060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>)

```
at qdbusconnection.cpp:199
    d = 0x7fffb800f210
    it = {i = 0x7fffb800fc50}
    locker = {val = 140737124851825}
```
#4  0x00007fffeec9d99a in QThreadPrivate::start(void*) (arg=0x7fffea556060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>)

```
at thread/qthread_unix.cpp:341
```

---Type <return> to continue, or q <return> to quit---
        __clframe = 
          {__cancel_routine = 0x7fffeec9cac0 QThreadPrivate::finish(void*), __cancel_arg = 0x7fffea556060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>, __do_it = 1, __cancel_type = <optimized out>}
        thr = 0x7fffea556060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>
        data = <optimized out>
#5  0x00007ffff76f95ca in start_thread (arg=0x7fffbf38b700) at pthread_create.c:333

```
    __res = <optimized out>
    pd = 0x7fffbf38b700
    now = <optimized out>
    unwind_buf = 
          {cancel_jmp_buf = {{jmp_buf = {140736401553152, 4940229463117871958, 140737488337743, 4096, 140736401553152, 140736401553856, -4940370773466465450, -4940213106621727914}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
    not_first_call = <optimized out>
    pagesize_m1 = <optimized out>
    sp = <optimized out>
    freesize = <optimized out>
```
#6  0x00007ffff6d22f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by davvid** [comment]
Closing this since this has been fixed upstream in Qt 5.8.  If you're on newer Debian or Fedora you should have the fix by now.

https://bugreports.qt.io/browse/QTBUG-52988

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845662
