### ISSUE TITLE
Make 'Check Spelling' selection preserved after git-cola restart

### ISSUE THREAD

**Issue by Coacher** [git-cola/git-cola#596]
Hello.

I like git-cola and I like correct spelling in my commit messages.
Currently I have to manually click on 'Check Spelling' every time I restart git-cola and sometimes I forget to do this. Could you please make it that 'Check Spelling' choice is preserved after git-cola restart? It's not a thing that needs to be flipped often, so preserving it makes sense.

**Comment by Myz** [comment]
Might be related: #632

**Comment by VeganHunter** [comment]
I believe this issue should be closed, it's been fixed since 15 January 2017 thanks to #645.
