### ISSUE TITLE
argv overflow on Windows

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#603]
While rebasing, running git hosted on msys2 (aka cygwin)

```
<130> crooked-schemer /home/sthalik/dev/WindowsSDK7-Samples % git cola      [A3][master]
error: unable to execute 'git'
error: please ensure that 'git' is in your $PATH
```

That happened when tried to stage lots and lots of files for amending.

On Windows `CreateProcess` returns HRESULT with an error code. Preferably though we'd perform like `xargs(1)` and choose just right sizes. Do the argument list thing in several chunks if need be according to advertised command line string limits.

@davvid do you want me to work on a pull request?

**Comment by davvid** [comment]
The rebasing part is actually done by core git, but if there's anywhere where we need chunking while doing `add` then I'd recommend taking a look at the `_sliced_add()` and `_sliced_op()` methods that are used when adding files in `cola/models/main.py`.

If lowering the hard-coded limit there helps then we can do that, but it might also be better to try to detect the limits at runtime and chunk accordingly.  The simplest patch is probably to decrease the limit.  Give that a try.

**Comment by davvid** [comment]
We recently reduced the chunking down by half, which should have fixed this.  Let me know if you're still seeing this issue.
