### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by gelldur** [git-cola/git-cola#604]
```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/cmds.py", line 1835, in runner
    do(cls, *local_args, **local_opts)
  File "/usr/share/git-cola/lib/cola/cmds.py", line 1856, in do
    return do_cmd(cls(*args, **opts))
TypeError: __init__() takes 1 positional argument but 2 were given
error: git-cola died of signal 6
```

When clicking `Refresh` action button

**Comment by davvid** [comment]
Hi, what were you doing when you hit this error?  It's highly possible that this has already been fixed in `master` but it's hard to tell.

Please let me know what action you performed in the UI, and what version you're running.  cheers

**Comment by gelldur** [comment]
I crush always when i press `Refresh` in action buttons. I'm using 2.8-1 version from Arch repositories.

**Comment by gelldur** [comment]
Thanks it is working now ;)
