### ISSUE TITLE
Separate dependency links for Windows 64 and 32 bits in Readme

### ISSUE THREAD

**Issue by Garoe** [git-cola/git-cola#609]
In the Windows installation section the current dependencies point to the main pages of the projects.
I have a 64bit system and I was naive enough for the Python to click on big Download button for python 2.7.X in their main website, so I ended up with

- Python 32bits
- PyQT 64 bits

git-cola fails silently when double clicking on the icon, and from the command line it otuputs "qt bindings not found".
Having two sets of dependency links which directly point to the 32 and 64 bits downloads would have avoided this.

**Comment by davvid** [comment]
Thanks for the sug.  I'll try to update the docs to make this clearer.
