### ISSUE TITLE
As a stupid windows user I can't make it work

### ISSUE THREAD

**Issue by Drugoy** [git-cola/git-cola#612]
So I ran the installer.
Turns out it requires python, because it asks to point at pythonw.exe.
So I've installed python, re-ran the git-cola's installer and pointed it to pythonw.exe. It installed fine.
I try to run it: desktop/start menu labels `git-cola` and `git-dag` that were created by the installer do nothing and open nothing.
I read ReleaseNotes.txt it says `To run cola, just type 'cola' from a Git Bash session.` there, but I don't have `git bash` and there's no link to it.
I go to this repo's <a href="https://github.com/git-cola/git-cola#windows-installation">windows installation</a> section and it doesn't mention `git bash` there, but instead mentions `msysgit` that seems to be a combo of `git bash` and `git GUI` (if it has GUI - why would I even need `git-cola` then?), but their installer (unlike yours) exists as both 64-bit and 32-bit installer/portable utility.

Now I'm thinking: if I have 64-bit OS and 32-bit `git-cola` - will it work fine if I install 64-bit `git GUI`?

Geez, it should all be way more simple: if your program depends on a framework/interpreter/compiler/library - it should ask the path to it AND offer to download it if user doesn't have it pre-installed.

**Comment by davvid** [comment]
Install 64bit python and 64bit Qt and matching PyQt.  the cola installer might be 32b or something but it doesn't matter, it's just python (platform-independent) so you just need to make sure to use matching 64b of all the dependencies.

I'd suggest trying to run out of the source tree first.  Once you have python you should be able to run from cmd.exe or a bash terminal (included with git? I dunno) and say `python bin/git-cola` and it should run.

That'll rule out issues with the installer.  I'll see if anything was missed, but I don't actually have a windows environment for testing stuff these days.  if someone gifts me an x64 windows image that I can plug into virtualbox then I'd be happy to try to debug this.

**Comment by Drugoy** [comment]
<a href="https://www.microsoft.com/en-us/download/details.aspx?id=2227">Windows Server 2008 R2 Enterprise Edition x64 (Full Install) VHD</a>. VBox should support those.

**Comment by Drugoy** [comment]
Thanks!
