### ISSUE TITLE
Favorites window: more customization

### ISSUE THREAD

**Issue by IgorGalarraga** [git-cola/git-cola#619]
Personally I use a lot of favorites item for each customer.
With favourites renaming I can use sort patterns:
- customer1-xxx
- customer1-yyy
- customer2-xxx
- ...

But in this way resultant favorites window is very large (vertical scroll bar) but I have width free that I think it could be used by favorites item.
I have done some tries with TreeWidget splitting items into columns, but I think It is a hard goal for my python knowledge.
I see that it is possible to fold Items on TreeWidget. I think this is more easier to do. This implies a change on configuration file for bookmarks list (adding folder extra item).
What is the way to take closer to this project?
Some advices?

**Comment by davvid** [comment]
Right now we store a list of dictionaries that represent the Favorites.  The best place to look to understand the data structure is to look at `~/.config/git-cola/settings`  Look for a key called `"bookmarks"`.

We would need to extend to format to allow having "folders" that could be identified as an entry with a key called `"items"` that itself points to another list with the same recursive structure.

When building the UI we would have to traverse the nested structure and create folders whenever it encounters an entry that contains a list of child `"items"`.

Operations like renaming and reparenting would need to be added.  It seems like this would be generally useful.  The file format can be changed in a forward-compatible way, as the current format is basically a subset of the recursive extension.

Would having a nested folder structure work for your use case?

**Comment by IgorGalarraga** [comment]
> Would having a nested folder structure work for your use case?

Yes, for my use case, first folder would be the customer and nested folders into would be projects with this customer. Each project folder will have one or more git repositories.

This is perfect for me.
