### ISSUE TITLE
Wishlist - add "Show in file manager" option

### ISSUE THREAD

**Issue by kedziorm** [git-cola/git-cola#621]
Once I open repository in git-cola, I would like to see all files within file manager (for example in [GNOME Files/Nautilus](https://en.wikipedia.org/wiki/GNOME_Files)).
View --> File Browser... is not enough, since I can't for example run from it different editor, copy new file to my repository or use option to open console in current location.

Currently, once I open my repository in git-cola, I manually run my file manager and navigate to appropriate path.

There's similar option "Show file in explorer" in SourceTree.

**Comment by davvid** [comment]
I've added actions to both the Browser and the Status widget that allow us to perform the following actions. There are keyboard shortcuts bound too (see the right-click menu in the status widget).

- Open with Default Application
- Open Parent Directory
- Launch Terminal

If you "open with default app" on a directory in the Browser widget then it'll launch nautilus, assuming that you have it configured as your default file manager.  If you use "open parent directory" it'll do the same with any of the files in the status tree.

The "Launch Terminal" option always launches into the same directory as the selected file/directory.  Thanks for the sug!

**Comment by geovens** [comment]
Sorry for bringing this up, but I can't find Open with Default Application or Open Parent Directory in the right-click menu in the status widget, or anywhere. Were they removed? I can't find an equivalent function anywhere either. I'm using Windows 10 version 2004, Git Cola v 3.9.
