### ISSUE TITLE
Word diff

### ISSUE THREAD

**Issue by nafg** [git-cola/git-cola#623]
Please highlight the words or characters that changed.

For example, how long does it take you to tell exactly what did change and what didn't change here?

![image](https://cloud.githubusercontent.com/assets/98384/20042211/efa1ebc6-a443-11e6-8b81-2b40ecdcbb40.png)

**Comment by Vdragon** [comment]
> For example, how long does it take you to tell exactly what did change and what didn't change here?

3 seconds/line

**Comment by nafg** [comment]
> 3 seconds/line

Then I suppose this:

![image](https://cloud.githubusercontent.com/assets/98384/20043429/3464b6dc-a45b-11e6-991c-7b7b04362713.png)

would take you about 50ms ;)

If you have a lot of changes it adds up quickly. Especially if, as often happens, I have a lot of changes, and I need to go through all of them and split them into multiple commits.

So (1) speed matters and it adds up, and (2) I want be certain that the line has only the change I want to commit

Thanks.

**Comment by richarson** [comment]
@nafg Just my $0.02 and maybe I'm too used to unified diffs, but in your second example it actually took me a while to realize what I was looking at and what the differences were.

That said, I undestand your point completely, and if you could keep the "unified diff" look but highlight the modified words I think it would be the best of both worlds.

**Comment by nafg** [comment]
Here's how the same change looks in gitlab (I believe github is basically the same):

![image](https://cloud.githubusercontent.com/assets/98384/20075766/9acf9574-a503-11e6-942d-bd87b83ca911.png)

That would be fine with me and I'm guessing with @richarson too

**Comment by Epskampie** [comment]
I would love this feature too, here is how to do it in git commandline, with a `diff-hightlight` script that might be a useful starting point for an implementation: http://stackoverflow.com/a/15149253/146738

**Comment by Myz** [comment]
Some time ago I implemented this partly and not fully tested in my personal fork of git-cola
https://github.com/Myz/git-cola/commit/9dc5153c7734a9a53b85f7b62fab0d9d4a8a5ecd

This still is missing one local commit but yes, this feature is doable and would be great to have in some situations when you would use the interactive mode from the cli.

**Comment by Vdragon** [comment]
Adding my usecase:

I'm using Git to track several Flat-ODF document, every modification to the file will cause a lot of trivial line changes which simply altering the auto-numbered style name, with this feature it will be easier to determine which line contain the actual changes instead of these trivial changes.

![default](https://cloud.githubusercontent.com/assets/1192163/21599655/3423c6f4-d1ab-11e6-860a-22d8ef217dd2.png)

**Comment by davethecipo** [comment]
I would also benefit from this feature when I write LaTeX files. I tried taking a stab at the problem in this [commit](https://github.com/davethecipo/git-cola/commit/48321043df538b8d87e46dbaa677c7e6f345bee2). I used the approach suggested by @Myz which calls `git diff --word-diff=porcelain`. Besides the fact that I used the wrong regex (which doesn't catch all cases; any help is welcome since I'm no expert on regexes), it works. The problem is that I don't know how to remove the prefixes and suffixes added by the porcelain option.

Any suggestion is welcome.

**Comment by Myz** [comment]
@davethecipo I already made it through that. It barely works but still has flaws and the code is not nicely separated nor testable. I will try to bring it to shape a bit more and the putting it into my fork.

**Comment by nafg** [comment]
Any updates on this?

**Comment by Myz** [comment]
> Any updates on this?

I can only come up with excuses. Haven't had the time. Family.... Job.... I am sorry.

**Comment by nafg** [comment]
No need to apologize! Just wondering if there is any plan or any likely
timeline.

Meanwhile I learned how to get such highlighting in the terminal...

**Comment by asmwarrior** [comment]
> 
> 
> Some time ago I implemented this partly and not fully tested in my personal fork of git-cola
> https://github.com/Myz/git-cola/commit/9dc5153c7734a9a53b85f7b62fab0d9d4a8a5ecd
> 
> This still is missing one local commit but yes, this feature is doable and would be great to have in some situations when you would use the interactive mode from the cli.

Hi, I can't access to your fork now, do you have any patch about the implementation? Thanks.

**Comment by asmwarrior** [comment]
> 
> 
> I would also benefit from this feature when I write LaTeX files. I tried taking a stab at the problem in this [commit](https://github.com/davethecipo/git-cola/commit/48321043df538b8d87e46dbaa677c7e6f345bee2). I used the approach suggested by @Myz which calls `git diff --word-diff=porcelain`. Besides the fact that I used the wrong regex (which doesn't catch all cases; any help is welcome since I'm no expert on regexes), it works. The problem is that I don't know how to remove the prefixes and suffixes added by the porcelain option.
> 
> Any suggestion is welcome.

OK, I see this commit/branch is the latest implementation of the feature request:

https://github.com/davethecipo/git-cola/commits/feature/word-color-diff

**Comment by asmwarrior** [comment]
It looks like parsing the `--word-diff=porcelain` result is not a good idea, there are some discussion in `git gui`'s git repo, it has a similar discussion: [Visualization of intraline differences · Issue #31 · prati0100/git-gui](https://github.com/prati0100/git-gui/issues/31)

**Comment by asmwarrior** [comment]
Maybe, a python based parser like the C++ code in this post: [QTextEdit and colored bash-like output emulation](https://stackoverflow.com/questions/26500429/qtextedit-and-colored-bash-like-output-emulation) can be used.

**Comment by asmwarrior** [comment]
Hi, a recent discussion in [Scintilla / Bugs / #2161 Ansi color codes support](https://sourceforge.net/p/scintilla/bugs/2161/) shows that the scintilla control support basic ANSI color codes from year 2016, so maybe, we can use this control, since there is a [QScintilla: QScintilla - a Port to Qt v4 and Qt v5 of Scintilla](https://docs.huihoo.com/pyqt/QScintilla2/).

**Comment by asmwarrior** [comment]
Another thing we can do is: manually compare the added or removed lines.

There is a similar project named [gitahead](https://github.com/gitahead/gitahead), which is QT based and implemented in C++.

https://github.com/gitahead/gitahead/blob/bb747caef098140d9674990b1d79d096d1eac8df/src/ui/DiffView.cpp#L1323-L1371

It looks like it just split a line to different words(tokens), and then compare token by token, then mark the mismatched tokens in different code styles.

**Comment by cgomj** [comment]
I started trying to use GitCola and this is one feature I'd really like to see implemented.

From the code I can see that the widgets to show the diff text finally inherit from QPlainTextEdit. I would suggest changing so the underlying type for the diff text is rather QTextEdit and this would give us the option to highlight differences in text using for example bold letters.

The highlighter seems to look one line at a time to add things such as the green/red background when it's an add/remove line but doesn't seem to take into account the context. Also highlighter only returns formatting not changes the underlying text so it doesn't seem this to be the place to modify.

I think a solution could be to change to QTextEdit as the underlying text for DiffText and implement some kind of post-processing on the text after the highlighter has run. For the text received go line by line finding at the lines that contain differences (+/-) symbols and for each line try to find the other one it refers to (for example -  and +). Then apply some algorithm to find difference in texts in between the lines like the ones suggested above based on splitting lines in tokens or something else. We can always improve this algorithm once something is up and running after anyway and do some TDD approach where we play with it until it seems to work the way we want!

**Comment by asmwarrior** [comment]
Oh, It looks like this issue is not implemented yet, but put in a file in the code repo.

**Comment by davvid** [comment]
Yeah, someone is free to implement it, but I don't have any plans to work on it. I'm not keen on keeping lingering issues around forever.

**Comment by nafg** [comment]
That's why you can close as not planned instead of close as completed

**Comment by asmwarrior** [comment]
> That's why you can close as not planned instead of close as completed

I agree with you.
