### ISSUE TITLE
On MacOS the toolbars are displayed pitch black.

### ISSUE THREAD

**Issue by utkukaratas** [git-cola/git-cola#624]
On MacOS the toolbars are displayed pitch black. 

Tested on El Capitan. Happens in all the windows: the DAG viewer and main app.

![screen shot 2016-11-12 at 12 18 48 am 1](https://cloud.githubusercontent.com/assets/59096/20230579/6049e43a-a865-11e6-9571-386320cae14e.png)

**Comment by davvid** [comment]
thanks for the heads-up.  please try the `macos-toolbars` branch in my fork https://github.com/davvid/git-cola/tree/macos-toolbars

does it fix the issue for you?  I can't reproduce the problem myself on El Cap (seems to work fine here) but the change did fix a long-standing bug where the toolbars would display with a transparent background when detached.  I have a feeling that the change may have also fixed this issue.

Let me know if it helps.

**Comment by utkukaratas** [comment]
This does fix the issue. Thanks.

Although, I just checked out master and that also does fix the issue. So I'm guessing this issue is particular to the vanilla homebrew install.

**Comment by raimue** [comment]
This issue only appeared for me on macOS 10.12 Sierra when using Qt5, the toolbars are fine with Qt4. Note qtpy will always prefer Qt5 unless you export `QT_API=pyqt4` in the environment before running git-cola. This might be a workaround for others as well.

**Comment by zjx20** [comment]
@davvid There are still some views have a black background color, could you please take a look? Actually, I suspect the black color is the default background color for ***all*** views.

OS: macOS 10.12.1
git-cola version: 2.9.1_1 (installed via brew)

Here are a few of them:

The parent view of the commit summary text view:
![780484d2-4584-4cdc-869e-38a79d660b52](https://cloud.githubusercontent.com/assets/2639200/21599782/ff543894-d1ac-11e6-90ac-946bc4e12e33.png)

The stash view:
![ba591b08-9457-4760-a9ba-c9638984e6f9](https://cloud.githubusercontent.com/assets/2639200/21599745/953edaae-d1ac-11e6-953b-3963ce08bf2a.png)

**Comment by davvid** [comment]
I fixed the main screen and will take a look at fixing the rest shortly.  Some defaults changed in PyQt5/MacOS
