### ISSUE TITLE
Can no longer run git-cola from git checkout on Windows

### ISSUE THREAD

**Issue by living180** [git-cola/git-cola#626]
I am trying to look into issue #620, but am having problems due to the addition of qtpy.  Windows has poor symlink support, and thus on Windows git checks out symlinks as a text file whose contents are the destination of the symlink.  However, this means that the `qtpy` symlink in the project root directory is not an actual symlink, and therefore Python cannot import qtpy.  As a result, git-cola exits with an error.  Obviously I can work around this locally for my development, but it is no longer possible to run git-cola from a git checkout on Windows in the standard configuration.

**Comment by davvid** [comment]
Good point.  I think we can get rid of the symlink and add some more sys.path munging in the startup scripts when we detect that we're in the source tree.
