### ISSUE TITLE
Tree rendering with lots of branches overlapping unrelated branches

### ISSUE THREAD

**Issue by thk123** [git-cola/git-cola#631]
In cases where there are quite a few branches, I find the DAG will have two unconnected branches appear on top of each other. This confusingly gives the impression they are connected:

Here it looks like fff_mocks is behind the unity_test_generation... branch:
![git_cola_branch](https://cloud.githubusercontent.com/assets/638608/20795262/13192276-b7c8-11e6-805c-ea0952fbedc8.png)

However, in gitk, it looks like this:
![gitk_tree](https://cloud.githubusercontent.com/assets/638608/20795346/9d1b81f8-b7c8-11e6-93a5-096182761c63.png)

So are clearly disconnected.

**Comment by davvid** [comment]
@laerreal I'm pretty sure your rework of the DAG layout algorithm in the various recent pull requests fixed this issue, so I'm closing this for now.
