### ISSUE TITLE
Feature Request: Enable spell check for the commit message by default by preferences

### ISSUE THREAD

**Issue by Myz** [git-cola/git-cola#632]
The first thing I do when I start up the git-cola is to enable the spell check.

This is so redundant and could be simplified by putting an option to the preferences page that allows to control this behaviour in a nice way.

Thanks for providing such a nice frontend for our beloved git <3

**Comment by Myz** [comment]
Might be related: #596

**Comment by davvid** [comment]
Keeping "check spelling" on after restart was implemented a bit ago and will be included in the next release (soon), but I forgot to close this issue.

**Comment by Myz** [comment]
Thanks a LOT! That's fantastic!
