### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'endswith' when starting

### ISSUE THREAD

**Issue by TimSchumi** [git-cola/git-cola#642]
When I try to open the program (from Ubuntu 16.04 standard repository), I get the following error:

Traceback (most recent call last):
  File "/usr/bin/git-cola", line 56, in <module>
    sys.exit(main())
  File "/usr/share/git-cola/lib/cola/main.py", line 34, in main
    return args.func(args)
  File "/usr/share/git-cola/lib/cola/main.py", line 268, in cmd_cola
    context = application_init(args)
  File "/usr/share/git-cola/lib/cola/app.py", line 277, in application_init
    prompt=args.prompt, settings=args.settings)
  File "/usr/share/git-cola/lib/cola/app.py", line 359, in new_model
    settings=settings)
  File "/usr/share/git-cola/lib/cola/widgets/startup.py", line 45, in __init__
    settings.load()
  File "/usr/share/git-cola/lib/cola/settings.py", line 117, in load
    self.remove_missing()
  File "/usr/share/git-cola/lib/cola/settings.py", line 78, in remove_missing
    if not self.verify(recent):
  File "/usr/share/git-cola/lib/cola/git.py", line 45, in is_git_worktree
    return is_git_dir(join(d, '.git'))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'dict' object has no attribute 'endswith'

I first used the git-cola from Ubuntu's apt. But then I tried to start git-cola from my checked out sources, which also worked (and still works). Since then I get the error from above if I try to start the apt version.

**Comment by davvid** [comment]
Sorry about that.  If you've launched from the source tree then you probably need to keep using the newer version.

There was a data format change between the version you have installed in `/usr` (likely from your distro) and the latest version in `master`.  The new code upgrades the settings file in-place, so once you've gone to a new version you can't go back (without deleting the settings).

The workaround, if you want to keep using the older version, is to delete, or restore your original, `~/.config/git-cola/settings` file.

**Comment by TimSchumi** [comment]
Thanks! That solved it!

**Comment by grmartin** [comment]
FTR The data change for me was that the `recent` list went from an array of just paths to an array of objects with both path and name... if youd rather not blow it away... its an easy manual fix in this case. For me it happened when i restored Debian's Jessie Unstable back to Stable after a fatal issue.

**Comment by davvid** [comment]
@grmartin that's true, instead of deleting settings you can also edit the json in the `settings` file to restore the old format.

An example of the old and new format is below.  Downgrading the settings file from Debian unstable (new) to stable (old) can be done by transforming entries from "New" style into "Old" style.

```
# Old
"recent": [
    "/src/a",
    "/src/b"
 ],

 # New
"recent": [
    {"name": "a", "path": "/src/a"},
    {"name": "b", "path": "/src/b"}
],
```

**Comment by grmartin** [comment]
@davvid thanks for the update, im a huge fan of ensuring these things to be detailed incase someone in a year or two comes back with a similar issue.
