### ISSUE TITLE
Context menu mouse issue.

### ISSUE THREAD

**Issue by Parashurama** [git-cola/git-cola#643]
First, this is likely not a purely git-cola issue, as this also appear in an other qt application (qgit).
In git-cola with when right-clicking on an item in **status**  or **diff** panel, and not releasing immediately the button, I can accidentally select the first entry of the context menu.
This is really annoying in the **diff** section since the first entry is 'stage the whole modified file'.
The issue appear in python 2.7/3.5 and using PyQt4.8/PyQt5.5 

An easy way to solve my issue (and for others, I assume) would be to nudge the context menu position by 2~3 pixels in every contextMenuEvent function.

```python
    def contextMenuEvent(self, event):
        ...
        menu.exec_(self.mapToGlobal(event.pos()))
```
## into
```python
    def contextMenuEvent(self, event):
        ...
        ev_pos = event.pos(); ev_pos.setX(ev_pos.x() + CONTEXT_MENU_NUDGE)
        menu.exec_(self.mapToGlobal(event.pos()))
```
I will write a proper pull request in a few days, if this is acceptable.

**Comment by davvid** [comment]
I've ran into that a few times myself as well. :+1:

**Comment by Vdragon** [comment]
Thanks for filing it.

**Comment by rpost** [comment]
Since more than a few days passed already I decided to take action: please find corresponding pr. I took different path to solve this issue though: instead of moving menu few pixels (which I tried as well, but found akward), I introduced short period of insensitivity right after menu was created.
