### ISSUE TITLE
Feature: Pls add a menu "ignore this" when right click the file.

### ISSUE THREAD

**Issue by yuushouri** [git-cola/git-cola#644]
Please add a feature ignore.
Ignore that files to be showed in the **status** list and to avoid getting selected in stage.
Can also make a list for all the files got ignored? so if we can put an option to remove them in ignore list..
Thanks

**Comment by Vdragon** [comment]
There's already a "Add to .gitignore" function in the contextual menu of "Status" widget
![_093](https://cloud.githubusercontent.com/assets/13408130/21895238/e5a6331c-d91c-11e6-948d-464d633080a2.png)

The list of all ignored files seems can be acquired from `git ls-files --ignored`

**Comment by yuushouri** [comment]
@Vdragon thanks

**Comment by yuushouri** [comment]
@Vdragon
![selection_006](https://cloud.githubusercontent.com/assets/1988090/22014801/49f40b30-dcda-11e6-9c4f-3876724c7e85.png) how about the file that were push before, there is no option add to .gitignore when right click..
Thanks

**Comment by davvid** [comment]
This is actually a Git feature.  Once a file has been added to the repo Git will not ignore that file -- it's a tracked file.

If you would like to Untrack the file, and no longer have Git care about it, you can use the "View -> File Browser..." menu, right-click the file, and choose "Untrack Selected".  Git will no longer track this file.

Note: that when your co-workers pull, they are either going to hit a conflict, or the file will be removed from their worktree.  If they hit a conflict, move the file out of the way and re-pull.
