### ISSUE TITLE
Signed commits

### ISSUE THREAD

**Issue by himynameisdave** [git-cola/git-cola#649]
Would be nice to have the ability to sign a commit (using command line it's `git commit -S -m 'My signed commit'`) right from the GUI.

https://help.github.com/articles/signing-commits-using-gpg/

**Comment by hamen** [comment]
I was able to do it in the past selecting the menu item:

<img width="318" alt="screen shot 2017-02-08 at 2 12 19 pm" src="https://cloud.githubusercontent.com/assets/19003/22738688/ae8c8858-ee08-11e6-94ba-faa4c949fc75.png">

Unfortunately is not working anymore:

<img width="359" alt="screen shot 2017-02-08 at 2 11 17 pm" src="https://cloud.githubusercontent.com/assets/19003/22738697/ba4ca0ba-ee08-11e6-976f-83f57ab09ea7.png">

I can do it via command line with `git commit -S ...` after setting:

```
git config --global gpg.program gpg2
```

but I think `git-cola` is not picking the right `gpg`.

I'm running `cola version 2.10` on MacOS Sierra.

Any help, please?

**Comment by davvid** [comment]
https://git-cola.readthedocs.io/en/latest/git-cola.html#setting-up-gpg-for-signed-commits

**Comment by MarcinWieczorek** [comment]
Pinentry flashes on the screen and that error is being displayed. It works sometimes on the first try, sometimes on the tenth. `git commit -S` works ok from the command line.

**Comment by MarcinWieczorek** [comment]
You can commit anyway by pressing the gear icon (which has disappeared but still works) and selecting "commit". Pinentry pops up normally.

**Comment by davvid** [comment]
I had to change my config recently on Linux.  I've updated the docs to reflect what works for me.

**Comment by MarcinWieczorek** [comment]
I'm quite sure I use gtk pinentry

**Comment by davvid** [comment]
https://git-cola.readthedocs.io/en/latest/git-cola.html#setting-up-gpg-for-signed-commits
