### ISSUE TITLE
Commit Message Editor Window

### ISSUE THREAD

**Issue by jj3666** [git-cola/git-cola#65]
After staging files, this window should be set to active.  Currently, you must take focus off of main window with selecting 'commit' button to generate error about blank message, or edit->options and pressing cancel button, at which point you can enter a commit message.

**Comment by rjasdf** [comment]
It's a decade later; I'm new to git-cola.  I have never seen the [Commit] button enabled, despite following most of the hints here and elsewhere.  I'm on Ubuntu 22.04 with git-cola 3.12.0.  Ctrl-Return fails; Edit>Commit is grayed out; fullscreen does not change anything.  No combination of maximize-window, change focus, etc seems to help.

**Comment by davvid** [comment]
The commit button is disabled by default until you type something into the subject field so that there's a commit message to commit.

**Comment by rjasdf** [comment]
Oh -- I have to fill in the little window ("Commit summary"), not the "Extended Description" window.
Rick Jamesemail: ***@***.***
 

    On Wednesday, May 31, 2023 at 11:26:30 PM PDT, David Aguilar ***@***.***> wrote:  
 
 


The commit button is disabled by default until you type something into the subject field so that there's a commit message to commit.
