### ISSUE TITLE
Split hunk into smaller pieces

### ISSUE THREAD

**Issue by qwfy** [git-cola/git-cola#650]
Sometimes it's useful to split a hunk into smaller hunks, like the `s` command in `git add -p`, will this be added to the right click context menu of the **Diff View**?

Better, is it possible to add a **Split hunk here** entry to the context menu? when clicked, will split the hunk at the cursor position.

**Comment by davvid** [comment]
We already allow you to split down to the single line level.  Select a few line in the diff editor and hit "s" and it will stage only the selected lines.

**Comment by qwfy** [comment]
didn't know you can do that :+1:
