### ISSUE TITLE
Feature Request: Toggle for "Spaces instead of Tabs" for indentation

### ISSUE THREAD

**Issue by conz27** [git-cola/git-cola#660]
Using git-cola, I tried to add some indentations into my commit message using the 'Commit' sub-window and was surprised that any indentations I tried to insert were interpreted as Tabs.

I went to File > Preferences > Settings and noticed that I only had the option to change the Tab Width but not use spaces instead of tabs.

Can you create a toggle switch that for "Spaces instead of Tabs" and use the Tab Width to determine how many spaces should be inserted for each Tab keyboard key press.

**Comment by judaszszymon** [comment]
Do we need this feature in one line edit fields?

**Comment by davvid** [comment]
I don't think we need this for the summary field.  That line should *never* be indented with a tab.  Use of tabs is more of a commit-body thing..

**Comment by conz27** [comment]
Agreed. My original thoughts were to replace tabs with spaces in the commit body, not one line edit fields.

**Comment by davvid** [comment]
Looks like we merged this feature already but forgot to close this issue.  Thanks again!
