### ISSUE TITLE
Spell check in "Extended description..." should support custom dictionaries (for Windows)

### ISSUE THREAD

**Issue by refaelsh** [git-cola/git-cola#663]
Spell check in "Extended description..." does not work.
Every word (regardless of correctness) is underlined with a red line.
Here is a screenshot:
https://www.dropbox.com/s/l9jkntkp5yopdip/Screenshot_2017-02-15_17-47-30.png?dl=0

**Comment by davvid** [comment]
We currently hard-code the path to a dictionary text file that is typically found on Linux and macOS/unix systems: `/usr/share/dict/words`

If you make that path available (tho I'm not really sure if it's possible on Windows) and you populate the file with an alphabetized, newline-separated list of words then this feature will start working.

We should make it possible to specify additional dictionaries so I'll leave this issue open as a feature request.

**Comment by refaelsh** [comment]
Thank You for replaying :-)
1. Its now Windows (God forbid :-)), its Arch Linux.
2. I have no text file named "words" in the /usr/share/dict/ folder. I have only one file in that folder and its called "crack-lib" small and it seems to contains more then 50k lines with dictionary words.

**Comment by davvid** [comment]
Looking at what I currently have (debian), `/usr/share/dict/words` is a symlink to `/usr/share/dict/cracklib-small`.  I'm going to make it prefer the latter path.  Is that the same exact path you have?  If not, let me know what you have and I'll add a check for that too.

**Comment by refaelsh** [comment]
@davvid Yes, this is the exact path I have.
I've seen the commits You've made.
Thank You very much for fixing this issue :-)

**Comment by refaelsh** [comment]
Hello again. Recently, the git-cola package on Arch Linux got updated to v2.11 and the bug still exists. What am I missing please?

**Comment by davvid** [comment]
I wonder if you need `aspell` or some package that provides the dictionary files?  I'm not an Arch user but on Debian the packages that provide files in `/usr/share/dict` are cracklib-runtime, base-files, and dictionaries-common.

**Comment by refaelsh** [comment]
@davvid 
1. I have `aspell` installed.
2. I have a file called `cracklib-small` in folder `/usr/share/dict`. It contains dictionary words separated by new line.
3. I ran `git config --global cola.dictionary /usr/share/dict/cracklib-small`.

I still have no spell checking :-)
What else am I missing?

**Comment by davvid** [comment]
sorry for the late response.. you also have to go into the `File -> Preferences` dialog, click on `Settings`, and check the `Check spelling` checkbox.  But, based on your original screenshot, you already have that enabled.

The setting of `cola.dictionary` should be optional and not strictly required now.  At least it works fine on my debian install that has that same exact `/usr/share/dict/cracklib-small` path.

Can you poke inside that (maybe run `head` on it) and see if it's identical to the one here:

```
$ head /usr/share/dict/cracklib-small
10th
1st
2nd
3rd
4th
5th
6th
7th
8675309
8th
```
