### ISSUE TITLE
git-cola displays that patch is correctly applied when it's not

### ISSUE THREAD

**Issue by wojnilowicz** [git-cola/git-cola#673]
Steps to reproduce:
1) File->Apply patches
2) add an patch
3) press apply

Results:
Message that patches were successfully applied, but no patch is applied.

Expected result:
Patch should be applied or warning should be displayed, that patching is not possible at the moment.

Additional info:
Repository is during patching operation. "git-am --abort" workarounds issue reported here.

**Comment by davvid** [comment]
Thanks for the sug!
