### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by kuon** [git-cola/git-cola#676]
I have just installed git-cola on archlinux and I notice missing icons on the right panel:

![Missing icons](https://www.dropbox.com/s/kh7de79rkg7uslg/Screenshot%202017-04-06%2016.41.22.png?dl=0&raw=1)

I have the following output in the terminal in which I invoked git-cola:

    libGL error: No matching fbConfigs or visuals found
    libGL error: failed to load driver: swrast

Version:

```
Git Cola version 2.10 
Linux-4.10.8-1-ARCH-x86_64-with-arch 
Python (/usr/bin/python) 3.6.0 (default, Jan 16 2017, 12:12:55) [GCC 6.3.1 20170109] 
Git 2.12.2 
Qt 5.8.0 
QtPy 1.1.1 
PyQt5 5.8 
```

**Comment by davvid** [comment]
All of your icons are missing.. We use svg icons.. is there a separate package to add qt image plugins, e.g. SVG support?

**Comment by davvid** [comment]
https://wiki.archlinux.org/index.php/Qt

> Icon theme is not applied
> 
> Since Qt 5.1 SVG support has moved into a module. Since qt5-base does not depend on qt5-svg it may happen that the qt5-base is installed but not qt5-svg. This results in deceptive icon theme behaviour. Since SVG is not supported the icons are silently skipped and the icon theme may seem to be unused. Installing qt5-svg explicitly solves the problem.

Would you mind filing a bug with the arch linux git-cola package maintainers?  It seems like the package should contain a dependency on `qt5-svg`.

For now, installing that package should do the trick.  Let me know if that works

**Comment by kuon** [comment]
Yep it did the trick. I will open an issue on the archlinux package. Thanks for your time.
