### ISSUE TITLE
Crash when editing commit message

### ISSUE THREAD

**Issue by wm4** [git-cola/git-cola#687]
I got a "random" crash when I hit some wrong keys (I don't know which):
```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/completion.py", line 323, in paint
    rect = style.subElementRect(item_text, params)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```
I don't know which keys I hit and can't reproduce it, but maybe the cause for the crash is somehow apparent anyway.

I'm using the Debian unstable package, which is outdated (sorry). Version output from git-cola's about tab:
```
Git Cola version 2.10 
Linux-4.4.49-x86_64-with-debian-9.0 
Python (/usr/bin/python3) 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] 
Git 2.11.0 
Qt 5.7.1 
QtPy 1.2.1 
PyQt5 5.7 
```

**Comment by davvid** [comment]
I'm pretty sure this was addressed in `v2.11`, fixed in 0da7624a6f473bda0c7152ddf2ff84c82075b0e0
