### ISSUE TITLE
Centos 6.8 Qt issue

### ISSUE THREAD

**Issue by eephillip** [git-cola/git-cola#692]
Version 2.6 works, but upgrading past that I get the following error.
Using the system python 2.6.6
PyQt4.x86_64            4.6.2-9.el6     @base                                   
PyQt4-devel.x86_64      4.6.2-9.el6     @base

```
Traceback (most recent call last):
  File "/home/user/.local/bin/git-cola", line 53, in <module>
    from cola.main import main  # pylint: disable=wrong-import-position
  File "/home/user/.local/git-cola/git-cola-2.10/cola/main.py", line 9, in <module>
    from .app import add_common_arguments
  File "/home/user/.local/git-cola/git-cola-2.10/cola/app.py", line 23, in <module>
    from qtpy import QtWidgets
  File "/home/user/.local/git-cola/git-cola-2.10/qtpy/QtWidgets.py", line 32, in <module>
    QFontMetricsF, QGlyphRun, QGradient, QHelpEvent, QHideEvent,
NameError: name 'QGlyphRun' is not defined
```

**Comment by davvid** [comment]
this might be as simple as updating our vendored copy of qtpy.

**Comment by eephillip** [comment]
Is that something I could patch just to try it out?

**Comment by davvid** [comment]
A quick workaround is to remove `QGlyphRun, ` from that file.  We don't use that symbol so we don't need it there.

The long-term solution is to report this problem at https://github.com/spyder-ide/qtpy

I tested this on PyQt4 4.6 with the latest qtpy and it has this same problem.

**Comment by davvid** [comment]
Another alternative is to build a newer PyQt from source.  PyQt 4.9 should work with that vintage.  I didn't realize that we may have silently updated our pyqt requirements when we moved to qtpy so I'll probably be patching this into our copy soon.

**Comment by eephillip** [comment]
Just pulled in merge spyder-ide/qtpy#106 into v2.10. Working great, thanks for supporting.
