### ISSUE TITLE
Several contextual menu entries in Status widget should be disabled when no items in list are selected

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#697]
As the following screenshot, several entries in contextual menu of the Status widget shouldn't be available when no files are selected:

![_025](https://cloud.githubusercontent.com/assets/1192163/25883793/ff93f056-357f-11e7-89b5-3e6b3db37f05.png)

We probably should only allow the "Launch Terminal" entry in this case

**Comment by davvid** [comment]
Thanks again for all the great sugs!
