### ISSUE TITLE
Clean filter that creates temporary files in work tree will cause unusable diff widget

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#699]
## Issue Reproducing Instructions
The instruction can be simplified but here's what we get now, it should be reproduced for any project's that implements a clean filter that creates file in work tree temporarily

1. `git clone https://github.com/Lin-Buo-Ren/Useful_Git_Clean_and_Smudge_Filters.git`
1. `cd Useful_Git_Clean_and_Smudge_Filters`
1. Checkout  commit 0d439fe015ce24fbb06b6be9de40d83754806e8e (which hasn't workaround the issue, yet)
1. `./初始化開發環境.bash` or simply `git config include.path ../.gitconfig` (you should audit the code first)
1. Uncomment *.fodt line in .gitattributes file
1. Install script dependency XMLStarlet and make sure `xmlstarlet` executable is in executable search `PATH` (Debian+: # apt-get install xmlstarlet )
1. Launch Git Cola from commandline
1. Make random changes to `Test Cases/Flat-ODF ODT.fodt` (using LibreOffice, or simply a text editor, just make sure it is still valid XML)
1. Select `Test Cases/Flat-ODF ODT.fodt` file in Status widget
1. Scroll down in Diff widget

## Current Behavior
* Notice the Diff widget automatically refreshes and return to the top of the diff, causes difficulties for user to stage partial content or view further diff
* Notice sometimes the temp file that is listed in the Status widget, then disappeared as it is deleted by the  clean script

## Expected Behavior
* Diff widget shouldn't automatically refreshes
* Clean filter shouldn't be automatically triggered when changes in work tree is detected (this probably not avoidable since it should be triggered by git command itself...?)

## Workaround
* Modify the filter so it creates temporary files outside of worktree(by using `mktemp` or other means)

### Git Cola
Git Cola 第 2.11 版 
Linux-4.10.0-pf3-not-that-ubuntu-tw-community-autodetected-optimized-x86_64-with-neon-16.04-xenial 
Python (/usr/bin/python) 第 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 版 
Git 第 2.7.4 版 
Qt 第 4.8.7 版 
QtPy 第 1.3.0.dev0 版 
PyQt4 (API v2) 第 4.11.4 版

**Comment by davvid** [comment]
Thanks for the careful report.

Can you please retest this in `master`?  There have been some changes there to make the diff widget's cursor stay in-place, so I think we may have fixed this issue.
