### ISSUE TITLE
UI is unresponsive when working with large LFS files

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#709]
The UI (understandably) seems to make assumptions about processor/disk speed and file size. When LFS it's possible to work with quite large files and git-cola becomes unresponsive for minutes at time. Especially when working with a working copy on a slow disk (like a mounted network folder).

**Comment by davvid** [comment]
Definitely.  We've added image diffing these days too, so we should detach the handling of diff requests to a background task so that the UI doesn't block while gathering data from git.  Unless someone beats me to it, I'll take a stab at this shortly after tagging the next release.

**Comment by davvid** [comment]
Duplicate of #499 -- sorry, I never got around to doing this yet. I'm gathering these ideas into a single issue where we'll attack performance issues related to this.
