### ISSUE TITLE
Cannot choose directory in File->Export patches

### ISSUE THREAD

**Issue by wojnilowicz** [git-cola/git-cola#711]
It would be nice if git cola had feature to configure directory into which it exports patches. Right now it's <REPOSITORY>/patches

**Comment by davvid** [comment]
This would be good.  It's currently hard-coded to my workflow ;-)

Most of the plumbing is already in place to make it configurable -- the top-level `export_patcheset()` function already takes an output parameter, but we just haven't hooked anything up to it yet.  It would be nice to have it default to `patches` and allow the user to enter anything.

**Comment by davvid** [comment]
Another thing that would be really cool is to add a "split patch" feature that lets you write patch files directly.

From the right-click menu:

```
Export (Hunk | Selection) to Patch
- New Patch
- Append Patch
  - Choose Patch File...
  - <list-of-existing-patches>
```

This can work with the selection and let you interactively create a patch file from your current edits.

Basically, the same idea as https://github.com/aleclearmind/split-patch but integrated into the diff editor.

This feature would also need to know about a designated directory for patches, so these are related.
