### ISSUE TITLE
refresh 'diff' view in DAG window only when hash of the viewed commit changes

### ISSUE THREAD

**Issue by jsilhan** [git-cola/git-cola#724]
Hi, my use case is to look at my commits through "Git DAG" window and clean code before I push it to my repo. It seems that every time I make *any* changes to the files in git directory (without committing) the the "diff" view renders again and jumps to the top of diff. Then I have to scroll back where was the code I recently reviewed. Is it possible to refresh the diff view only when hash of currently viewed commit changes, please?

This happens in version 2.10 and in the upstream (73408a0)

You have done a great job on git-cola - it is the fastest GUI git tool with clean design and fixing this issue can improve UX a bit. I could make a patch myself if you point me to the file of the change. Thanks.

**Comment by davvid** [comment]
A quick workaround is to disable inotify support.  Maybe we should add a way to disable it for the dag only.

Most of the code is in `cola/widges/dag.py` as well as around.  The way this gets triggered is the `cola/fsmonitor.py` registers for inotify events and sends a (probably overly-general) "update" signal that triggers `cola/cmds..py`'s Refresh class to issue a refresh command, triggering a GUI refresh.

You can disable inotify by doing `git config --global cola.inotiy false`.  It would be good to fix this, though. Having the UI automatically see new commits might be more of a usability burden than the use case you described -- I often hit it myself.

**Comment by davvid** [comment]
Thanks for reporting this issue.  The usability should be much improved now.

Not only do we now detect when the hash/object IDs change, but we also keep the scrollbars where they are, so that the diff viewport stays stable when a refresh does occur.

**Comment by jsilhan** [comment]
Confirming it works as expected. Even when new commit is added while browsing the old commits it stays in the same state.

Thanks @davvid for fixing this, you're awesome!
