### ISSUE TITLE
Stash does nothing

### ISSUE THREAD

**Issue by joshnoe** [git-cola/git-cola#733]
Steps to reproduce:

1. Modify some files
2. Select all modified files
3. Actions->Stash->Save
4. Enter a name of the Stash and click OK

Expected: Files are stashed.
Actual: No stash is created. Files remain shown as modified. No error is shown.

Version info:
Git Cola version 2.10 
Linux-4.12.5-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six 
Python (/usr/bin/python3) 3.6.2 (default, Aug 11 2017, 11:59:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] 
Git 2.13.5 
Qt 4.8.7 
QtPy 1.1.1 
PyQt4 (API v2) 4.12

**Comment by davvid** [comment]
Check the `Ctrl+0` Log window to see if there's any output reported by `git`.  Try running cola from a recent clone, as `v2.10` was over 500 commits ago.
