### ISSUE TITLE
Option to automatically add commit message template?

### ISSUE THREAD

**Issue by ebousse** [git-cola/git-cola#735]
It would be great to have an option to automatically _always_ load the commit message template, when preparing a commit message. What do you think?

**Comment by davvid** [comment]
That could be a useful feature.  I propose using the boolean `cola.commit.autotemplate` git config variable to enable the feature.

**Comment by stephenmoloney** [comment]
Is there a way to do this manually ?

**Comment by davvid** [comment]
Commit Menu > Get Commit Message Template

You have to configure `git config commit.template /path/to/your/template.md` first.

**Comment by stephenmoloney** [comment]
`Commit Menu > Get Commit Message Template`  that does it, thanks.
