### ISSUE TITLE
When new release?

### ISSUE THREAD

**Issue by francoism90** [git-cola/git-cola#742]
Thanks for creating git-cola. :)

Just an question: when would be the a new release zip?
I'm using the AUR stable package.

**Comment by davvid** [comment]
I'm going to try and tag a new release before the end of the month.  We caught one regression before today release which is good, and there might still be some more translations on the way..  @pavreh are you planning on having any more translation-related PRs before the end of the year?

#744 was recently reported related to Ubuntu and Gnome3.  The final bit of polish is fixing that issue before the next release.

**Comment by pavreh** [comment]
I will push one last commit for a new release during next two weeks, so the most visible strings should be translated.
