### ISSUE TITLE
cola/widgets/status.py: ambiguous source term: "Format String"

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#749]
The term "Format String" is quite ambiguous IMO, probably should change to something like "Format Specification String" just like `printf(3)`?

**Comment by Lin-Buo-Ren** [comment]
Nevermind, even `printf(3)` uses "Format String"

**Comment by davvid** [comment]
Thanks nonetheless, it's good to make sure it's easy to translate the app.
