### ISSUE TITLE
Option to increase the amount of recent repositories?

### ISSUE THREAD

**Issue by ebousse** [git-cola/git-cola#752]
At the moment, it seems that git-cola only shows the latest 6 or 7 repositories when opening up. However, it might happen to work with ~10 repositories, which then requires using the "Select manually" option to choose repositories that have been pushed out of the list.

Could we imagine an option to choose in the preferences the amount of recent repositories we want git-cola to remember, and hence to show up in the start window?

Note: I know that "favorites" can be used, but when git-cola opens up it only shows the recent repositories, not the favorites. Maybe yet another feature could be to show the favorites in the opening window.

**Comment by ebousse** [comment]
I guess the culprit is this line? :) https://github.com/git-cola/git-cola/blob/master/cola/settings.py#L128

**Comment by davvid** [comment]
Yes, that's the culprit.  We should make that configurable via `cola.maxrecent`, and default it to `10`.

Using `gitcfg.current().get('cola.maxrecent', 10)` instead of the hard-coded `8` can implement that feature after importing `gitcfg`.  Updating the documentation should be the bulk of the diff.

**Comment by ebousse** [comment]
I've just tested the master branch and it works just fine! thanks :)!
