### ISSUE TITLE
Support alt- keyboard shortcuts for menu navigation

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#759]
![_532](https://user-images.githubusercontent.com/1192163/33948784-c22a41dc-e062-11e7-8b3b-a0c65d24b242.png)

Currently Git Cola doesn't support menu navigation using the conventional alt- keyboard shortcuts, this creates difficulty for people don't have a pointer device or chooses to don't use one for some reason.

**Comment by davvid** [comment]
We should fix this, but not sure if it's something Qt is already doing automatically for us.

On debian, I was just able to type "Alt + Down" and it activated the menu.  I switched over to gnome (+lots of extensions and tweaks) from xfce4 and not sure if that's a gnome hotkey, but it activated the file menu, which then allowed me to navigate to the edit menu using the left and right arrow keys.  So maybe this already works?

MacOS might have its own hotkey to activate the menu.

**Comment by Vdragon** [comment]
Comparison: The compose that should be used to activate the sub-menu is underlined (at least when Alt is hold)

Currently Git Cola assigned some shortcuts that may conflict with the menu, like <em>E</em>dit (Alt+E)

![VLC](https://user-images.githubusercontent.com/1192163/36943812-dcb558be-1fca-11e8-9503-afff52dc6cfd.png)
