### ISSUE TITLE
can't use fcitx 

### ISSUE THREAD

**Issue by bitwater1997** [git-cola/git-cola#762]
With Gnome On Wayland , fcitx not  work just in git cola.
i can solve fcitx in java app, but i don't know why fcitx not work on git cola.

**Comment by davvid** [comment]
git-cola is a Qt app so this is probably an issue that affects all Qt apps.

Relevant?  https://wiki.qt.io/QtWayland

From that page, it suggests that you might be able to install the QtWayland modules (perhaps it's already installed, or available via apt/yum?) and then enable it by setting the `QT_QPA_PLATFORM` environment variable to `wayland`, e.g.

    env QT_QPA_PLATFORM=wayland ./bin/git-cola

what's the easiest way for me to test this on debian/stretch?  in any case, if the environment variable works let me know and I'll add this to our documentation.

**Comment by bitwater1997** [comment]
thanks your suggestion. sure, qt app may meet this question on ubuntu. 
Fortunately, i find a easy to solve this question.
in qt app , fcitx can work well after installing the  `fcitx-frontend-qt5` 

```shell
sudo pip install fcitx-frontend-qt5
dpkg -L fcitx-frontend-qt5 \| grep .so
# /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
```



copy `libfcitxplatforminputcontextplugin.so`to solve all question ,also work  in pyqt

solve qtcreator can't used fcitx

```shell
sudo cp libfcitxplatforminputcontextplugin.so ~/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/
```

to solve git-cola can't used fcitx

```shell
sudo cp libfcitxplatforminputcontextplugin.so /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforminputcontexts/

```

**Comment by Vdragon** [comment]
Yes, qt5 frontend is required to allow input methods to be used in Git Cola.

**Comment by Vdragon** [comment]
I would suggest to use the prepackaged Qt5 frontend provided by the fcitx-frontend-qt5 in Ubuntu instead from PyPI.  Comment if you have anymore problem regarding this issue.
