### ISSUE TITLE
failing tests 'git show' and 'git tag'

### ISSUE THREAD

**Issue by bket** [git-cola/git-cola#764]
git-cola v3.0 builds, and runs without any issue on Python2.7. However, I'm encountering 2 failing tests when running **nosetests --verbose test**:

```
======================================================================
FAIL: Test running 'git show'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ports/pobj/git-cola-3.0/git-cola-3.0/test/git_test.py", line 233, in test_show
    self.failUnless(content.startswith('commit '))
AssertionError: False is not true

======================================================================
FAIL: Test running 'git tag'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ports/pobj/git-cola-3.0/git-cola-3.0/test/git_test.py", line 227, in test_tag
    self.failUnless('v1.0.0' in tags)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 139 tests in 11.812s

```

Any idea where to look for identifying the root cause of failing these tests?

The 'git tag' test is OK when env GIT_COLA_NO_HISTORY=1 (as is done in .travis.yml). Explanation is given in https://github.com/git-cola/git-cola/blob/master/test/git_test.py#L222-L227. I'm not sure why this test is disabled in .travis.yml. Any ideas?

**Comment by davvid** [comment]
It's probably because you don't have the full history in your worktree (`git clone --shallow`, perhaps?).  Travis probably clones without history to speed up stuff.  Those tests haven't failed in a really long time, and we have other things we could test that don't require the history, so these tests can be reworked to not need history.  Thanks for the heads-up.
