### ISSUE TITLE
Space in to-be-created branch name leads to '"git branch" returned exit status "128"'

### ISSUE THREAD

**Issue by kannes** [git-cola/git-cola#765]
I don't know much about git so I had no idea I could not use a space in a branch name. Git Cola's Create Branch dialog just threw a `"git branch" returned exit status "128"` error in my face and I had no idea why.

Please present a nicer message to the user, eg "Branch names cannot contain spaces" or "Invalid characters in branch name" or something. :)

**Comment by davvid** [comment]
Thanks for the heads-up.  The input field now prevents invalid branch names so it shouldn't be possible to create branches with spaces (and other invalid characters) anymore.
