### ISSUE TITLE
Copy-paste shortcuts broken in MacOS

### ISSUE THREAD

**Issue by plsamuel** [git-cola/git-cola#767]
The Cmd+C shortcut is currently broken in the Diff window, have to do right-click + Copy menu.

Using version 3.0

**Comment by jedie** [comment]
Confirm with v3.0 unter linux, too :(

**Comment by davvid** [comment]
v3.2 is the latest stable

**Comment by jedie** [comment]
In ubuntu 18.04 is currently only v3.0 :(

**Comment by davvid** [comment]
It's really easy to try the latest version:

    git clone git://github.com/git-cola/git-cola.git
    ./git-cola/bin/git-cola

That should work just fine if you have the ubuntu version installed since you already have all of the python dependencies.

**Comment by jedie** [comment]
It's not so easy:
```
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
I don't quite understand. I have git-cola from the dirtribution installed... So I assume that every dependencies are installed.

**Comment by jedie** [comment]
Yes that's it!

shebang in "git-cola/bin/git-cola" is `#!/usr/bin/env python`

default python in ubuntu 18.04 is still 2.7 :(

So i can make just this: `python3 git-cola/bin/git-cola` and it works.
