### ISSUE TITLE
Build fails with "qtpy.PythonQtError: No Qt bindings could be found"

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#769]
Maybe (probably) it's just me falling off the build instructions here, but when running `make` in repo root I get the following errors:

```
Traceback (most recent call last):
  File "bin/git-cola", line 53, in <module>
    from cola.main import main  # pylint: disable=wrong-import-position
  File "/home/birger/Projects/leisure/git-cola/cola/main.py", line 7, in <module>
    from .app import add_common_arguments
  File "/home/birger/Projects/leisure/git-cola/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/home/birger/Projects/leisure/git-cola/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
python setup.py  build
running build
running build_mo
running build_scripts
```

I've installed
**qtpy** with `pip install qtpy`, and
**pyqt5** with `sudo apt install pyqt5-dev`

(Ubuntu 17.10)

**Comment by davvid** [comment]
On debian, at least, the name of the package is `python-pyqt5`.  Can you try installing that?  IIRC, `pyqt5-dev` is for C++ development against the pyqt5 headers.

The easiest way, though, is to do `sudo apt install git-cola` which will ensure that you have all the dependencies installed, and you can use a development version without any issues.

Let me know if this isn't working for you.

**Comment by birgersp** [comment]
Installing `python-pyqt5` solved the issue, thanks a lot!

So, to specify, I needed to install

**qtpy** with `pip install qtpy`, and
**pyqt5** with `sudo apt install python-pyqt5`

I think the next Debian/Ubuntu user also might appreciate this details, when trying to build the project. How about I create a PR with these details in the build instructions?

**Comment by davvid** [comment]
Sure thing, that sounds great.  There's a `HACKING` section in the README where it'd make sense to document it.

We also support PyQt4, so it's useful to test in both environments by having both installed and then using the `QT_API` environment variable to swap between the libraries.

e.g. `env QT_API=pyqt4 ./bin/git-cola` and `env QT_API=pyqt5 ./bin/git-cola`

**Comment by birgersp** [comment]
Struggling to find a smart place to document the specifics for Debian/Ubuntu. Maybe it's better to just leave it. Unlike me, Python devs will probably realize how to properly install the dependencies without any difficulty, anyways.

**Comment by Vdragon** [comment]
@davvid
> Sure thing, that sounds great. There's a HACKING section in the README where it'd
> make sense to document it.

The NUTRITIONAL FACTS section seems much reasonable for runtime dependencies, however it will clutter the content.  [A table is used in HIME for this matter.](https://github.com/hime-ime/hime/wiki/Software-dependencies-for-building-HIME)
