### ISSUE TITLE
Regression?: Menu disappeared

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#774]
![screenshot_20180311_125520](https://user-images.githubusercontent.com/1192163/37249906-99a94d44-252b-11e8-998d-9f2831c903ea.png)

The reckless guess is due to #759, not verified yet.  
Last working revision: Not sure, probably last time I update the zh_TW translation  
OS: KDE neon User Edition 5.12 (based on Ubuntu 16.04)
Locale: 

```
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_CN
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
```

**Comment by Vdragon** [comment]
## Bisect Result
```
5b7dd502587ce19e0c9cac0f6636930b8b8568f8 is the first bad commit
commit 5b7dd502587ce19e0c9cac0f6636930b8b8568f8
Author: David Aguilar <davvid@gmail.com>
Date:   Sun Mar 4 18:11:59 2018 -0800

    main: enable native menu bars
    
    Related-to: #759
    Signed-off-by: David Aguilar <davvid@gmail.com>

:040000 040000 3e0dc386a9c69b46278096c070b44abf64567e5d f206c01a992b2d2c22ffa67e0933d87e8461b419 M     cola
```

**Comment by Vdragon** [comment]
## Additional Info
- Linux-4.13.0-36-generic-x86_64-with-neon-16.04-xenial 
- Python (/usr/bin/python) 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609] 
- Git 2.7.4 
- Qt 4.8.7 
- QtPy 1.3.0.dev0 
- PyQt4 (API v2) 4.12

**Comment by davvid** [comment]
Thanks for the heads-up.  I'll revert that asap.
