### ISSUE TITLE
Launch Diff Tool not working on Ubuntu

### ISSUE THREAD

**Issue by moondowner** [git-cola/git-cola#776]
When I click 'Launch Diff Tool' it doesn't do anything, and in the console I see the following error: 

`The diff tool xxdiff is not available as 'xxdiff'
`

After doing `sudo apt install xxdiff` I don't get this error anymore, I successfully get the diff screen.

Ideally, xxdiff should be added as package dependency so that it's installed when git-cola is being installed.

**Comment by Vdragon** [comment]
xxdiff is a optional dependency with different alternatives like Meld, Kdiff etc. and shouldn't be listed as a strict dependency of Git Cola

The real issue is that Git Cola doesn't warn you graphically when it can not find a optional dependency.

**Comment by Vdragon** [comment]
Possible duplicate of #457
