### ISSUE TITLE
Git Cola hangs randomly with full cpu usage

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#781]
The window become unresponsive after certain amount of operations, and 100% single core cpu usage is noticed in the task manager.

## Bug Reproduction Instructions
Currently no reproducible method is found.  The only thing in common is it hangs after certain time of inactivity.

**UPDATE:** Seems to be more reproducible with this repo: https://github.com/slacka/WoeUSB  
It has custom git clean/smudge filters to deal with package versions, refer the setup-development-environment.bash script for more info.

## GIT_COLA_TRACE=all
```
git -c diff.suppressBlankEmpty=false config --get-all -z --show-origin cola.icontheme
git -c diff.suppressBlankEmpty=false config --null --file /etc/gitconfig --list
git -c diff.suppressBlankEmpty=false config --null --file /home/Lin-Buo-Ren/.gitconfig --list
git -c diff.suppressBlankEmpty=false config --null --file /home/Lin-Buo-Ren/工作空間/第三方專案/WoeUSB - A Linux program to create Windows USB stick installer from a real Windows DVD or an image/.git/config --list
git -c diff.suppressBlankEmpty=false version
git -c diff.suppressBlankEmpty=false update-index --refresh
git -c diff.suppressBlankEmpty=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false ls-files -z --
git -c diff.suppressBlankEmpty=false diff-files -z --
git -c diff.suppressBlankEmpty=false ls-files --exclude-standard -z --others --
git -c diff.suppressBlankEmpty=false rev-parse --symbolic-full-name HEAD
git -c diff.suppressBlankEmpty=false merge-base HEAD upstream/master
git -c diff.suppressBlankEmpty=false diff-tree --name-only -r -z --no-commit-id 11cab3c72083b691331dfe363267f486d3f02834 upstream/master
git -c diff.suppressBlankEmpty=false remote
git -c diff.suppressBlankEmpty=false for-each-ref --sort=version:refname --format=%(refname)
git -c diff.suppressBlankEmpty=false log --oneline upstream/master..master
git -c diff.suppressBlankEmpty=false log --oneline master..upstream/master
error: git-cola died of signal 9 # Killed via task manager
[1]+  Exit 137                git cola 
```

## About git-cola > Versions
```
Git Cola 3.0 版第 (v3.0-88-g2529306) 修訂版 
Linux-4.13.0-37-generic-x86_64-with-neon-16.04-xenial 
Python (/usr/bin/python) 第 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609] 版 
Git 第 2.7.4 版 
Qt 第 4.8.7 版 
QtPy 第 1.3.1 版 
PyQt4 (API v2) 第 4.12 版 
```

**Comment by davvid** [comment]
It's hard to say, does it happen all the time deterministically?  You're on xenial.. one thing to test might be worth testing is doing `sudo apt install python-pyqt5` and seeing if running with pyqt5 is better behaved. (for example, PyQt5 has better integration with newer gnome environments)

It prefers pyqt5 over pyqt4 when both are installed.

If that doesn't make a difference, then the next thing to do would be to try running the git commands listed above one after another (or in a short loop) and see if any one of them is causing the cpu or memory spike.

If there's a certain calling pattern that makes using the tool slow with large repos we can add some more features to our "turbo" mode where we try to avoid expensive operations at the expense of losing some non-critical features.  Let me know if any of these helps narrow down on the issue.

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance, switching to pyqt5 fixes the issue.  The problem probably is due to the rolling Qt distribution from KDE neon.
