### ISSUE TITLE
Support stripping multiple levels of ending folders in Copy > Copy Leading Path to Clipboard

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#784]
Sometimes only fewer levels of path is necessary to describe the change, it would be helpful if Git Cola can strip them automatically.

For example a staged file `distribution/snappy/snap/snapcraft.yaml`, one may want to use `distribution/snappy` or simply `distribution` as the commit title tag.

The expected interface is a sub-menu under Copy > Copy Leading Path to Clipboard, with stripped paths of different levels as options.

Thanks!

**Comment by davvid** [comment]
Sorry it took so long, but this is now available via the right-click context menu. It remembers your session state and hopefully it's intuitive enough.

There's still some minor styling issues that I'll be looking into, but the core functionality is now available. Thanks again!
