### ISSUE TITLE
PNG Image not displayed

### ISSUE THREAD

**Issue by futureweb** [git-cola/git-cola#788]
Hey there,

nothing serious ... but some PNG Images won't get displayed within the new Git Cola Image Viewer.
Sample: 

icon_arrow_up.png - http://temp.in.futureweb.at/icon_arrow_up.png
bannerVideoPlay.png - http://temp.in.futureweb.at/bannerVideoPlay.png

Maybe a Problem with the Alpha Channel?

bye from Austria
Andreas Schnederle-Wagner

**Comment by davvid** [comment]
PR #803 (thanks @xieofxie) should have fixed this issue.  Thanks for the report.
