### ISSUE TITLE
Visualize Current Branch & Visual All Branches spawn new git-cola instance

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#791]
When I try to use the _Visualize Current Branch_ or the _Visualize All Branches_ functions, the proper window is not started up.  Instead, they start a new instance of Git-Cola, bringing up the window asking you to select a repository, which appears when you first start up.

Paste of the info on git-cola's About/Version tab:
```
Git Cola version 3.0 (v3.0-116-gdcc61a0e) 
Windows-8.1-6.3.9600-SP0 
Python (C:\Users\Zauber\AppData\Local\git-cola\Python\pythonw.exe) 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] 
Git 2.11.0.windows.1 
Qt 5.10.1 
QtPy 1.3.1 
PyQt5 5.10.1 
```

**Comment by davvid** [comment]
I changed the default history browser to pass the `--repo <path>` argument when launching the DAG viewer.  Let me know if that's better behaved; I'll upload a new beta installer shortly.
