### ISSUE TITLE
[Feature Request] Search commit titles in "fixup" and "reuse" views

### ISSUE THREAD

**Issue by kakra** [git-cola/git-cola#795]
When doing a fixup, I sometimes already have a long history of small commits being queued up. Finding the correct commit can become quite difficult then. I'd like to have a very simple search function, maybe just by starting to type - different than it is currently implemented.

Currently, it just searches from the beginning of the titles. I think this is standard behavior of the list view.

I suggest that I could just type characters and this search string is found anywhere in the titles.

It could be made more obvious by adding an explicit search bar at the top of the titles.

**Comment by mdirik** [comment]
I second this request. That would be also very useful in "Load previous commit message" dialog (as it opens up the same "Select commit" dialog I presume.

**Comment by abid1998** [comment]
I can help with this issue if someone can point me to a direction.

**Comment by davvid** [comment]
Thanks @abid1998 that would be super cool! I believe the code in question is in `cola/selectcommits.py` and `git cola grep selectcommits` will point out the files where the functionality is used.
For the fixup/squash actions, the caller is `cola/widgets/commitmsg.py`

**Comment by abid1998** [comment]
@davvid from the problem statement it looks like i need to add a search bar and have it search the above list view ?
![image](https://user-images.githubusercontent.com/29145667/111129108-b2231200-859b-11eb-8ac9-8deb5e750743.png)
Something like this?

**Comment by davvid** [comment]
Nice. I'd suggest lifting the inputs to the very top so that the input flow is top-down, with the inputs up top and the results right below it.

**Comment by abid1998** [comment]
I have created search functionality how should i display it ? Because if i clear the items i will have to reset it on every new search.

**Comment by abid1998** [comment]
Moved the search and revision expression up. 
![image](https://user-images.githubusercontent.com/29145667/111137215-88221d80-85a4-11eb-8dee-807ed544a131.png)
Should i create another issue + PR for this ?

**Comment by kakra** [comment]
Do we really need a close button? It's now at the top, and usually there's a window decoration close button nearby (on MacOS it's even on the left side, so there's no point in having a close button there). In turn, the search bar could take the whole left-over space at the top.

**Comment by abid1998** [comment]
I have completed the Search functionality adding some screenshots -> 
![image](https://user-images.githubusercontent.com/29145667/111139112-ba347f00-85a6-11eb-9012-d23e698519e1.png)
![image](https://user-images.githubusercontent.com/29145667/111139163-ca4c5e80-85a6-11eb-9d68-f9a989e8f8fc.png)
Will raise a PR for search + UI changes after i clean the code a bit.

**Comment by abid1998** [comment]
Added a PR #1121. Please review it @kakra @davvid

**Comment by abid1998** [comment]
Final UI look:- 
![image](https://user-images.githubusercontent.com/29145667/111140934-ebae4a00-85a8-11eb-8b72-50b9f2ad004e.png)

**Comment by davvid** [comment]
that looks really nice! Good note about the close button -- if the window decoration already serves the purpose then we can keep it nice and simple/minimal.

**Comment by abid1998** [comment]
@davvid can you take a look at the PR https://github.com/git-cola/git-cola/pull/1121

**Comment by abid1998** [comment]
![Search](https://user-images.githubusercontent.com/29145667/111434658-cdba2400-8725-11eb-99b6-4192ddcfc2c5.gif)
