### ISSUE TITLE
"git cat-file" returned exit status 129

### ISSUE THREAD

**Issue by futureweb** [git-cola/git-cola#797]
Hey there,
running Master Branch from 27.03. - and getting often this failure (a few dozen Error Messages popping up without doing anything within cola):

![grafik](https://user-images.githubusercontent.com/1698881/38497488-8affeedc-3c01-11e8-99a8-06b2cf297909.png)

any ideas on that?

thx, bye from sunny Austria
Andreas Schnederle-Wagner

**Comment by davvid** [comment]
Ah, interesting.  It looks like we started relying on a newer `git cat-file` feature, the `--path=...` option when specifying `--textconv`, which first arrived in Git v2.11.0.

Please paste the version details from the File::About menu action's "Version" tab to help verify whether this is true.  We might be able to do this in a backwards-compatible way.

**Comment by futureweb** [comment]
there you go ;-)

Git Cola version 3.0 
Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core 
Python (/usr/bin/python) 2.7.5 (default, Aug 4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] 
Git 1.8.3.1 
Qt 4.8.5 
QtPy 1.3.1 
PyQt4 (API v2) 4.10.1

**Comment by futureweb** [comment]
Even with latest Master of GIT COLA I still get the Error?

![grafik](https://user-images.githubusercontent.com/1698881/38862376-09ee59b6-4235-11e8-99f0-b67ee78b0cb1.png)

**Comment by davvid** [comment]
Hmm.  Please run from the shell with `GIT_COLA_TRACE=1` set in your environment and copy the output that's printed right before this error message appears.

A helpful debugging aid would be to open a python console in the cola source tree and run this code inside python:

```
from cola import version
print(version.check_git('cat-file-textconv-path'))
```

What does it print?  It *should* print `False`.  If you see `True` then there's something else going on.

You can verify if you have the latest by typing `make` in the source tree and checking the version tab again. Here it says:  `Git Cola version 3.0 (v3.0-192-gacd26a71)`.

**Comment by futureweb** [comment]
right now I'm not entirely sure if I'm really on the latest Master as it only shows me Version 3.0 and not the extended Version Info you posted above?

![grafik](https://user-images.githubusercontent.com/1698881/38920900-b3b83e8e-42f4-11e8-94d8-425c6402d00e.png)


![grafik](https://user-images.githubusercontent.com/1698881/38920999-f592f7ea-42f4-11e8-952d-74a16f0d2c49.png)

**Comment by davvid** [comment]
Just a few notes.. the usual "don't run stuff as root" caveats.  Because it's not required to install cola to use it, I suggest running it from the source tree.

The easiest way for me to do that is to create a symlink in `~/bin` that points to the `bin/git-cola` script.  That way I never have to install it, and since `~/bin` is in my `$PATH` earlier than `/usr/bin`, that's the one that gets used..

One reason you might not see the extended version is you need to use `make` to build the project.  Use `make prefix=/usr install` to match what you did above, but I really wouldn't recommend installing into the `/usr` prefix.

Typically we let yum or apt manage `/usr`, so it might be worth running the `make uninstall` target and letting the distro-provided version take over the stuff installed under `/usr`.

`make prefix=/usr/local install` might be a safer alternative since it'll avoid clashing with any distro-provided files.

**Comment by davvid** [comment]
.. and assuming you are running the latest, please include the log output from running `env GIT_COLA_TRACE=1 ./bin/git-cola` -- just the parts right before it prints the error.

**Comment by futureweb** [comment]
thx for your Input - will change it they way you suggested ... but needs to be done in off Hours - asthe Binary is linked in a few dozens Home-Directories .... Our Devs/Template Coders are accessing GIT-COLA by RDP on Dev Server ... so unfortunately it's not a quick change to do ... (that was initially the reason why I simply hijacked the Distro Location of the Binaries when I tried GIT Version the first time a few weeks ago ... ;-)

Even fresh make/built Version won't show me more detailed Version Info?
![grafik](https://user-images.githubusercontent.com/1698881/38922670-0335d88c-42f9-11e8-80c7-53abfab53b5a.png)

anyway - will provide Trace as soon as Error occurs again (don't know how to trigger it ... it simply appears a few hours/days after Cola is started in the RDP Session)

**Comment by futureweb** [comment]
Well - that was fast - now as soon as I click on an Image the Error is triggered ...

> 04/18/2018 11:12:23 AM:  git version 1.8.3.1
> 04/18/2018 11:12:23 AM:  git cola version 3.0
> 04/18/2018 11:12:24 AM:  File system change monitoring: enabled.
> 04/18/2018 11:12:35 AM:  usage: git cat-file (-t|-s|-e|-p|<type>|--textconv) <object>
> 04/18/2018 11:12:35 AM:     or: git cat-file (--batch|--batch-check) < <list_of_objects>
> 04/18/2018 11:12:35 AM:  
> 04/18/2018 11:12:35 AM:  <type> can be one of: blob, tree, commit, tag
> 04/18/2018 11:12:35 AM:      -t                    show object type
> 04/18/2018 11:12:35 AM:      -s                    show object size
> 04/18/2018 11:12:35 AM:      -e                    exit with zero when there's no error
> 04/18/2018 11:12:35 AM:      -p                    pretty-print object's content
> 04/18/2018 11:12:35 AM:      --textconv            for blob objects, run textconv on object's content
> 04/18/2018 11:12:35 AM:      --batch               show info and content of objects fed from the standard input
> 04/18/2018 11:12:35 AM:      --batch-check         show info about objects fed from the standard input
> 04/18/2018 11:12:35 AM:  
> 04/18/2018 11:12:35 AM:  
> 04/18/2018 11:12:35 AM:  exit code 129

But I fear it's not more verbose than before?

**Comment by davvid** [comment]
Thank you, I think I see my mistake there.  I'll push up a new commit shortly.

**Comment by futureweb** [comment]
Would really love to say that this change fixed the behaviour for me - but with latest Checkout it's still throwing Errors at me! :-(

Since Transparent PNGs now got another Background (#803) - I can assume I'm on the latest Version even the Version String doesn't tell me ... ?

![grafik](https://user-images.githubusercontent.com/1698881/38977847-db2e8308-43b5-11e8-9de9-357336810082.png)

**Comment by davvid** [comment]
:man_facepalming: I missed one last call site.  Thanks for bearing with that.

**Comment by futureweb** [comment]
haha - you are welcome! ;-)
Guess your last change did the Trick ... no more Errors!! Perfect! 👍 

thx
