### ISSUE TITLE
Intent-To-Package: Snaps are Universal Linux Packages

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#798]
[Snaps are universal Linux packages](https://snapcraft.io/), since it packages all the runtime dependencies as one it can be installed to distros with unsupported or unavailable dependencies.

However, there are some known issues for packaging Git Cola in snap format:

* ~~[The `home` interface](https://docs.snapcraft.io/reference/interfaces) **doesn't provide access to non-hidden files**, which of course including `.git`s~~
* The input method compatibility is only partially implemented.  
  (UPDATE: iBus is now supported)
* Git --global configuration is not accessible

~~Currently, the only solution is to package it as a classic snap, which allows the same access to the host system as native apps., but doing so will [lose compatibility of all distros doesn't support classic snaps](https://docs.snapcraft.io/core/install#support-overview).~~

**Comment by Lin-Buo-Ren** [comment]
Related with #460 .

**Comment by Lin-Buo-Ren** [comment]
UPDATE: According to the answer to [New Interface Proprosal: The `git` interface - snapd - snapcraft.io](https://forum.snapcraft.io/t/new-interface-proprosal-the-git-interface/5498) snap apps do have access to the git repositories (with an exception of `$HOME/.git`) so this is no longer a blocker.

**Comment by Lin-Buo-Ren** [comment]
I am working on the packaging at [Lin-Buo-Ren/git-cola-snap: Snap Packaging for Git Cola](https://github.com/Lin-Buo-Ren/git-cola-snap), a PR will be filed when it is ready.

**Comment by davvid** [comment]
Awesome, thanks for taking this on.  I'm really excited to try it.

BTW, not sure if you've run into this.  If I take a machine and make `/etc/gitconfig` non-readable, I cannot fetch or push to this machine.  I haven't tested every corner of git in this configuration, but I would not be surprised if there are other parts that `die(...)` (that's a git library function that aborts the process) when that file is not readable.

Maybe the snap model can allow access to that path?  not sure if it's a problem, but it would make the behavior consistent for users that use the CLI git alongside snap packages, and expect both of them to pickup the system configuration.  Just a note in case that's related to any issues you've encountered along the way.

**Comment by Lin-Buo-Ren** [comment]
Apologies for not responding in time, there's a Git environment variable called `GIT_CONFIG_NOSYSTEM` that can avoid this problem at least in the local end.
