### ISSUE TITLE
Memory depleting problem when browsing vslavik/poedit

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#809]
## Issue Reproduction Instructions
1. `git clone --depth=1 https://github.com/vslavik/poedit.git poedit` # only one snapshot is required
2. Launch Git Cola and open the cloned repository

## Expected Result
The repository opened properly

## Current Result
Git Cola hangs, uses 100% CPU and starts allocating a huge amount of memory(>4.2GiB), might be more as the task manager freezes in the process), later shrinks to single-digit MiBs if the process isn't killed by the system due to insufficient memory

![screenshot](https://user-images.githubusercontent.com/13408130/39093842-9b54f55a-4658-11e8-85ed-15aa51166dcf.png)

## Additional Information
* Might be due to the huge object count(71101) in the repository

### System Info
* Ubuntu 16.04LTS
* 8GiB primary memory and 14GiB swap space

### Git Cola
Git Cola 3.0 版第 (v3.0-217-ga1f4867c) 修訂版

-   Linux-4.13.0-38-generic-x86_64-with-neon-16.04-xenial
-   Python (/usr/bin/python) 第 2.7.12 (default, Dec 4 2017, 14:50:18) \[GCC 5.4.0 20160609\] 版
-   Git 第 2.17.0 版
-   Qt 第 5.10.0 版
-   QtPy 第 1.3.1 版
-   PyQt5 第 5.9.2 版

**Comment by Lin-Buo-Ren** [comment]
This issue isn't being reproduced in Git GUI.

**Comment by Lin-Buo-Ren** [comment]
This issue is also reproduced with the Inkscape source repository, the system hangs over 10min. until the kernel killed the process.

**Comment by davvid** [comment]
Do you have the browser docked?  Another good debugging avenue would be to set `GIT_COLA_TRACE=1` in the environment and report back which git commands are holding it up.

For very large repos that use the browser (which its information labels that have to do many git queries) we have a `cola.turbo` configuration variable you can set which disables those lookups.
