### ISSUE TITLE
Avoid localized timestamp in Console widget

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#817]
![screenshot_20180509_235923](https://user-images.githubusercontent.com/13408130/39825682-0469d652-53e5-11e8-9cfc-d4302c8745c9.png)

It takes too much space and has no benefit, simple `YYYY/MM/DD HH/MM/SS: ` will be enough.

**Comment by davvid** [comment]
@alex-gulyas any thoughts?

**Comment by alex-gulyas** [comment]
@davvid: I think we have 3 options:

1. Use the users locale
The whole point of locales is that apps can display information in a way that is natural to the users. I strongly believe that this is the better choice, unless you don't mind implementing option 3.
2. Use a hard coded format
There are a lot of different ways to format dates/times, so there is no single format that will please everyone. If this option is selected, then I highly suggest to use an international standard format, like ISO 8601: `%Y-%m-%d %H:%M:%S` (2018-05-09 23:58:13).
3. Make it user configurable
This might be overkill, but this would resolve date/time formatting related issues once and for all. (The default format should be the localized one.)

@Lin-Buo-Ren:
- Your suggested format would reduce the width of the date/time format by 6 characters (6 double width chars -> 6 single width chars). But as soon as git starts to print out paths and other messages, the lines would have to be wrapped anyway. Maybe increase the width of the console widget (or redock it to make it full width within the app window)?
- On Linux (sorry, I'm not familiar with other systems) there is a way to force a different locale to a specific application.

**Comment by davvid** [comment]
ISO-8601 really makes a lot of sense here.  Thanks for the sug.
