### ISSUE TITLE
fedora build of git-cola is broken for a long time

### ISSUE THREAD

**Issue by 4ndrej** [git-cola/git-cola#827]
Hello,
I found out that git-cola is not part of fedora (26, 27, 28 and rawhide) because it's broken, at least since 2017-11-20.

The build logs are available at https://apps.fedoraproject.org/koschei/package/git-cola?collection=f27
I am not able to fix it but maybe some python guru could.

https://kojipkgs.fedoraproject.org/work/tasks/4079/26844079/build.log
```
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.X5Z86T (%install)
    Bad exit status from /var/tmp/rpm-tmp.X5Z86T (%install)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/git-cola.spec
```
thanks,
a.

**Comment by davvid** [comment]
Thanks for the heads-up.  A fedora PR was submitted to fix this issue. cheers

https://src.fedoraproject.org/rpms/git-cola/pull-request/1

**Comment by davvid** [comment]
i believe this has since been fixed in fedora.  Please reopen this bug if this is not the case.

**Comment by 4ndrej** [comment]
It was fixed in f29 but this one line fix is still missing in (still supported) f27 and f28 branches which is bad.
