### ISSUE TITLE
Windows shell integration not working

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#831]
There's no "Git Cola Here" shell integration option in the contextual menu in Explorer in Windows 10 1803.  I wonder if it's still available?

**Comment by davvid** [comment]
Hmm, IIRC we lost that feature when we switched to using the (much nicer!) pynsist toolchain for generating Windows installers.

@takluyver is this something pynsist could reasonably support without needing for the user to provide a custom template?  Defining explorer shortcuts that can take paths as arguments seems like a pretty generic feature that other projects could leverage.

If you think would be not too hard to implement then maybe I can can help hobble together something from the snippets that we were using in the [old installer](https://github.com/git-cola/git-cola/blob/a587b06432c6f437052f49656c88ec4a5f256c4e/contrib/win32/install.iss).

The first part is a line in the `[Tasks]` section that tweaks a flag called `guiextension` via a checkbox.  This allows the user to install the "Git Cola Here" shell integration:

```
[Tasks]
Name: guiextension; Description: "Add ""Git &Cola Here"""; GroupDescription: "Windows Explorer integration:"; Flags: checkedonce
```

Later in the `CurStepChanged` function (I don't know what means ;-)) we create it:

```
    {
        Create the Windows Explorer shell extensions
    }

    if IsAdminLoggedOn then begin
        RootKey:=HKEY_LOCAL_MACHINE;
    end else begin
        RootKey:=HKEY_CURRENT_USER;
    end;

    if IsTaskSelected('guiextension') then begin
        if (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_cola','','Git &Cola Here'))
        or (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_cola\command','','"'+EdtPython.Text+'" "'+AppDir+'\bin\git-cola.pyw" "--repo" "%1"')) then begin
            Msg:='Line {#emit __LINE__}: Unable to create "Git Cola Here" shell extension.';
            MsgBox(Msg,mbError,MB_OK);
            Log(Msg);
            // This is not a critical error, the user can probably fix it manually,
            // so we continue.
        end;
    end;
```

Lastly, the uninstaller snippet from `CurUninstallStepChanged`:

```
    {
        Delete the Windows Explorer shell extensions
    }

    if IsAdminLoggedOn then begin
        RootKey:=HKEY_LOCAL_MACHINE;
    end else begin
        RootKey:=HKEY_CURRENT_USER;
    end;

    Command:='';
    RegQueryStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_cola\command','',Command);
    if Pos(AppDir,Command)>0 then begin
        if not RegDeleteKeyIncludingSubkeys(RootKey,'SOFTWARE\Classes\Directory\shell\git_cola') then begin
            Msg:='Line {#emit __LINE__}: Unable to remove "Git Cola Here" shell extension.';
            MsgBox(Msg,mbError,MB_OK);
            Log(Msg);
            // This is not a critical error, the user can probably fix it manually,
            // so we continue.
        end;
    end;
```

Do you think supporting these types of actions would fit well into pynsist's design?  If you think so I could try to dive in and implement that feature.  Any suggestions on where to best start reading in the code and whether this would be fairly straightforward to implement?

Design guidance on what the config structure should be and how to best expose the feature, either by extending existing constructs or adding new ones, would be greatly appreciated.  Thanks again for pysnist.

**Comment by takluyver** [comment]
Thanks for the idea and the offer to work on it. However, I don't think that Windows shell integration is in scope for Pynsist itself. I've written a doc page on how I try to keep the scope manageable:
http://pynsist.readthedocs.io/en/latest/design.html

I'm happy to give some pointers on using a custom template for this, and if you get it working, I'd love to get an example in the pynsist repository showing how to do it.

Sorry to give an answer that's mainly 'no', but I hope this doesn't stop you working on it. :-)
