### ISSUE TITLE
Unable to stage a PNG file currently tracked by Git LFS

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#841]
## Issue Reproduce Instructions
1. Create a new repository
1. Start tracking (add, stage, and commit) a PNG file
1. Initialize Git LFS
1. Track PNG files with Git LFS by running `git lfs track '*.png'` in a terminal in the repository
1. Back to Git Cola

## Current Behavior
The PNG file is marked as "Modified" but there's no "stage file" option in its contextual menu

![peek 2018-06-12 00-00](https://user-images.githubusercontent.com/13408130/41243009-b7d115d6-6dd3-11e8-90f6-6cb580c6f477.gif)

## Workaround
Double click on the file works

## Additional Information

Git Cola version 3.1 (v3.1-28-gd5caab1b) 

- Linux-4.13.0-43-generic-x86_64-with-neon-16.04-xenial 
- Python (/usr/bin/python) 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609] 
- Git 2.17.1 
- Qt 5.10.0 
- QtPy 1.3.1 
- PyQt5 5.9.2

**Comment by davvid** [comment]
Thanks again for all these reports.  It's looking like we should tag a new release soon, perhaps shortly after adding the revert and stash pop sugs ;-)
