### ISSUE TITLE
Layout does not get preserved between multiple launches of git-cola

### ISSUE THREAD

**Issue by jakubklos77** [git-cola/git-cola#848]
I have tried almost anything but each time I run git-cola the layout configuration gets resized a few pixels.
It does not really matter if I use the Lock Layout option in the View menu.

The vertical splitter jumps a few pixels to the right and so do the horizontal splitters (more to the top)
The vertical splitter keeps doing this until it is in the center of the window.

Testing the current git master. What can I do to help to fix this issue?
Thank you

**Comment by jakubklos77** [comment]
I wanted to debug this and while testing I have figured out the issue occurs only when the window is maximazed. If it's not maximized/fullscreen then it works properly. Although between restarts of "git-cola" the window slightly moves to the left a few pixels until it gets aligned with x=0. Somebody should look at this.
Thank you

**Comment by davvid** [comment]
Thanks for the heads-up.  What OS are you using?  If Linux, what window manager?  I'll see if I can reproduce it.

**Comment by jakubklos77** [comment]
Thank you David.
Yes, running on Linux. I use the gala window manager (Elementary OS) but have just tested Ubuntu 18.04 (gnome window manager I believe) and the behavior is the same.

I have also tried the tweak as you mentioned above and it also does not seem to help.

I started git-cola with the default settings and moved the vertical splitter to the left (it was in the center by default). Then restarted and it does not stay in position.

I haven't tested it on Windows as I abandonded that OS some time ago :)

Thank you

**Comment by davvid** [comment]
Me too ;-) thanks for the verification.

I'm able to reproduce the issue now.  I see why I wasn't able to before -- my layout was always within the margins where the widget sizes wouldn't trigger it.  I think I have a solution that should solve this nicely.  Thanks for the heads-up.

Today I learned that I shouldn't try to implement my own window maximized and sizing logic -- just let Qt's saveGeometry / restoreGeometry handle it.  We have custom logic for restoring window sizes, and that seems to be the core issue.

**Comment by jakubklos77** [comment]
Glad you got it reproduced. Good job.
Love git-cola a lot :). I used to do all the git work in bash but git-cola makes my work so much faster.
Thank you

**Comment by davvid** [comment]
This should be much better behaved now.  Note, that one issue remains, but it's a tiny one.

One the very first launch, when no settings are present, the middle splitter can't be resized.  Once we restart the app, this issue goes away, and everything works as expected.  That is a Qt5-only bug.  I tested Qt4 and it does not exhibit that behavior:

    env QT_API-pyqt4 ./bin/git-cola

This lines up with some bugs that have been submitted against Qt, and explains why we didn't see this in the past:

https://bugreports.qt.io/browse/QTBUG-65592

https://stackoverflow.com/questions/48119969/qdockwidget-splitter-jumps-when-qmainwindow-resized

In any case, this should be a non-issue in practice now.  Qt4 should be fine, and Qt5 will be fine once you start up and shutdown the app once with the new code.
