### ISSUE TITLE
keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by kopach** [git-cola/git-cola#852]
**git-cola version**: 3.1
**OS**: macOS High Sierra 10.13.3

Steps to reproduce:
1. Select staged files
2. press **Cmd+u** to unstage selected files -> confirmation dialog will pop up
3. neither **enter** nor **escape** work here as it was in previous version
4. click `cancel` button by mouse -> selected files still remind selected and focused (highlighted in blue)
5. press **Cmd+u** again -> also not working

The same steps are reproducible for other keyboard shortcuts: e.g. to delete untracked files (**Cmd+Backspace**), etc

This behaviour is really frustrating me all the time as I get used to work with git-cola mainly by using shortcuts.

**Comment by davvid** [comment]
We recently swapped out the use of QMessageBox because we were loosing focus on Linux (MATE).  I think we should be able to fix this -- maybe we just need to set the window modality to ApplicationModal for the MessageBox replacement dialog.  We'll get this fixed before we tag v3.2.

Just to verify -- are you running the latest version in master?

**Comment by kopach** [comment]
Hi @davvid. Thank you for your response. As I mentioned in description - this issue is reproducible for me only on current latest released version - `v3.1`. So, to test this you would need to do `git checkout v3.1`. On the time of opening this issue I wasn't able to test keyboard shortcuts on latest changes from `master` branch as app was crashing for me (as described here: https://github.com/git-cola/git-cola/issues/851). Anyway, now I'm able to run app built from `master` and can confirm that shortcuts works properly even there (4409089). I've also tested `messagebox` branch just in case - everything is working there also. But as it works on `master` - probably no need in those changes from `messagebox`.

**Comment by davvid** [comment]
Sweet, thanks for the heads-up.  I'll be releasing a new version soon (late July / early August).
