### ISSUE TITLE
Useless "Question Mark" Button in Windows Build

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#856]
In most sub-window/dialogs(stash/pull/push/checkout/about) in Windows build the "question mark" button is available in the title bar but is useless as no help message can be triggered in this mode.  It should be removed when there's no functionality.

![screenshot](https://user-images.githubusercontent.com/13408130/42144220-9096656a-7dec-11e8-8198-43a44aaeceb3.png)

**Comment by davvid** [comment]
I changed the base Dialog class so that we remove the `Qt.WindowContextHelpButtonHint` from its window flags.  Let me know if that does the trick!
