### ISSUE TITLE
Allow plaintext diff for SVG files

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#859]
Currently, Git Cola shows image diff for SVG files, however sometimes plaintext diff is much preferable in these files, the diff widget should allow switching between image diff and plaintext diff in these cases.

**Comment by davvid** [comment]
Makese sense.  When we added image support one of the thoughts I had was how someone might want to disable that feature.  Having a switch sounds like a great idea.

**Comment by lah7** [comment]
I created a PR for this feature at #1035.

My original idea was to show a radio/dropdown in the diff area, similar to how GitHub would present two options:

![image](https://user-images.githubusercontent.com/13032135/72653282-0f183d80-3982-11ea-94e5-a95e020e31d6.png)
_(Image mock up only)_

However, I didn't quite figure out how to do this so I went with an on/off toggle in the preferences instead.

**Comment by davvid** [comment]
I've started integrating this feature into the diff editor directly.   There's now a toggle button that enables/disables the image diff mode.  This lays the foundation for automatically remembering the state of this toggle, which will be added shortly.

Thanks for the sugs!  I'm going to take another round at it later tonight with the goal of making it remember the toggle on a per-filetype basis, but for now you can test out the toggle in `master`.

**Comment by davvid** [comment]
This is now feature-complete in master.  It automatically remembers its state on a per-file-extension basis, and does so automatically.
