### ISSUE TITLE
failed to install pythin3.4 on git-cola's Travis CI Environment

### ISSUE THREAD

**Issue by fu7mu4** [git-cola/git-cola#872]
I sent pull request japanese-update (see https://github.com/git-cola/git-cola/pull/871) .
but your travis ci had problem. it said that:
``
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (7) Failed to connect to s3.amazonaws.com port 443: Connection timed out
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
``
https://travis-ci.org/git-cola/git-cola/jobs/414792543

please fix the travis ci environment .

**Comment by davvid** [comment]
AWS often fails.  unfort. there's not much we can do about that besides restart the build.  That fixed it.
