### ISSUE TITLE
Honour XDG_DATA_HOME and XDG_DATA_DIRS when loading spellchecking dictionaries

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#873]
https://github.com/git-cola/git-cola/blob/0c846e7568da496fe8864e84c1de1c1b3abb35f2/cola/spellcheck.py#L53-L55

Currently, Git Cola appears to hardcode path of spellchecking dictionaries under /usr, which is not always the case(Flatpak: /app, Snap: /snap/_snap_name_/current; user may supply their own dictionaries via $HOME/.local).

Git Cola should honor the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use the first valid file in `XDG_DATA_HOME` and `XDG_DATA_DIRS` so that the behavior can be modified at runtime.

>  `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME`/.local/share should be used.
>  
>  `$XDG_DATA_DIRS` defines the preference-ordered set of base directories to search for data files in addition to the `$XDG_DATA_HOME` base directory. The directories in `$XDG_DATA_DIRS` should be seperated with a colon ':'.
>  
>  If `$XDG_DATA_DIRS` is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

**Comment by davvid** [comment]
Thanks for the sug!

**Comment by davvid** [comment]
The lookup details and environment variable usage is documented here:

https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-dictionary
