### ISSUE TITLE
i18n: Git Cola shouldn't strip string source locations from POs

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#880]
String source locations is helpful for translators to find out where a string actually used in the context.  This helps avoid errors like #881 .

**Comment by Lin-Buo-Ren** [comment]
> The reason we remove the source locations is to avoid merge conflicts and the constant churn that happens when line numbers change.

I would suggest only update PO files per release and only accept translation patches that based on the currently released PO files.

**Comment by Lin-Buo-Ren** [comment]
> The reason we remove the source locations is to avoid merge conflicts and the constant churn that happens when line numbers change.

I would suggest only update PO files per release and only accept translation patches that based on the currently released PO files.

**Comment by Lin-Buo-Ren** [comment]
Oops, blame the unicorn.

**Comment by davvid** [comment]
Ok, we can tweak the `extras/build_pot.py` code to restore the line numbers.  The problem does remain, though, that once we accept a patch they'll no longer be the currently released PO file, but that probably won't be an issue in practice.

**Comment by Lin-Buo-Ren** [comment]
I believe merge conflicts should be handled by the translators themselves.

**Comment by davvid** [comment]
Thanks again for the heads-up! I've restored all of the line number information now.
