### ISSUE TITLE
Do not suggest yaourt as an Arch packet manager

### ISSUE THREAD

**Issue by EgZvor** [git-cola/git-cola#883]
This issue #117 was resolved by suggesting the `yaourt` AUR helper. Nowadays it is considered harmful. 

In my opinion it's best to just have an AUR package name `git-cola` and the mention that it is in indeed in AUR without suggesting dangerous tools. Arch is a DIY distro and it is not in the spirit of it to blindly input command that installs the package. AUR is not a safe space.

**Comment by davvid** [comment]
I'm a debian user so I'm completely ignorant of these fine arch considerations.

Is there a one-liner install command we can recommend instead?  I was surprised that this report didn't suggest an alternative, or included a PR to change the line.  I don't mind periodically tweaking that line in the docs, though.

If there's no easy one-liner that fits into the spirit of the arch community then we can just delete the section altogether.  Let me know what you think.

**Comment by EgZvor** [comment]
Yep, that looks good, thanks. Sorry about the PR, it didn't came to my mind that the site code is in the repository as well.
