### ISSUE TITLE
DAG: Revert commit silently fails when corresponding files are modified

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#885]
## Bug Reproduce Instructions
1. Modify a file
1. Stage the file and create a commit
1. Modify the file again
1. Attempt to revert the previously created commit

## Current Behavior
Action silently fails, DAG graph not changing, no error message in the main window's console output widget.

## Expected Behavior
An error dialog popup telling the user that the action failed and why.

## Git Cola
```
Git Cola 第 3.2 版(v3.2-6-gc1866f10) 
Linux-4.15.0-33-generic-x86_64-with-neon-16.04-xenial 
Python (/usr/bin/python) 第 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609] 版 
Git 第 2.18.0 版 
Qt 第 5.11.1 版 
QtPy 第 1.4.2 版 
PyQt5 第 5.11.2 版 
```

**Comment by davvid** [comment]
Thanks for the heads-up! This will be in the upcoming v4.2.0 release.
