### ISSUE TITLE
Upgrade the outdated version of git-cola (2.10) on Fedora repository

### ISSUE THREAD

**Issue by gsag** [git-cola/git-cola#887]
Distro: Fedora 27
Available package: git-cola-2.10-2.fc26.noarch

**Comment by Lin-Buo-Ren** [comment]
Shouldn't these kinds of issue should be sent to the package's maintainer instead of the upstream?

**Comment by Lin-Buo-Ren** [comment]
[Overview - rpms/git-cola - Pagure](https://src.fedoraproject.org/rpms/git-cola)
![default](https://user-images.githubusercontent.com/13408130/45272205-7399d180-b4de-11e8-9eb1-4f20c8fab54d.png)

**Comment by gsag** [comment]
Sorry about opening such issue here. Do you know how can I contact the fedora package's maintainer?

**Comment by gsag** [comment]
Thank you @Lin-Guo-Ren . Sorry about the inconvenience.
