### ISSUE TITLE
Upgrade the outdated version of git-cola (3.1) on AUR

### ISSUE THREAD

**Issue by nils-van-zuijlen** [git-cola/git-cola#888]
Distro: ArchLinux
Available package: git-cola-3.1-1

**Comment by Lin-Buo-Ren** [comment]
[AUR (en) - git-cola](https://aur.archlinux.org/packages/git-cola/)
![default](https://user-images.githubusercontent.com/13408130/45272267-e30fc100-b4de-11e8-904f-f49e28f28dba.png)

**Comment by davvid** [comment]
It looks like Arch has 3.11 these days, and there's a maintainer listed, so this can be considered done. Thanks for the heads-up.
