### ISSUE TITLE
Ctrl+C (copy) doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by rinu** [git-cola/git-cola#901]
I'm unable to copy code from git-cola using Ctrl+C on Ubuntu 18.04 (xfce desktop). It's not isolated to one computer, it has happened on two machines I use.

Right clicking and selecting Copy does work however.

I understand this issue is only with version 3.0 (from https://github.com/git-cola/git-cola/issues/846). That is unfortunately the version in the Ubuntu repository. Can you update the Ubuntu package? Is there are workaround for 3.0? Is there a ppa for upgrading?

**Comment by davvid** [comment]
https://github.com/git-cola/git-cola/#ubuntu

**Comment by xmik** [comment]
I have built git-cola v3.3, installed it on Ubuntu 18.04 and the Ctrl+C behavior is still the same as @rinu observed.
