### ISSUE TITLE
The section: "Status", could be rendered the information like a tree

### ISSUE THREAD

**Issue by yferras** [git-cola/git-cola#902]
Now all the files are classified as: Staged, Modified, Untracked. But the list of files for each category has the same margin as its own category entry. Sometimes I have to look many times to differentiate which is which. But if the margin is different between the category and the list of files, I think that each user will be able to identify the category and the file in question more quickly. 
The follow image is for reference:
![ref](https://user-images.githubusercontent.com/11029945/48148800-a23aeb00-e288-11e8-9fd9-ef57aa13719a.png)

**Comment by davvid** [comment]
Green is always staged, but besides that, we now have an option to enable this behavior thanks to @javierrodriguezcuevas
