### ISSUE TITLE
documentation for color settings is ambiguous

### ISSUE THREAD

**Issue by playmyskay** [git-cola/git-cola#907]
The documentation says:

> cola.color.text
> 
> The default diff text color, in hexadecimal #RRGGBB notation. Defaults to “#030303”.
> cola.color.add

This is right so far but if you set your colors via `git config` you have to set your value like '00ff00' without the leading sharp ('#').

Example:
works **not**: `git config --global cola.color.remove #ff0000`
works: `git config --global cola.color.remove ff0000`

For those who are interested in getting dark theme with gtk i have written some instructions here:
https://github.com/git-cola/git-cola/issues/760#issuecomment-440381021

**Comment by davvid** [comment]
This is a shell-quoting issue.  Bash sees the last item as a comment.  Works fine in zsh and some others.

This should work just fine everywhere:

    git config --global cola.color.remove '#ff0000'

Note the single-quotes around the value.  So it's not really ambiguous, it's just the usual shell shenanigans.  I updated the documentation to provide a hint.
