### ISSUE TITLE
Error when launching git-cola

### ISSUE THREAD

**Issue by kapad** [git-cola/git-cola#908]
System: Ubuntu 18.04

I've installed git cola from the Ubuntu repositories. The package version for git-cola is `3.0-1ubuntu1`. 

When I try and launch git-cola, I get the following error message. I can't tell what's changed. I was already using git-cola on my laptop, and then when I tried using it again after a week or so, it simply failed to launch. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 53, in <module>
    from cola.main import main  # pylint: disable=wrong-import-position
  File "/usr/share/git-cola/lib/cola/main.py", line 7, in <module>
    from .app import add_common_arguments
  File "/usr/share/git-cola/lib/cola/app.py", line 14, in <module>
    from qtpy import QtCore
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by davvid** [comment]
Try `sudo apt install python-pyqt5 python3-pyqt5` that'll get you the Qt bindings.

I'm surprised the package doesn't already depend on it -- it might be reporting that to the ubuntu/debian package maintainers.  This was reported previously.

Please see https://github.com/git-cola/git-cola/#ubuntu for a PPA.

Once you have that, you might as well run a newer version by arranging for the `bin/` directory in this source tree to be in your $PATH.  cheers

**Comment by kapad** [comment]
`python3-pyqt5` was already installed on my system but `python-pyqt5` wasn't, so I then installed that. Also, I was using the version of git-cola from the ubuntu repositories, so I went ahead and added the PPA maintained by pavreh and reinstalled the `git-cola` package. 

And I'm still getting the same error (a couple of line numbers have changed, but the error is still the same).
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 53, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by kapad** [comment]
@davvid you've closed this issue, but I'm still getting the above error. Could it be related to some other dependency missing on my system? Any suggestions on how to check which dependencies are missing?

**Comment by davvid** [comment]
Run these commands in your shell and it'll help narrow down what's going on.

0. Do you have `QT_API` exported in your environment somehow?

        echo $QT_API

1. What python is git-cola using?

        head -n 1 /usr/bin/git-cola

2. Can python2 import qtpy?

        python -c 'import qtpy'

3. Can python3 import qtpy?

        python3 -c 'import qtpy'


The way it's supposed to work is that you shouldn't need to have `QT_API` set.  It's supposed to find `PyQt5` and use that version by default.

The error message you're getting is related to not being able to import Qt modules.  These commands might help too:

        python3 -c 'from PyQt5 import QtCore; print(QtCore)'


Is it possible that you have a incompatible modules in `~/.local/lib/python3*` ?  Importing the modules directly like above should uncover the root problem.

**Comment by kapad** [comment]
1. `QT_API` isn't set. 
```
$ echo $QT_API

```
2. git-cola is using python3
```
$ head -n 1 /usr/bin/git-cola
#!/usr/bin/python3
```
3. python cannot import qtpy
```
$ python -c 'import qtpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named qtpy
```
4. python3 cannot import qtpy
```
$ python3 -c 'import qtpy'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

I also tried your last suggestion, to import `QtCore` directly from `PyQt5` but that didn't work either. I've tried purging and reinstalling all the Qt packages, but that hasn't helped either. 
```
$ python3 -c 'from PyQt5 import QtCore; print(QtCore)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Also, 
`~/.local/lib` doesn't have a sub directory for python 3.x. `/usr/local/lib` does have a `python3.6` directory but that is empty. (technically, it has a `dist-packages` dir which is empty)

**Comment by kapad** [comment]
Okay. This issue is fixed now. :grinning: 

The problem wasn't about missing python qt5 dependencies, but the qt5 core libs had broken on my system for some reason. 

running "sudo apt-get install --reinstall libqt5dbus5 libqt5widgets5 libqt5network5 libqt5gui5 libqt5core5a libdouble-conversion1 libxcb-xinerama0 ' fixed my issue. 

Note: `libdouble-conversion1 libxcb-xinerama0` are probably not required, but I couldn't open virtualbox either, and that command fixed running virtual box (gui) for me as well as git-cola.

Thanks for the help @davvid
