### ISSUE TITLE
[Windows 10] High CPU usage in fontdrvhost.exe when scrolling DAG

### ISSUE THREAD

**Issue by nyanpasu64** [git-cola/git-cola#910]
Git Cola version 3.2 (v3.2-6-gc1866f10) 
Windows-10-10.0.16299-SP0 
Python (C:\Program Files (x86)\git-cola\Python\pythonw.exe) 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] 
Git 2.20.0.windows.1 
Qt 5.10.1 
QtPy 1.4.2 
PyQt5 5.10.1 

Clicking "Visualize all branches" (which I manually hooked up to git-cola dag) opens a graph.

Scrolling the DAG causes high CPU usage in both pythonw.exe and fontdrvhost.exe.

----------

I also have other (largely lag) issues, maybe I should report elsewhere.
- Editing preferences causes UI to freeze for ~0.4 seconds.
- Doesn't respond to filesystem changes until Ctrl+R in the main GUI. Doing so causes brief freezing. Hold down the combo for a few seconds, to freeze program for 10 seconds.

**Comment by davvid** [comment]
No one's really stepped up to take a look at this so closing for now. Sorry 'bout that but this seems like a Windows-specific issue.
