### ISSUE TITLE
Help with remote push/pull

### ISSUE THREAD

**Issue by davidsavoie1** [git-cola/git-cola#922]
I'm using Git Cola on Linux Ubuntu and I am having issues pulling/pushing to remote repository (Bitbucket, private repo). Each time I try either command, I get an error stating that the username or password is wrong, but I didn't get any chance to enter it.

I've read [many issue threads](https://github.com/git-cola/git-cola/issues?utf8=%E2%9C%93&q=push+password) related to this kind of problem and I was able to make it work if I launched Git Cola from the shell, in which case the password prompt would occur in it on each action. It's not intuitive to me and quite repetitive. I wasn't able to configure anything to save the password or prompt me for login.

**Is there someone who could help me with the setup?**

I used GitKraken in the past, but I want to switch for performance reasons. In GitKraken, I only had to log into my Bitbucket account once and everything worked from there.

**Comment by richarson** [comment]
When I push, I get a prompt that uses `wish` asking for my password, e.g.:

```
$ ps fax | grep -v "grep --color" | grep -e pass -e git
32551 ?        Sl     0:03  \_ /usr/bin/python /usr/bin/git-cola --prompt
32673 ?        Ss     0:00      \_ git -c diff.suppressBlankEmpty=false push --verbose origin master
32674 ?        S      0:00          \_ /usr/libexec/git-core/git-remote-https origin https://github.com/richarson/slackbuilds
32679 ?        Sl     0:00              \_ wish /usr/share/git-cola/bin/ssh-askpass -- Password for 'https://richarson@github.com':
```

Make sure to have Tk installed on your system.

FWIW, I also have in my .gitconfig:

```
[credential]
    helper = cache
```

**Comment by jm4R** [comment]
Install `wish`:
> sudo apt-get install wish

I guess this should be a dependency package for git-cola on Ubuntu (or Debian). You may want to make an issue for Ubuntu's bugtracker.

**Comment by davidsavoie1** [comment]
Thanks for all the answers...

I had already tried to install *wish* from what I had read elsewhere, but apparently, it was already installed.
```
Note, selecting 'tk' instead of 'wish'
tk is already the newest version.
```
Is there something I could check to understand why it doesn't show any dialog?

**Comment by davvid** [comment]
The key piece is configuring `core.askpass` as noted in the blog post above.  Cola doesn't actually handle the password prompt -- it's handled by git and ssh itself.

We include a default askpass program if nothing is installed, but it's a good idea to install a better askpass program and configure `core.askpass`, as noted in the blog post above.  Example using gnome-ssh-askpass

    sudo apt install ssh-askpass-gnome
    git config --global core.askpass /usr/lib/openssh/gnome-ssh-askpass
    
    # For completeness, add this to your ~/.bashrc and logout/login
    SSH_ASKPASS=/usr/lib/openssh/gnome-ssh-askpass
    export SSH_ASKPASS

If the askpass helper is still not being used then perhaps the reason could be related to the url you're using with bitbucket.  If you're using an `https` url, try using an `ssh` url instead, or vice versa.

If that still doesn't work, password-less ssh keys and using ssh urls for push repos works great without the hassle.  As long as your homedir is secure then you should be fine.

I use ssh urls exclusively, both `git@example.com:group/repo.git` and `ssh://git@example.com/group/repo.git` style urls, but it really should work either way.

Also, which version are you on?  https://packages.ubuntu.com/search?keywords=git-cola

There was a change in v2.2 related to askpass programs that you might need, so I would suggest running `./bin/git-cola` from master for comparison if you're on an older release.

**Comment by SourceCodeDeleted** [comment]
I am surprised this is almost 2 years old. 

Leading username and password would be a good implementation. It' doesn't need to save it to disk , but it should at least prompt for this or prompt if SSH key is not in use.

**Comment by davvid** [comment]
This has already been addressed as far as I can tell.
