### ISSUE TITLE
Debian repository

### ISSUE THREAD

**Issue by shakenov-chinga** [git-cola/git-cola#923]
Hi, everybody!
The latest git-cola version in Debian 9.7 x64 stable repositories is git-cola 2.10-1. How do I install git-cola on my PC, so I would be able to update it with `apt-get upgrade` command in terminal?

Thanks in advance!

**Comment by jm4R** [comment]
You should rather make issue in Debians bug tracker.

**Comment by davvid** [comment]
Please cc: me on any related debian issues. I did get a notice from them that one of our dependencies (qtpy) was going to be removed, but that's probably been resolved by now.

The latest versions should be much easier to package in debian, but we did change the files we release so I suspec that there's going to be some work before the upcoming v4.0.0 release is packaged.

If you have one installed via `apt` already then you can easily run `git-cola` from the source tree by cloning the repo and running `./bin/git-cola` directly.
