### ISSUE TITLE
Add 'git-cola here' to directory context menu on windows

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#928]
I use git-cola on both Linux and Windows. On Linux I can open directory with any application I choose so it is not a big deal but on Windows I can not do such things. The workaround is to add appropriate item to the windows registry:
https://stackoverflow.com/questions/20449316/how-add-context-menu-item-to-windows-explorer-for-folders

Can we add such feature to the Windows installer? "Windows for Git" installer already adds `Git Bash Here` and `Git GUI Here` so we may add similar item consistently.

**Comment by davvid** [comment]
Related-to #831 

The link in that issue suggests that we should derive from their base template to add the shell integration stuff.  It uses nsis under the hood so this should be doable for someone familiar with nsis.
