### ISSUE TITLE
ComboBoxes in properties doesn't work with Qt4

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#929]
After I added 2 combo boxes in Preferences->Appearance tab, I realized that it will not work with versions older than 5.2 as I use `currentData` property:
https://doc.qt.io/qt-5/qcombobox.html#currentData-prop

Please inform me if we should support Qt4. If so, maybe I will try to redesign usage of `QComboBox`es in preferences to not use `currentData` property .

**Comment by davvid** [comment]
Yeah, it would be good to continue supporting Qt4 for a bit longer since that's still a supported configuration.  Thanks for the heads-up.
