### ISSUE TITLE
"_q_startOperation was called more than once" error message in console

### ISSUE THREAD

**Issue by PetrGlad** [git-cola/git-cola#933]
Running git-cola shows this error in console:
```
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://gravatar.com/avatar/0a852575aff62f77deb45066feb17277?s=48&d=https%3A%2F%2Fgit-cola.github.io%2Fimages%2Fgit-64x64.jpg")
```
Expected behavior would avoid this warning, perhaps.

Also a question: why one would need to download avatar every time instead of packaging it? Are you tracking installations?

Version:
```
Git Cola version 3.0 
Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic 
Python (/usr/bin/python3) 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
Git 2.17.1 
Qt 5.12.1 
QtPy 1.3.1 
PyQt5 5.12 
```
Running in VirtualBox 6.x

**Comment by davvid** [comment]
That's just the thing that looks up the user's icon when you're looking through the DAG viewer.  It's impossible to package every user's icon in the entire world, but we've approximated infinite storage by letting every client have its own in-memory cache until they restart, and letting gravatar handle the storage.

Do we track installations?  No.  No serious hacker tool would do something so short-sighted. 

Using gravatar would be a really terrible way of tracking users, but if you're still paranoid I can explain why it's not really a big deal.

Sure, gravatar.com knows that that you looked up someone's icon, but only if that person has already opted-in to the gravatar service themselves.  I'm sure they have better things to do than to try to reverse-hash the hashes sent by clients, but besides the point that it's computationally expensive($$$), the more likely truth is that they really don't care that random person on the internet Alice looked up the unknown icon for unknown user Bob.  Furthermore, they don't even know it's Bob unless he signed up in the first place.  By signing up he adds his email and icon to their hash table of hash(email) => icon.

The true purpose of the service is to allow users to see their personal icons in various apps.  But, the key part is that the user has opted in and has chosen to see their icon in various apps by signing up for the gravatar service.  For users that haven't, they just get a stock icon.

**Comment by PetrGlad** [comment]
The storage is few Kb, not infinite - it's git-cola's own icon.
I'd prefer to have an option to limit unwanted external interactions as it potentially can leak something sensitive.

The problem is the message itself, apparently Qt does not expect this call sequence.

**Comment by davvid** [comment]
As I noted, there is nothing we can do from our side about the message -- it has to be fixed upstream in Qt.  When we detect that we are requesting our own icon we don't download it -- we use the shipped version.  The URL is just there so that we can detect that situation.  Feel free to submit a change to disable gravatar usage, maybe when `git config --global cola.gravatar false` is set we can skip trying to do that.

**Comment by davvid** [comment]
I've added a feature to disable all use of gravatar. Thanks for the heads-up about the privacy concerns.

```
git config --global cola.gravatar false
```

The same setting is available in the Preferences dialog.
