### ISSUE TITLE
PySide2 doesn't provide QtCore.QT_VERSION

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#938]
In the `hidpi.py` file:

    from qtpy.QtCore import QT_VERSION

is broken when using PySide2. There should be more common way to check Qt version.

**Comment by davvid** [comment]
This should be easy to rework into a `version.check(...)` call testing against `QtCore.__version__`.  qtpy seems to paper over the differences by shuttling the value into a consistent `__version__` field.
