### ISSUE TITLE
Searching for text in commit titles in git-dag

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#941]
I can't find a way search for specific text in the commit title.

Steps that I take.
1. I open my repository.
2. I press on Branch --> Visualize All Branches
3. I try to enter into the log space the following --grep='gggg' 
4. But the moment I press on the single quote I get the "Python stopped working error"

How else can I search for a specific commit title containing text.

OS: windows 7
normal git-cola install v3.3
Git version 2.17.1.windows.2

Any help would be appreciated.

**Comment by davvid** [comment]
This looks like a Python3 regression (though they might call it a feature).  Ah, python3, the upgrade that keeps on giving.

In Python2.7 `shlex.split()` was robust to missing quotes and escape sequences without an actual escape character (for example, a single `\`), but it seems like they've made it stricter (and less robust) recently.  I can reproduce this in python3.7; it could be in earlier 3.x versions too.  It might behoove us to vendor the older shlex.split() implementation since this used to work just fine.

**Comment by davvid** [comment]
Please test master if you can.  This works now in all versions of python (it was previously working in python2 only).

**Comment by NielBuys** [comment]
Hi Thanks for reply, can you provide steps of how I can overwrite the installed files with master.
I expect if I uninstall the installed git-cola, and clone the files from git. I will have to install the requirements manually.
I suspect it won't be as easy as overwriting all the files in the installation folder with the git master files.

**Comment by davvid** [comment]
True, in order for you to generate an installer you'll need `pynsist` installed and a python toolchain.  It's kind of a lot of effort.. but it is the usual `pip install pynsist PyQt5` in a virtualenv if you're used to the python workflow.  The main entry point is `./contrib/win32/run-pynsist.sh` if you're curious to try it out.

The simplest way is to copy the `cola/utils.py` file from master and copy it over to the installed location's `cola/utils.py`.  I wouldn't recommend that in general, but for this case it'll work just fine.

The installer typically drops that file at `/c/Program Files (x86)/git-cola/pkgs/cola/utils.py` so you can just replace that file for now until the next release.

**Comment by davvid** [comment]
Oh, and in case you did just want to replace all the files, that actually should work just fine in general.

The folders to replace are `pkgs/cola` and `pkgs/qtpy` with folders from the root of the source tree.

The `share` directories are needed too (docs, icons).  Those are the parts that change between releases.  You'll want to copy without removing other stuff in installed `share` (generated docs) ~ the source tree contains less than the installed tree so be careful not to remove existing folders when copying over.

**Comment by NielBuys** [comment]
Thanks for the help it looks like its working. I replaced all the mentioned folders and I could use the grep option.
