### ISSUE TITLE
Make status panel more intuitive

### ISSUE THREAD

**Issue by piegamesde** [git-cola/git-cola#944]
I'm currently trying out a lot of graphical git clients and I'd like to give you some feedback to make the status panel more intuitive:

- The icons are not consistent: Some icons refer to the file type of a file, but others symbolize the status of the file and yet others indicate the change of the type. Please settle on one information to display through the icon and use it everywhere in the panel. Personally, I'd go for added/removed/modified/renamed icons, but that is clearly biased from my GitKraken background
- The grouping of changes is not communicated clearly. The changes have a hierarchy but are presented as list. The gui currently does not make it clear that "Modified", "Untracked" etc. are not just files, but categories that can even be collapsed. To resolve this, I'd suggest indenting all entries to create a visual hierarchy. Alternatively, split the view into multiple list panels (one for staged and one for unstaged changes)
- This may be not true to how git works, but displaying untracked files as added file makes it more intuitive to users less familiar with git.

**Comment by jm4R** [comment]
* 2nd is already fixed, but not released (indentation will be optional in the next `git-cola` release)
 * 3rd - one of the great thinks about `git-cola` is naming convention. Almost everything is named in the same way that `git` does. I wouldn't change that path.

**Comment by piegamesde** [comment]
Oh yes, *way* better. Would you mind checking the option by default when updating (or at least for new users)?

And what about the icons? I'm willing to help out if needed (if so, please point me to some source files I should start looking into).
