### ISSUE TITLE
"Revert Unstaged Edits..." reverts also staged edits

### ISSUE THREAD

**Issue by travnick** [git-cola/git-cola#947]
Steps to reproduce
1. Make many changes to file.
2. Mark part of them as "staged"
3. Execute "Revert Unstaged Edits..." on file visible in modified section.
4. All changes are gone, even those which were staged before.

This looks like quite serious bug.

```
Git Cola version 3.3 (v3.3) 
Windows-10-10.0.17763-SP0 
Python (C:\Program Files (x86)\git-cola\Python\python.exe) 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] 
Git 2.21.0.windows.1 
Qt 5.10.1 
QtPy 1.6.0 
PyQt5 5.10.1 
```

**Comment by davvid** [comment]
This should be critical, and I use this feature all the time, but unfortunately I just tried it and it worked fine so we're going to have to dig in deeper to see why you're hitting this.

What you're describing shouldn't happen.  We use core git commands so we can always trace this back to a git invocation.

Can you maybe zip up a representative repo that demonstrates the issue?

I basically edited a file, staged a few lines interactively, and then did the "Revert Unstaged Edits" command when right-clicking on the same file in the Modified files list.  It worked fine and the staged edits were still present in the index/stage, and in the on-disk file.

To debug this, you'll have to be able to run out of the source tree, or at least be able to set environment variables when running cola.  e.g. `env GIT_COLA_TRACE=1 git cola` in a git bash shell should run it in debug mode.

When in that mode cola will print out every single git command it runs.  The idea would be to isolate this behavior down to the specific git commands.  Basically reproduce the issue, and then see what the corresponding command it's printing at that time.

Were you in "Amend" mode?  That could be related.  I'll test that now in case it's related.

**Comment by davvid** [comment]
I think you probably must have been in amend mode.  I'm going to tweak the behavior so that it never happens, ever.  Thanks for the report.

**Comment by travnick** [comment]
You are right. It happens in "Amend" mode only. Sorry for missing this detail.
