### ISSUE TITLE
Feature request: Show server response messages with clickable URLs when pushing

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#951]
It's common for git server response messages to include messages with a convenient URL to e.g. create a PR/MR for a newly pushed branch. It would be nice if git-cola showed these messages with any URLs as clickable links.

**Comment by davvid** [comment]
This was first implemented in `v4.2.0`.

**Comment by davvid** [comment]
Thanks to @bensmrs who also added a feature to display remote messages in a dedicated dialog (outside of the already existing Console widget output).

This is an opt-in feature. There's a new, "Show remote messages" checkbox in the Push dialog.
