### ISSUE TITLE
Feature request: auto-fetch in background and notify

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#952]
There is a great functionality in one of competitor application - you may enable automatic fetch for each customizable period of time (eg. 1 minute) and - if there is change on remote - it notifies user.

If maintainers doesn't have enough resources - would pull-request with such feature be welcome?

**Comment by piegamesde** [comment]
Duplicate of #361

**Comment by davvid** [comment]
https://github.com/git-cola/git-cola/commit/3cb3c91654e4d71af154f2b0dd21936e3535296e
