### ISSUE TITLE
win32 random hotkey failure on startup

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#955]
There's an issue on win32 where starting the application through `pythonw` breaks `QShortcut` hotkeys until the main window is unfocused, then focused again. I've had the same issue in my own project using Qt5 and narrowed it down to a `QWidget::raise()` call. The call is necessary on OSX but causes this issue on win32. Eventually I settled on,

```c++
        d.show();
#ifdef __APPLE__
        d.raise(); // OSX
#endif
        d.activateWindow(); // Windows, doesn't hurt Linux or OSX
```

I'd rather not send a pull request making such a sweeping change (note the amount of show/raise calls in git-cola) without discussing this first. Should this go into `cola.widgets.standard.WidgetMixin`?

**Comment by davvid** [comment]
Amazing sleuthing.  This does make sense in the WidgetMixin.

**Comment by sthalik** [comment]
I'd go for overriding all cases of `show` and removing all `raise` calls. I'm afraid going over all call sites on a case-by-case basis can lead to many regressions. Moreover, I'd call this new `show` `show_` or something similar to avoid cases where something accidentally doesn't inherit from the mixin. Either this or use an unbound function in the util module. Is this acceptable?

**Comment by davvid** [comment]
An unbound function in the `qtutils` seems like the better choice.  It's probably best to avoid stuff like `x.show_()` if possible.

**Comment by sthalik** [comment]
I haven't been able to reproduce it for more than a year.
