### ISSUE TITLE
UI broken in linux GNOME3 dark theme.

### ISSUE THREAD

**Issue by david0might** [git-cola/git-cola#957]
Hi there,

After updating from Fedora 28 to Fedora 30, I noticed that git-cola does not honor the dark-theme anymore as set in GNOME tweaks for the applications.

This seems to be some kind of regression.

GNOME Shell version is:
```
$ gnome-shell --version
GNOME Shell 3.32.2
```

I ve tried both with the git-cola 3,2 version from fedora repos, and then with the 3.3 version from this GitHub.

Both use the default theme now.

May be there is something I am missing about some local git-cola configuration for the theme... but couldn't find anything too ovbious.

What is the status on this?

Regards

**Comment by s101d1** [comment]
I got same issue too in antergos (arch linux) after upgrading it to v3.3.

**Comment by davvid** [comment]
I have the `adwaita-qt` package installed and I set `QT_STYLE_OVERRIDE=adwaita-dark` in my environment and that gets the default Qt theme for cola (and most other Qt apps as well) to use a dark theme that matches gnome.

Alternatively, you should be able to use the new Appearance tab in the preferences and select a dark theme.  There's also a dark icon theme you have to enable using `git config --global cola.icontheme dark`

We should probably make the icon theme configurable through the preferences screen too.

**Comment by davvid** [comment]
(I sometimes do things the old-fashioned way) -- a better approach then setting environment variables might be to use the `qt5ct` qt5 configuration tool to set the default theme.  I just tried this and that worked too.

Let me know if that does the trick for you.  I wish there was an option to just have Qt follow gnome's theme.  Perhaps there's already a way (or someone is working on it) -- I wouldn't be surprised if there's a way to do that too.

**Comment by david0might** [comment]
Hi @davvid, tried both setting `QT_STYLE_OVERRIDE=adwaita-dark`, as in:
```
$ QT_STYLE_OVERRIDE=adwaita-dark git-cola
```
and also to uinstall `qt5ct` and change things in the **appearance** tab to look similar to GNOME:
```
$ QT_QPA_PLATFORMTHEME=qt5ct git-cola
```
Both seem to be ignored by `git-cola` for some unknown reason... may be there is something about Qt apps that I am missing.
N.B. I take the **appearance** tab you were referring to is the one in `qt5ct`, as I see none in `git-cola` **prefernces**.

Regards

**Comment by david0might** [comment]
False alarm...

Seems that, after running qt5ct, I need to logout and back in again for the changes to take effect.
Also, need to export the `QT_QPA_PLATFORMTHEME="qt5ct"` in my `.bash_profile`.

Now also `vimpal` show dark theme in some bits it was missing.

Note that this works only on git-cola-3.3, but not on git-cola-3.2.

Thanks.

**Comment by davvid** [comment]
Please test with master, too ;-) The appearance tab is in the newer versions.

I actually noticed that we're doing something (namely, calling `setPalette(...)`) that will interfere with `qt5ct` and being able to override Qt settings, so I'm going to change it so that we don't do that when using the `default` theme, which makes sense since it was supposed to represent the original behavior.

Heads-up @jm4R tho I doubt this will impact your use case since it will only involve the behavior when using the default theme.  Being able to closely follow the themes provided by the style engine is a good feature so we'll make sure to keep that working.

Thanks for the heads-up about `QT_QPA_PLATFORMTHEME=qt5ct`.  I'm going to start using that now instead and add a note to our docs about it.

**Comment by jm4R** [comment]
> Heads-up @jm4R tho I doubt this will impact your use case since it will only involve the behavior when using the default theme. Being able to closely follow the themes provided by the style engine is a good feature so we'll make sure to keep that working.

Yes, it was one of my goals to make default theme work exactly like before. Thanks for the fix.
