### ISSUE TITLE
Add Slackware to installation section

### ISSUE THREAD

**Issue by richarson** [git-cola/git-cola#959]
Hello,

git-cola has been available for some time in SlackBuilds.org:

http://slackbuilds.org/result/?search=git-cola

Can you add it to the README?
Or should I just make a pull request?

Thanks!

**Comment by davvid** [comment]
Thanks for the heads-up, slackware is rad.  Sure thing, a PR would be much appreciated.  Is there a one-liner command to install the package that users can use?

**Comment by richarson** [comment]
Sorry, I completely missed notifications for this.

There's no one-liner, there are some SlackBuild helpers (like yaourt and similar for Arch's AUR) but the canonical way is to download the files and execute the .Slackbuild script.

I can provide instructions in a PR.

**Comment by richarson** [comment]
I submited #962 with a link to SBo's search page for git-cola based on your Arch link to AUR.

I was going to make an alternative PR with full instructions but SBo already has a nice [Howto](https://slackbuilds.org/howto/), and my instructions would be tied to a particular version of Slackware, which I don't really like.

Anyway, Slackers using SBo should know what they're doing, or where to ask for help :)
