### ISSUE TITLE
Empty list of recent repositories

### ISSUE THREAD

**Issue by ebousse** [git-cola/git-cola#960]
Although I have been using git-cola on my system for many git repos, when I start it I always have an empty list of recent repositories:
![Capture d’écran du 2019-06-28 09-03-53](https://user-images.githubusercontent.com/5868014/60323922-ab95d680-9983-11e9-81ab-99cfc0df24fe.png)
And same thing in the list  of recent repos available from the menu, which remains empty.

I have checked and my "recent repository count" is more than zero:
![Capture d’écran du 2019-06-28 09-04-27](https://user-images.githubusercontent.com/5868014/60323977-c9fbd200-9983-11e9-9db5-3b2494ce1618.png)

Maybe I am missing something?

**Comment by davvid** [comment]
Hmm, this is interesting.  What OS/platform are you using, Linux?  We typically save settings in `~/.config/git-cola/settings`.

The `settings` file is a plain-text JSON file with a dictionary of settings.  The `"recent"` key is where the list of recent repositories are stored.  Does your file contain entries in the `"recent"` block?

Here is another possible explanation.  Have you disabled the `Save GUI Settings` preference?

The recent files and bookmark saving is currently tied to the general GUI state saving, so disabling that option could have this effect.  It would be good to decouple that.  Does that setting make a difference?

**Comment by ebousse** [comment]
Indeed, I had disabled the `Save GUI Settings` preference, and re-enabling it does solve the problem! Thank you! I had not expected that this would have an impact on this list of recent files :).

**Comment by davvid** [comment]
I'll leave this issue open to address decoupling that behavior.  Thanks for the heads-up.

**Comment by VeganHunter** [comment]
I believe this issue should be closed.

Unless I'm mistaken, that behavior is now decoupled. I've tried adding repos while having the `Save GUI Settings` preference disabled, and they've correctly been added to my list of recent repos.

**Comment by davvid** [comment]
cheers
