### ISSUE TITLE
Diff tool not opening error.

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#966]
I installed a new Windows 10 environment. But I can't get my diff tool meld to launch. git-cola gives an error. I used the exact same .gitconfig settings as on my Windows 7 environment.
The gitconfig settings work in windows 7 and in Gitkraken on Windows 10.

See Attached the error message
![image](https://user-images.githubusercontent.com/8427483/61452951-3e130f80-a95d-11e9-92fb-1cc18a8b47b5.png)

The gitconfig setup is as follows.
```
[merge]
        tool = meld
[mergetool "meld"]
        cmd = \"C:/Program Files (x86)/Meld/Meld.exe\" \"$LOCAL\" \"$MERGED\" \"$REMOTE\" --output \"$MERGED\"
        path = C:/Program Files (x86)/Meld/Meld.exe
[diff]
        tool = meld
        guitool = meld
[difftool]
         prompt = false
 [difftool "meld"]
         cmd = \"C:/Program Files (x86)/Meld/Meld.exe\" \"$LOCAL\" \"$REMOTE\"
         path = C:/Program Files (x86)/Meld/Meld.exe
```

git-cola version: 3.4
Windows 10 64 bit
git v2.22 64 bit

Thanks in advance

**Comment by NielBuys** [comment]
Mmmmm. Just read on Meld tool site "Note: The 3.20 Windows build uses a new build chain. If you experience issues, please use Meld 3.18.3." On my windows 7 I have Meld 1.18.2. After uninstalling Meld 3.20 and installing 3.18.3 the meld diff tool open.
Both apps is Python apps. So it looks like git-cola and Meld 3.20 version don't want to talk to each other.

Not sure where I need to log the issue. I will search where to log the issue on the meld tool and paste the link to the issue here.

**Comment by NielBuys** [comment]
Link to Meld issue https://gitlab.gnome.org/GNOME/meld/issues/353

**Comment by davvid** [comment]
One thing you might want to consider is removing your custom meld configuration.  We use the core `git difftool` command, which already contains a command recipe for meld.

The only thing you might need to configure is `difftool.meld.path` / `mergetool.meld.path`.  Try it out by commenting-out the `cmd` configuration.

**Comment by davvid** [comment]
For reference, see https://github.com/git/git/blob/master/mergetools/meld

We do version detection to see whether the `--output` flag is needed -- some versions do not support it.  You can configure `git config mergetool.meld.hasOutput false` (or `true`) to skip the auto-detection and use the specified command style.

The real difference is that older versions of meld support `--output`, and newer ones do not.  The meld script I added to core git attempts to auto-detect whether the flag is needed, and allows you to override the autodetection via optional confguration.

**Comment by davvid** [comment]
Oh, sorry, I was just talking about a potential command-line difference, but the errors listed in the screenshot are something completely unrelated.

The error message does look to be just purely a problem related to running meld itself, and not really cola specific.  Sorry for the distraction about the configuration, though it is true that it's better to use the built-in recipe (if possible).

**Comment by NielBuys** [comment]
Thanks for reply I will test the build in recipe.
