### ISSUE TITLE
How to start git-cola in a different language to the operation system on Windows?

### ISSUE THREAD

**Issue by clouddemo1** [git-cola/git-cola#976]
I'm on a Japanese Windows system, but I want to use git-cola in English. I can't find any option to change its language in git-cola. I have searched and found this issue https://github.com/git-cola/git-cola/issues/140 . But that issue is on the Linux system. How to start git-cola in a different language to the operation system on Windows?

**Comment by davvid** [comment]
If you go into your home directory and find the `_config` (or `.config` on unix systems) directory, in there you'll find a `git-cola` folder.  Create a file (with no extension) called `language` with the following content and it will override the language:

        en_US.UTF-8

Typically one could do it like this from the command-line:

        $ echo en_US.UTF-8 > ~/.config/git-cola/language

**Comment by clouddemo1** [comment]
It works, thanks!

**Comment by prof7bit** [comment]
changing the language completely changes the panel layout! What is the reason for this?
