### ISSUE TITLE
Deleting local branch doesn't update the UI

### ISSUE THREAD

**Issue by s101d1** [git-cola/git-cola#978]
I'm on Git Cola v3.4 in manjaro linux.

How to produce the issue:

* In the Branches view, delete one of the local branch item (right click -> Delete Branch).
* In the confirmation dialog, click "Delete Branch" button to proceed.
* The deleted local branch item is still shown in the Branches view.

If you try to delete the branch again, you will get error message: "delete_local returned exit status 1".

So basically the branch had been deleted, but the git-cola UI still shows the branch in the list. The UI doesn't get updated after the delete branch is performed. You have to restart the git-cola to make the deleted branch disappear.

---------

Also, could you add keyboard shortcut for deleting branch, maybe `Shift + Delete` ? and add support for multiple selection of the branch items, so I can delete them in one action.

**Comment by davvid** [comment]
Reopening for the Shift+Delete hotkey and multi-select request.

**Comment by ibraheem5022** [comment]
> I'm on Git Cola v3.4 in manjaro linux.
> 
> How to produce the issue:
> 
> * In the Branches view, delete one of the local branch item (right click -> Delete Branch).
> * In the confirmation dialog, click "Delete Branch" button to proceed.
> * The deleted local branch item is still shown in the Branches view.
> 
> If you try to delete the branch again, you will get error message: "delete_local returned exit status 1".
> 
> So basically the branch had been deleted, but the git-cola UI still shows the branch in the list. The UI doesn't get updated after the delete branch is performed. You have to restart the git-cola to make the deleted branch disappear.
> 
> Also, could you add keyboard shortcut for deleting branch, maybe `Shift + Delete` ? and add support for multiple selection of the branch items, so I can delete them in one action.

**Comment by sonulohani** [comment]
Hi @davvid ,

Could you please assign this issue to me. I want to contribute to this project and working on this issue would be a good start for me.

Thank you.

**Comment by sonulohani** [comment]
This problem is due to the current branch, which is set to the one which you're trying to delete. Since the branch is current, so git can't delete the branch until the current branch is switched to some other branch. You can’t delete the branch you’re currently on. 

We need to make changes in the code which tells the user to switch to other branch if we are trying to delete the current branch instead of throwing the error which the user can't understand. I will make the fix and create the PR for the same.

**Comment by sonulohani** [comment]
Hi @davvid ,

As per my understanding no changes are required to make this fix as the application is working as expected. I am attaching the screenshot where you can see that git command error and the git-cola error is same and is what expected. I've already explained above on what causing the error. If you don't have any comments then we can close this issue. 

![git_error_screenshot](https://user-images.githubusercontent.com/2958681/82174028-fa769280-98ec-11ea-86b8-dc2d5a9f77b4.png)

![git_cola_error_screenshot](https://user-images.githubusercontent.com/2958681/82174035-02363700-98ed-11ea-8525-cea96128d0a0.png)

**Comment by s101d1** [comment]
Hi all,

I just tried it again with v3.6 and I can't reproduce the delete branch issue, so it seems the issue had been fixed.

@sonulohani It seems your issue is different than mine, on my case it's about deleting another branch (not the current one). But anyway, I can't reproduce your issue, on the right click menu for current branch, there is no "Delete Branch" menu at all. Perhaps you're using older version of git-cola? If you are able to reproduce the issue, you might want to create a new issuge page for that with detailed information on how to reproduce the issue.

@davvid I think this issue page can be closed. For Shift+Delete hotkey and multi-select request feature, you can just create a new separate issue page for that.

**Comment by davvid** [comment]
Thanks for verifying.  I'm about to tag v3.7, thank you!
