### ISSUE TITLE
Fedora package broken somehow

### ISSUE THREAD

**Issue by jshamg** [git-cola/git-cola#979]
I just skip using this tool now, because on up to date fedora 30 it is not working. It starts with the
`qtpy.PythonQtError: No Qt bindings could be found` Error and i don't want to install any unlisted decencies or whatever. Never experienced broken packages in a distro-own repo...

**Comment by rafaelreuber** [comment]
Hi @jshamg. There is [3 bugs reported](https://apps.fedoraproject.org/packages/git-cola/) on the Fedora git-cola package related to QT.

You can try to install the dependences manually (using dnf) on run git-cola from sources.

**Comment by jshamg** [comment]
@rafaelreuber it works with those dependecies! Thanks, i was missing python3-pyside...
