### ISSUE TITLE
No need to check remote on delete

### ISSUE THREAD

**Issue by WanWizard** [git-cola/git-cola#986]
Now it tries to contect the remote when you press the "-" to delete it, which takes an absolute age when the remote can't be reached for whatever reason. The UI hangs on "Gathering info for "<remote name>", for several minutes, before finally continuing with the delete.

Not sure why it tries to contact the remote when you want to delete it?

git-cola version: current master.

**Comment by davvid** [comment]
Is this in the `Branches` widget?  When deleting remote branches we actually delete them on the server.  But local branches should be instant.  Unfortunately, yes, we do block on this operation.  It would be good to not do that, and will require a bit of refactoring.

**Comment by WanWizard** [comment]
No,this is not about branches, but about the remote repo definitions (menu - File - Edit Remotes).

I have a local repo with 4 remotes: our gitolite server, the clients github account, the staging server and the production server. The client changed hosting providers, so I created new entries for staging and production (so I could test those). 

After the new servers went live, I wanted to delete the remotes for the old servers, which tool absolute ages because it tried to contact those remotes (which failed, the servers were gone at that point).

So: to be able to delete a remote you need to select the remote first. Selecting the remote contacts the remote (the section on the right says "Gathering info on <remotename>...", and this fails if the remote no longer exists (you need to wait for a timeout).

**Comment by davvid** [comment]
Nice catch, thanks for the report.
