### ISSUE TITLE
Checking out a branch doesn't update the UI

### ISSUE THREAD

**Issue by TomDobbelaere** [git-cola/git-cola#992]
So I understand the star indicates the branch you have checked out currently.

When I checkout a different branch, it displays the executing actions progress bar. After it completes, my current branch does change in vscode, but in git-cola the star hasn't moved and it still thinks I'm checked out in the old branch.

This is on a private repository, I'm checking out a local branch.

**Comment by davvid** [comment]
Thanks for the heads-up.  I'd still like to refactor that part further by using model commands asynchronously somehow, but until then this should do the trick.
