### ISSUE TITLE
Failing regression test

### ISSUE THREAD

**Issue by bket** [git-cola/git-cola#993]
On OpenBSD I experience a failing test with git-cola 3.5. This failure is not observed with 3.4.

```
=================================== FAILURES ===================================
___________________ IconTestCase.test_from_filename_unicode ____________________

self = <test.icons_test.IconTestCase testMethod=test_from_filename_unicode>

    def test_from_filename_unicode(self):
        filename = compat.uchr(0x400) + '.odt'
        expect = 'file-code.svg'
        actual = icons.basename_from_filename(filename)
>       self.assertEqual(expect, actual)
E       AssertionError: u'file-code.svg' != u'file-text.svg'
E       - file-code.svg
E       ?      ^^^
E       + file-text.svg
E       ?      ^ ++

../icons_test.py:17: AssertionError
1 failed, 166 passed in 15.36 seconds
```

Any idea where to look?

**Comment by davvid** [comment]
Hmm it could be related to mimetypes.  We might have some code where we check the mime type for the `xxx.odt` filename and it's giving a different result on openbsd.

That test should probably be tweaked to not be platform-dependent, maybe by choosing a more stable extension such as `.txt`.  Thanks for the heads-up. That should be a harmless failure.
