### ISSUE TITLE
Git-cola crash on branch delete

### ISSUE THREAD

**Issue by akontsevich** [git-cola/git-cola#997]
Steps to reproduce:
1. Delete 1st inactive branch
2. Delete 2nd inactive branch -> crash

**Stack trace:**
```
> git-cola
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/qtutils.py", line 35, in <lambda>
    action.triggered[bool].connect(lambda x: fn())
  File "/usr/share/git-cola/lib/cola/widgets/branch.py", line 441, in delete_action
    branch = self.tree_helper.get_full_name(self.selected_item(), SLASH)
  File "/usr/share/git-cola/lib/cola/widgets/branch.py", line 547, in get_full_name
    parents = [item.name]
AttributeError: 'NoneType' object has no attribute 'name'
Segmentation fault
```

**Comment by davvid** [comment]
Thanks for the report.  I believe this was fixed in the latest release, and subsequent refactorings should have eliminated this condition.  Please test the latest on master and let me know if you're still seeing this.  You can run directly from the source tree very easily:

```
# clone (one-time setup)
mkdir -p ~/src
git clone git://github.com/git-cola/git-cola.git ~/src/git-cola

# run in-place
~/src/git-cola/bin/git-cola
```

**Comment by akontsevich** [comment]
> I believe this was fixed in the latest release
Which version is it?

**Comment by davvid** [comment]
`v3.5` is the most recent release.  master has additional robustness in this area in case that version isn't sufficient.

**Comment by akontsevich** [comment]
Ok, thanks, will ask suse guy to update.

**Comment by akontsevich** [comment]
No, not fixed: crash on branch rename. Please reopen!

**Comment by davvid** [comment]
Thanks for the heads-up.  I'll tag `v3.6` soon.
